// This file was generated by gir (https://github.com/gtk-rs/gir)
// from build
// from subprojects/gir-files
// DO NOT EDIT

use crate::ffi;
use glib::{
    prelude::*,
    signal::{connect_raw, SignalHandlerId},
    translate::*,
};
use std::boxed::Box as Box_;

glib::wrapper! {
    #[doc(alias = "AwraDataColumn")]
    pub struct DataColumn(Object<ffi::AwraDataColumn, ffi::AwraDataColumnClass>);

    match fn {
        type_ => || ffi::awra_data_column_get_type(),
    }
}

impl DataColumn {
    #[doc(alias = "awra_data_column_new")]
    pub fn new(
        title: Option<&str>,
        factory: Option<&impl IsA<gtk::ListItemFactory>>,
    ) -> DataColumn {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_full(ffi::awra_data_column_new(
                title.to_glib_none().0,
                factory.map(|p| p.as_ref()).to_glib_none().0,
            ))
        }
    }

    // rustdoc-stripper-ignore-next
    /// Creates a new builder-pattern struct instance to construct [`DataColumn`] objects.
    ///
    /// This method returns an instance of [`DataColumnBuilder`](crate::builders::DataColumnBuilder) which can be used to create [`DataColumn`] objects.
    pub fn builder() -> DataColumnBuilder {
        DataColumnBuilder::new()
    }

    #[doc(alias = "awra_data_column_apply_alignment")]
    pub fn apply_alignment(&self, cell: &impl IsA<gtk::Widget>) {
        unsafe {
            ffi::awra_data_column_apply_alignment(
                self.to_glib_none().0,
                cell.as_ref().to_glib_none().0,
            );
        }
    }

    #[doc(alias = "awra_data_column_get_alignment")]
    #[doc(alias = "get_alignment")]
    pub fn alignment(&self) -> gtk::Align {
        unsafe { from_glib(ffi::awra_data_column_get_alignment(self.to_glib_none().0)) }
    }

    #[doc(alias = "awra_data_column_get_delegate")]
    #[doc(alias = "get_delegate")]
    pub fn delegate(&self) -> gtk::ColumnViewColumn {
        unsafe { from_glib_none(ffi::awra_data_column_get_delegate(self.to_glib_none().0)) }
    }

    #[doc(alias = "awra_data_column_get_expand")]
    #[doc(alias = "get_expand")]
    #[doc(alias = "expand")]
    pub fn expands(&self) -> bool {
        unsafe { from_glib(ffi::awra_data_column_get_expand(self.to_glib_none().0)) }
    }

    #[doc(alias = "awra_data_column_get_factory")]
    #[doc(alias = "get_factory")]
    pub fn factory(&self) -> Option<gtk::ListItemFactory> {
        unsafe { from_glib_none(ffi::awra_data_column_get_factory(self.to_glib_none().0)) }
    }

    #[doc(alias = "awra_data_column_get_fixed_width")]
    #[doc(alias = "get_fixed_width")]
    #[doc(alias = "fixed-width")]
    pub fn fixed_width(&self) -> i32 {
        unsafe { ffi::awra_data_column_get_fixed_width(self.to_glib_none().0) }
    }

    #[doc(alias = "awra_data_column_get_resizable")]
    #[doc(alias = "get_resizable")]
    #[doc(alias = "resizable")]
    pub fn is_resizable(&self) -> bool {
        unsafe { from_glib(ffi::awra_data_column_get_resizable(self.to_glib_none().0)) }
    }

    #[doc(alias = "awra_data_column_get_sorter")]
    #[doc(alias = "get_sorter")]
    pub fn sorter(&self) -> Option<gtk::Sorter> {
        unsafe { from_glib_none(ffi::awra_data_column_get_sorter(self.to_glib_none().0)) }
    }

    #[doc(alias = "awra_data_column_get_title")]
    #[doc(alias = "get_title")]
    pub fn title(&self) -> glib::GString {
        unsafe { from_glib_none(ffi::awra_data_column_get_title(self.to_glib_none().0)) }
    }

    #[doc(alias = "awra_data_column_set_alignment")]
    #[doc(alias = "alignment")]
    pub fn set_alignment(&self, alignment: gtk::Align) {
        unsafe {
            ffi::awra_data_column_set_alignment(self.to_glib_none().0, alignment.into_glib());
        }
    }

    #[doc(alias = "awra_data_column_set_expand")]
    #[doc(alias = "expand")]
    pub fn set_expand(&self, expand: bool) {
        unsafe {
            ffi::awra_data_column_set_expand(self.to_glib_none().0, expand.into_glib());
        }
    }

    #[doc(alias = "awra_data_column_set_factory")]
    #[doc(alias = "factory")]
    pub fn set_factory(&self, factory: Option<&impl IsA<gtk::ListItemFactory>>) {
        unsafe {
            ffi::awra_data_column_set_factory(
                self.to_glib_none().0,
                factory.map(|p| p.as_ref()).to_glib_none().0,
            );
        }
    }

    #[doc(alias = "awra_data_column_set_fixed_width")]
    #[doc(alias = "fixed-width")]
    pub fn set_fixed_width(&self, width: i32) {
        unsafe {
            ffi::awra_data_column_set_fixed_width(self.to_glib_none().0, width);
        }
    }

    #[doc(alias = "awra_data_column_set_resizable")]
    #[doc(alias = "resizable")]
    pub fn set_resizable(&self, resizable: bool) {
        unsafe {
            ffi::awra_data_column_set_resizable(self.to_glib_none().0, resizable.into_glib());
        }
    }

    #[doc(alias = "awra_data_column_set_sorter")]
    #[doc(alias = "sorter")]
    pub fn set_sorter(&self, sorter: Option<&impl IsA<gtk::Sorter>>) {
        unsafe {
            ffi::awra_data_column_set_sorter(
                self.to_glib_none().0,
                sorter.map(|p| p.as_ref()).to_glib_none().0,
            );
        }
    }

    #[doc(alias = "awra_data_column_set_title")]
    #[doc(alias = "title")]
    pub fn set_title(&self, title: &str) {
        unsafe {
            ffi::awra_data_column_set_title(self.to_glib_none().0, title.to_glib_none().0);
        }
    }

    #[doc(alias = "alignment")]
    pub fn connect_alignment_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_alignment_trampoline<F: Fn(&DataColumn) + 'static>(
            this: *mut ffi::AwraDataColumn,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::alignment".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_alignment_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "expand")]
    pub fn connect_expand_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_expand_trampoline<F: Fn(&DataColumn) + 'static>(
            this: *mut ffi::AwraDataColumn,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::expand".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_expand_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "factory")]
    pub fn connect_factory_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_factory_trampoline<F: Fn(&DataColumn) + 'static>(
            this: *mut ffi::AwraDataColumn,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::factory".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_factory_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "fixed-width")]
    pub fn connect_fixed_width_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_fixed_width_trampoline<F: Fn(&DataColumn) + 'static>(
            this: *mut ffi::AwraDataColumn,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::fixed-width".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_fixed_width_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "resizable")]
    pub fn connect_resizable_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_resizable_trampoline<F: Fn(&DataColumn) + 'static>(
            this: *mut ffi::AwraDataColumn,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::resizable".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_resizable_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "sorter")]
    pub fn connect_sorter_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_sorter_trampoline<F: Fn(&DataColumn) + 'static>(
            this: *mut ffi::AwraDataColumn,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::sorter".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_sorter_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "title")]
    pub fn connect_title_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_title_trampoline<F: Fn(&DataColumn) + 'static>(
            this: *mut ffi::AwraDataColumn,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::title".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_title_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }
}

impl Default for DataColumn {
    fn default() -> Self {
        glib::object::Object::new::<Self>()
    }
}

// rustdoc-stripper-ignore-next
/// A [builder-pattern] type to construct [`DataColumn`] objects.
///
/// [builder-pattern]: https://doc.rust-lang.org/1.0.0/style/ownership/builders.html
#[must_use = "The builder must be built to be used"]
pub struct DataColumnBuilder {
    builder: glib::object::ObjectBuilder<'static, DataColumn>,
}

impl DataColumnBuilder {
    fn new() -> Self {
        Self {
            builder: glib::object::Object::builder(),
        }
    }

    pub fn alignment(self, alignment: gtk::Align) -> Self {
        Self {
            builder: self.builder.property("alignment", alignment),
        }
    }

    pub fn expand(self, expand: bool) -> Self {
        Self {
            builder: self.builder.property("expand", expand),
        }
    }

    pub fn factory(self, factory: &impl IsA<gtk::ListItemFactory>) -> Self {
        Self {
            builder: self.builder.property("factory", factory.clone().upcast()),
        }
    }

    pub fn fixed_width(self, fixed_width: i32) -> Self {
        Self {
            builder: self.builder.property("fixed-width", fixed_width),
        }
    }

    pub fn resizable(self, resizable: bool) -> Self {
        Self {
            builder: self.builder.property("resizable", resizable),
        }
    }

    pub fn sorter(self, sorter: &impl IsA<gtk::Sorter>) -> Self {
        Self {
            builder: self.builder.property("sorter", sorter.clone().upcast()),
        }
    }

    pub fn title(self, title: impl Into<glib::GString>) -> Self {
        Self {
            builder: self.builder.property("title", title.into()),
        }
    }

    // rustdoc-stripper-ignore-next
    /// Build the [`DataColumn`].
    #[must_use = "Building the object from the builder is usually expensive and is not expected to have side effects"]
    pub fn build(self) -> DataColumn {
        assert_initialized_main_thread!();
        self.builder.build()
    }
}
