// This file was generated by gir (https://github.com/gtk-rs/gir)
// from build
// from subprojects/gir-files
// DO NOT EDIT

use crate::{ffi, DataColumn, DataViewState};
use glib::{
    prelude::*,
    signal::{connect_raw, SignalHandlerId},
    translate::*,
};
use std::boxed::Box as Box_;

#[cfg(feature = "gtk_v4_10")]
#[cfg_attr(docsrs, doc(cfg(feature = "gtk_v4_10")))]
glib::wrapper! {
    #[doc(alias = "AwraDataView")]
    pub struct DataView(Object<ffi::AwraDataView, ffi::AwraDataViewClass>) @extends gtk::Widget, gobject::InitiallyUnowned, @implements gtk::Accessible, gtk::Buildable, gtk::ConstraintTarget;

    match fn {
        type_ => || ffi::awra_data_view_get_type(),
    }
}

#[cfg(not(feature = "gtk_v4_10"))]
glib::wrapper! {
    #[doc(alias = "AwraDataView")]
    pub struct DataView(Object<ffi::AwraDataView, ffi::AwraDataViewClass>) @extends gtk::Widget, gobject::InitiallyUnowned, @implements gtk::Buildable, gtk::ConstraintTarget;

    match fn {
        type_ => || ffi::awra_data_view_get_type(),
    }
}

impl DataView {
    #[doc(alias = "awra_data_view_new")]
    pub fn new(model: Option<&impl IsA<gtk::SelectionModel>>) -> DataView {
        assert_initialized_main_thread!();
        unsafe {
            gtk::Widget::from_glib_none(ffi::awra_data_view_new(
                model.map(|p| p.as_ref()).to_glib_none().0,
            ))
            .unsafe_cast()
        }
    }

    // rustdoc-stripper-ignore-next
    /// Creates a new builder-pattern struct instance to construct [`DataView`] objects.
    ///
    /// This method returns an instance of [`DataViewBuilder`](crate::builders::DataViewBuilder) which can be used to create [`DataView`] objects.
    pub fn builder() -> DataViewBuilder {
        DataViewBuilder::new()
    }

    #[doc(alias = "awra_data_view_append_column")]
    pub fn append_column(&self, column: &DataColumn) {
        unsafe {
            ffi::awra_data_view_append_column(self.to_glib_none().0, column.to_glib_none().0);
        }
    }

    #[doc(alias = "awra_data_view_get_column")]
    #[doc(alias = "get_column")]
    pub fn column(&self, position: u32) -> Option<DataColumn> {
        unsafe {
            from_glib_none(ffi::awra_data_view_get_column(
                self.to_glib_none().0,
                position,
            ))
        }
    }

    #[doc(alias = "awra_data_view_get_delegate")]
    #[doc(alias = "get_delegate")]
    pub fn delegate(&self) -> gtk::ColumnView {
        unsafe { from_glib_none(ffi::awra_data_view_get_delegate(self.to_glib_none().0)) }
    }

    #[doc(alias = "awra_data_view_get_empty_widget")]
    #[doc(alias = "get_empty_widget")]
    #[doc(alias = "empty-widget")]
    pub fn empty_widget(&self) -> Option<gtk::Widget> {
        unsafe { from_glib_none(ffi::awra_data_view_get_empty_widget(self.to_glib_none().0)) }
    }

    #[doc(alias = "awra_data_view_get_error_widget")]
    #[doc(alias = "get_error_widget")]
    #[doc(alias = "error-widget")]
    pub fn error_widget(&self) -> Option<gtk::Widget> {
        unsafe { from_glib_none(ffi::awra_data_view_get_error_widget(self.to_glib_none().0)) }
    }

    #[doc(alias = "awra_data_view_get_loading_more")]
    #[doc(alias = "get_loading_more")]
    #[doc(alias = "loading-more")]
    pub fn is_loading_more(&self) -> bool {
        unsafe { from_glib(ffi::awra_data_view_get_loading_more(self.to_glib_none().0)) }
    }

    #[doc(alias = "awra_data_view_get_loading_widget")]
    #[doc(alias = "get_loading_widget")]
    #[doc(alias = "loading-widget")]
    pub fn loading_widget(&self) -> Option<gtk::Widget> {
        unsafe {
            from_glib_none(ffi::awra_data_view_get_loading_widget(
                self.to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "awra_data_view_get_model")]
    #[doc(alias = "get_model")]
    pub fn model(&self) -> Option<gtk::SelectionModel> {
        unsafe { from_glib_none(ffi::awra_data_view_get_model(self.to_glib_none().0)) }
    }

    #[doc(alias = "awra_data_view_get_n_columns")]
    #[doc(alias = "get_n_columns")]
    pub fn n_columns(&self) -> u32 {
        unsafe { ffi::awra_data_view_get_n_columns(self.to_glib_none().0) }
    }

    #[doc(alias = "awra_data_view_get_state")]
    #[doc(alias = "get_state")]
    pub fn state(&self) -> DataViewState {
        unsafe { from_glib(ffi::awra_data_view_get_state(self.to_glib_none().0)) }
    }

    #[doc(alias = "awra_data_view_insert_column")]
    pub fn insert_column(&self, column: &DataColumn, position: u32) {
        unsafe {
            ffi::awra_data_view_insert_column(
                self.to_glib_none().0,
                column.to_glib_none().0,
                position,
            );
        }
    }

    #[doc(alias = "awra_data_view_remove_column")]
    pub fn remove_column(&self, column: &DataColumn) {
        unsafe {
            ffi::awra_data_view_remove_column(self.to_glib_none().0, column.to_glib_none().0);
        }
    }

    #[doc(alias = "awra_data_view_set_empty_widget")]
    #[doc(alias = "empty-widget")]
    pub fn set_empty_widget(&self, widget: Option<&impl IsA<gtk::Widget>>) {
        unsafe {
            ffi::awra_data_view_set_empty_widget(
                self.to_glib_none().0,
                widget.map(|p| p.as_ref()).to_glib_none().0,
            );
        }
    }

    #[doc(alias = "awra_data_view_set_error_widget")]
    #[doc(alias = "error-widget")]
    pub fn set_error_widget(&self, widget: Option<&impl IsA<gtk::Widget>>) {
        unsafe {
            ffi::awra_data_view_set_error_widget(
                self.to_glib_none().0,
                widget.map(|p| p.as_ref()).to_glib_none().0,
            );
        }
    }

    #[doc(alias = "awra_data_view_set_loading_more")]
    #[doc(alias = "loading-more")]
    pub fn set_loading_more(&self, loading_more: bool) {
        unsafe {
            ffi::awra_data_view_set_loading_more(self.to_glib_none().0, loading_more.into_glib());
        }
    }

    #[doc(alias = "awra_data_view_set_loading_widget")]
    #[doc(alias = "loading-widget")]
    pub fn set_loading_widget(&self, widget: Option<&impl IsA<gtk::Widget>>) {
        unsafe {
            ffi::awra_data_view_set_loading_widget(
                self.to_glib_none().0,
                widget.map(|p| p.as_ref()).to_glib_none().0,
            );
        }
    }

    #[doc(alias = "awra_data_view_set_model")]
    #[doc(alias = "model")]
    pub fn set_model(&self, model: Option<&impl IsA<gtk::SelectionModel>>) {
        unsafe {
            ffi::awra_data_view_set_model(
                self.to_glib_none().0,
                model.map(|p| p.as_ref()).to_glib_none().0,
            );
        }
    }

    #[doc(alias = "awra_data_view_set_state")]
    #[doc(alias = "state")]
    pub fn set_state(&self, state: DataViewState) {
        unsafe {
            ffi::awra_data_view_set_state(self.to_glib_none().0, state.into_glib());
        }
    }

    #[doc(alias = "empty-widget")]
    pub fn connect_empty_widget_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_empty_widget_trampoline<F: Fn(&DataView) + 'static>(
            this: *mut ffi::AwraDataView,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::empty-widget".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_empty_widget_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "error-widget")]
    pub fn connect_error_widget_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_error_widget_trampoline<F: Fn(&DataView) + 'static>(
            this: *mut ffi::AwraDataView,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::error-widget".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_error_widget_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "loading-more")]
    pub fn connect_loading_more_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_loading_more_trampoline<F: Fn(&DataView) + 'static>(
            this: *mut ffi::AwraDataView,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::loading-more".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_loading_more_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "loading-widget")]
    pub fn connect_loading_widget_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_loading_widget_trampoline<F: Fn(&DataView) + 'static>(
            this: *mut ffi::AwraDataView,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::loading-widget".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_loading_widget_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "model")]
    pub fn connect_model_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_model_trampoline<F: Fn(&DataView) + 'static>(
            this: *mut ffi::AwraDataView,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::model".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_model_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "state")]
    pub fn connect_state_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_state_trampoline<F: Fn(&DataView) + 'static>(
            this: *mut ffi::AwraDataView,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::state".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_state_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }
}

impl Default for DataView {
    fn default() -> Self {
        glib::object::Object::new::<Self>()
    }
}

// rustdoc-stripper-ignore-next
/// A [builder-pattern] type to construct [`DataView`] objects.
///
/// [builder-pattern]: https://doc.rust-lang.org/1.0.0/style/ownership/builders.html
#[must_use = "The builder must be built to be used"]
pub struct DataViewBuilder {
    builder: glib::object::ObjectBuilder<'static, DataView>,
}

impl DataViewBuilder {
    fn new() -> Self {
        Self {
            builder: glib::object::Object::builder(),
        }
    }

    pub fn empty_widget(self, empty_widget: &impl IsA<gtk::Widget>) -> Self {
        Self {
            builder: self
                .builder
                .property("empty-widget", empty_widget.clone().upcast()),
        }
    }

    pub fn error_widget(self, error_widget: &impl IsA<gtk::Widget>) -> Self {
        Self {
            builder: self
                .builder
                .property("error-widget", error_widget.clone().upcast()),
        }
    }

    pub fn loading_more(self, loading_more: bool) -> Self {
        Self {
            builder: self.builder.property("loading-more", loading_more),
        }
    }

    pub fn loading_widget(self, loading_widget: &impl IsA<gtk::Widget>) -> Self {
        Self {
            builder: self
                .builder
                .property("loading-widget", loading_widget.clone().upcast()),
        }
    }

    pub fn model(self, model: &impl IsA<gtk::SelectionModel>) -> Self {
        Self {
            builder: self.builder.property("model", model.clone().upcast()),
        }
    }

    pub fn state(self, state: DataViewState) -> Self {
        Self {
            builder: self.builder.property("state", state),
        }
    }

    pub fn can_focus(self, can_focus: bool) -> Self {
        Self {
            builder: self.builder.property("can-focus", can_focus),
        }
    }

    pub fn can_target(self, can_target: bool) -> Self {
        Self {
            builder: self.builder.property("can-target", can_target),
        }
    }

    pub fn css_classes(self, css_classes: impl Into<glib::StrV>) -> Self {
        Self {
            builder: self.builder.property("css-classes", css_classes.into()),
        }
    }

    pub fn css_name(self, css_name: impl Into<glib::GString>) -> Self {
        Self {
            builder: self.builder.property("css-name", css_name.into()),
        }
    }

    //pub fn cursor(self, cursor: /*Ignored*/&gdk::Cursor) -> Self {
    //    Self { builder: self.builder.property("cursor", cursor), }
    //}

    pub fn focus_on_click(self, focus_on_click: bool) -> Self {
        Self {
            builder: self.builder.property("focus-on-click", focus_on_click),
        }
    }

    pub fn focusable(self, focusable: bool) -> Self {
        Self {
            builder: self.builder.property("focusable", focusable),
        }
    }

    pub fn halign(self, halign: gtk::Align) -> Self {
        Self {
            builder: self.builder.property("halign", halign),
        }
    }

    pub fn has_tooltip(self, has_tooltip: bool) -> Self {
        Self {
            builder: self.builder.property("has-tooltip", has_tooltip),
        }
    }

    pub fn height_request(self, height_request: i32) -> Self {
        Self {
            builder: self.builder.property("height-request", height_request),
        }
    }

    pub fn hexpand(self, hexpand: bool) -> Self {
        Self {
            builder: self.builder.property("hexpand", hexpand),
        }
    }

    pub fn hexpand_set(self, hexpand_set: bool) -> Self {
        Self {
            builder: self.builder.property("hexpand-set", hexpand_set),
        }
    }

    //pub fn layout_manager(self, layout_manager: &impl IsA</*Ignored*/gtk::LayoutManager>) -> Self {
    //    Self { builder: self.builder.property("layout-manager", layout_manager.clone().upcast()), }
    //}

    #[cfg(feature = "gtk_v4_18")]
    #[cfg_attr(docsrs, doc(cfg(feature = "gtk_v4_18")))]
    pub fn limit_events(self, limit_events: bool) -> Self {
        Self {
            builder: self.builder.property("limit-events", limit_events),
        }
    }

    pub fn margin_bottom(self, margin_bottom: i32) -> Self {
        Self {
            builder: self.builder.property("margin-bottom", margin_bottom),
        }
    }

    pub fn margin_end(self, margin_end: i32) -> Self {
        Self {
            builder: self.builder.property("margin-end", margin_end),
        }
    }

    pub fn margin_start(self, margin_start: i32) -> Self {
        Self {
            builder: self.builder.property("margin-start", margin_start),
        }
    }

    pub fn margin_top(self, margin_top: i32) -> Self {
        Self {
            builder: self.builder.property("margin-top", margin_top),
        }
    }

    pub fn name(self, name: impl Into<glib::GString>) -> Self {
        Self {
            builder: self.builder.property("name", name.into()),
        }
    }

    pub fn opacity(self, opacity: f64) -> Self {
        Self {
            builder: self.builder.property("opacity", opacity),
        }
    }

    //pub fn overflow(self, overflow: /*Ignored*/gtk::Overflow) -> Self {
    //    Self { builder: self.builder.property("overflow", overflow), }
    //}

    pub fn receives_default(self, receives_default: bool) -> Self {
        Self {
            builder: self.builder.property("receives-default", receives_default),
        }
    }

    pub fn sensitive(self, sensitive: bool) -> Self {
        Self {
            builder: self.builder.property("sensitive", sensitive),
        }
    }

    pub fn tooltip_markup(self, tooltip_markup: impl Into<glib::GString>) -> Self {
        Self {
            builder: self
                .builder
                .property("tooltip-markup", tooltip_markup.into()),
        }
    }

    pub fn tooltip_text(self, tooltip_text: impl Into<glib::GString>) -> Self {
        Self {
            builder: self.builder.property("tooltip-text", tooltip_text.into()),
        }
    }

    pub fn valign(self, valign: gtk::Align) -> Self {
        Self {
            builder: self.builder.property("valign", valign),
        }
    }

    pub fn vexpand(self, vexpand: bool) -> Self {
        Self {
            builder: self.builder.property("vexpand", vexpand),
        }
    }

    pub fn vexpand_set(self, vexpand_set: bool) -> Self {
        Self {
            builder: self.builder.property("vexpand-set", vexpand_set),
        }
    }

    pub fn visible(self, visible: bool) -> Self {
        Self {
            builder: self.builder.property("visible", visible),
        }
    }

    pub fn width_request(self, width_request: i32) -> Self {
        Self {
            builder: self.builder.property("width-request", width_request),
        }
    }

    //pub fn accessible_role(self, accessible_role: /*Ignored*/gtk::AccessibleRole) -> Self {
    //    Self { builder: self.builder.property("accessible-role", accessible_role), }
    //}

    // rustdoc-stripper-ignore-next
    /// Build the [`DataView`].
    #[must_use = "Building the object from the builder is usually expensive and is not expected to have side effects"]
    pub fn build(self) -> DataView {
        assert_initialized_main_thread!();
        self.builder.build()
    }
}
