// This file was generated by gir (https://github.com/gtk-rs/gir)
// from build
// from subprojects/gir-files
// DO NOT EDIT

use crate::{ffi, Section};
use glib::{
    prelude::*,
    signal::{connect_raw, SignalHandlerId},
    translate::*,
};
use std::boxed::Box as Box_;

#[cfg(feature = "gtk_v4_10")]
#[cfg_attr(docsrs, doc(cfg(feature = "gtk_v4_10")))]
glib::wrapper! {
    #[doc(alias = "AwraDetailPane")]
    pub struct DetailPane(Object<ffi::AwraDetailPane, ffi::AwraDetailPaneClass>) @extends gtk::Widget, gobject::InitiallyUnowned, @implements gtk::Accessible, gtk::Buildable, gtk::ConstraintTarget;

    match fn {
        type_ => || ffi::awra_detail_pane_get_type(),
    }
}

#[cfg(not(feature = "gtk_v4_10"))]
glib::wrapper! {
    #[doc(alias = "AwraDetailPane")]
    pub struct DetailPane(Object<ffi::AwraDetailPane, ffi::AwraDetailPaneClass>) @extends gtk::Widget, gobject::InitiallyUnowned, @implements gtk::Buildable, gtk::ConstraintTarget;

    match fn {
        type_ => || ffi::awra_detail_pane_get_type(),
    }
}

impl DetailPane {
    #[doc(alias = "awra_detail_pane_new")]
    pub fn new() -> DetailPane {
        assert_initialized_main_thread!();
        unsafe { gtk::Widget::from_glib_none(ffi::awra_detail_pane_new()).unsafe_cast() }
    }

    // rustdoc-stripper-ignore-next
    /// Creates a new builder-pattern struct instance to construct [`DetailPane`] objects.
    ///
    /// This method returns an instance of [`DetailPaneBuilder`](crate::builders::DetailPaneBuilder) which can be used to create [`DetailPane`] objects.
    pub fn builder() -> DetailPaneBuilder {
        DetailPaneBuilder::new()
    }

    #[doc(alias = "awra_detail_pane_append_section")]
    pub fn append_section(&self, section: &Section) {
        unsafe {
            ffi::awra_detail_pane_append_section(self.to_glib_none().0, section.to_glib_none().0);
        }
    }

    #[doc(alias = "awra_detail_pane_get_actions")]
    #[doc(alias = "get_actions")]
    pub fn actions(&self) -> Option<gtk::Widget> {
        unsafe { from_glib_none(ffi::awra_detail_pane_get_actions(self.to_glib_none().0)) }
    }

    #[doc(alias = "awra_detail_pane_get_media")]
    #[doc(alias = "get_media")]
    pub fn media(&self) -> Option<gtk::Widget> {
        unsafe { from_glib_none(ffi::awra_detail_pane_get_media(self.to_glib_none().0)) }
    }

    #[doc(alias = "awra_detail_pane_get_metadata")]
    #[doc(alias = "get_metadata")]
    pub fn metadata(&self) -> Option<gtk::Widget> {
        unsafe { from_glib_none(ffi::awra_detail_pane_get_metadata(self.to_glib_none().0)) }
    }

    #[doc(alias = "awra_detail_pane_get_n_sections")]
    #[doc(alias = "get_n_sections")]
    pub fn n_sections(&self) -> u32 {
        unsafe { ffi::awra_detail_pane_get_n_sections(self.to_glib_none().0) }
    }

    #[doc(alias = "awra_detail_pane_get_section")]
    #[doc(alias = "get_section")]
    pub fn section(&self, position: u32) -> Option<Section> {
        unsafe {
            from_glib_none(ffi::awra_detail_pane_get_section(
                self.to_glib_none().0,
                position,
            ))
        }
    }

    #[doc(alias = "awra_detail_pane_get_subtitle")]
    #[doc(alias = "get_subtitle")]
    pub fn subtitle(&self) -> Option<glib::GString> {
        unsafe { from_glib_none(ffi::awra_detail_pane_get_subtitle(self.to_glib_none().0)) }
    }

    #[doc(alias = "awra_detail_pane_get_title")]
    #[doc(alias = "get_title")]
    pub fn title(&self) -> Option<glib::GString> {
        unsafe { from_glib_none(ffi::awra_detail_pane_get_title(self.to_glib_none().0)) }
    }

    #[doc(alias = "awra_detail_pane_remove_section")]
    pub fn remove_section(&self, section: &Section) {
        unsafe {
            ffi::awra_detail_pane_remove_section(self.to_glib_none().0, section.to_glib_none().0);
        }
    }

    #[doc(alias = "awra_detail_pane_set_actions")]
    #[doc(alias = "actions")]
    pub fn set_actions(&self, actions: Option<&impl IsA<gtk::Widget>>) {
        unsafe {
            ffi::awra_detail_pane_set_actions(
                self.to_glib_none().0,
                actions.map(|p| p.as_ref()).to_glib_none().0,
            );
        }
    }

    #[doc(alias = "awra_detail_pane_set_media")]
    #[doc(alias = "media")]
    pub fn set_media(&self, media: Option<&impl IsA<gtk::Widget>>) {
        unsafe {
            ffi::awra_detail_pane_set_media(
                self.to_glib_none().0,
                media.map(|p| p.as_ref()).to_glib_none().0,
            );
        }
    }

    #[doc(alias = "awra_detail_pane_set_metadata")]
    #[doc(alias = "metadata")]
    pub fn set_metadata(&self, metadata: Option<&impl IsA<gtk::Widget>>) {
        unsafe {
            ffi::awra_detail_pane_set_metadata(
                self.to_glib_none().0,
                metadata.map(|p| p.as_ref()).to_glib_none().0,
            );
        }
    }

    #[doc(alias = "awra_detail_pane_set_subtitle")]
    #[doc(alias = "subtitle")]
    pub fn set_subtitle(&self, subtitle: Option<&str>) {
        unsafe {
            ffi::awra_detail_pane_set_subtitle(self.to_glib_none().0, subtitle.to_glib_none().0);
        }
    }

    #[doc(alias = "awra_detail_pane_set_title")]
    #[doc(alias = "title")]
    pub fn set_title(&self, title: Option<&str>) {
        unsafe {
            ffi::awra_detail_pane_set_title(self.to_glib_none().0, title.to_glib_none().0);
        }
    }

    #[doc(alias = "actions")]
    pub fn connect_actions_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_actions_trampoline<F: Fn(&DetailPane) + 'static>(
            this: *mut ffi::AwraDetailPane,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::actions".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_actions_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "media")]
    pub fn connect_media_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_media_trampoline<F: Fn(&DetailPane) + 'static>(
            this: *mut ffi::AwraDetailPane,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::media".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_media_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "metadata")]
    pub fn connect_metadata_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_metadata_trampoline<F: Fn(&DetailPane) + 'static>(
            this: *mut ffi::AwraDetailPane,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::metadata".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_metadata_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "subtitle")]
    pub fn connect_subtitle_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_subtitle_trampoline<F: Fn(&DetailPane) + 'static>(
            this: *mut ffi::AwraDetailPane,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::subtitle".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_subtitle_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "title")]
    pub fn connect_title_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_title_trampoline<F: Fn(&DetailPane) + 'static>(
            this: *mut ffi::AwraDetailPane,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::title".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_title_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }
}

impl Default for DetailPane {
    fn default() -> Self {
        Self::new()
    }
}

// rustdoc-stripper-ignore-next
/// A [builder-pattern] type to construct [`DetailPane`] objects.
///
/// [builder-pattern]: https://doc.rust-lang.org/1.0.0/style/ownership/builders.html
#[must_use = "The builder must be built to be used"]
pub struct DetailPaneBuilder {
    builder: glib::object::ObjectBuilder<'static, DetailPane>,
}

impl DetailPaneBuilder {
    fn new() -> Self {
        Self {
            builder: glib::object::Object::builder(),
        }
    }

    pub fn actions(self, actions: &impl IsA<gtk::Widget>) -> Self {
        Self {
            builder: self.builder.property("actions", actions.clone().upcast()),
        }
    }

    pub fn media(self, media: &impl IsA<gtk::Widget>) -> Self {
        Self {
            builder: self.builder.property("media", media.clone().upcast()),
        }
    }

    pub fn metadata(self, metadata: &impl IsA<gtk::Widget>) -> Self {
        Self {
            builder: self.builder.property("metadata", metadata.clone().upcast()),
        }
    }

    pub fn subtitle(self, subtitle: impl Into<glib::GString>) -> Self {
        Self {
            builder: self.builder.property("subtitle", subtitle.into()),
        }
    }

    pub fn title(self, title: impl Into<glib::GString>) -> Self {
        Self {
            builder: self.builder.property("title", title.into()),
        }
    }

    pub fn can_focus(self, can_focus: bool) -> Self {
        Self {
            builder: self.builder.property("can-focus", can_focus),
        }
    }

    pub fn can_target(self, can_target: bool) -> Self {
        Self {
            builder: self.builder.property("can-target", can_target),
        }
    }

    pub fn css_classes(self, css_classes: impl Into<glib::StrV>) -> Self {
        Self {
            builder: self.builder.property("css-classes", css_classes.into()),
        }
    }

    pub fn css_name(self, css_name: impl Into<glib::GString>) -> Self {
        Self {
            builder: self.builder.property("css-name", css_name.into()),
        }
    }

    //pub fn cursor(self, cursor: /*Ignored*/&gdk::Cursor) -> Self {
    //    Self { builder: self.builder.property("cursor", cursor), }
    //}

    pub fn focus_on_click(self, focus_on_click: bool) -> Self {
        Self {
            builder: self.builder.property("focus-on-click", focus_on_click),
        }
    }

    pub fn focusable(self, focusable: bool) -> Self {
        Self {
            builder: self.builder.property("focusable", focusable),
        }
    }

    pub fn halign(self, halign: gtk::Align) -> Self {
        Self {
            builder: self.builder.property("halign", halign),
        }
    }

    pub fn has_tooltip(self, has_tooltip: bool) -> Self {
        Self {
            builder: self.builder.property("has-tooltip", has_tooltip),
        }
    }

    pub fn height_request(self, height_request: i32) -> Self {
        Self {
            builder: self.builder.property("height-request", height_request),
        }
    }

    pub fn hexpand(self, hexpand: bool) -> Self {
        Self {
            builder: self.builder.property("hexpand", hexpand),
        }
    }

    pub fn hexpand_set(self, hexpand_set: bool) -> Self {
        Self {
            builder: self.builder.property("hexpand-set", hexpand_set),
        }
    }

    //pub fn layout_manager(self, layout_manager: &impl IsA</*Ignored*/gtk::LayoutManager>) -> Self {
    //    Self { builder: self.builder.property("layout-manager", layout_manager.clone().upcast()), }
    //}

    #[cfg(feature = "gtk_v4_18")]
    #[cfg_attr(docsrs, doc(cfg(feature = "gtk_v4_18")))]
    pub fn limit_events(self, limit_events: bool) -> Self {
        Self {
            builder: self.builder.property("limit-events", limit_events),
        }
    }

    pub fn margin_bottom(self, margin_bottom: i32) -> Self {
        Self {
            builder: self.builder.property("margin-bottom", margin_bottom),
        }
    }

    pub fn margin_end(self, margin_end: i32) -> Self {
        Self {
            builder: self.builder.property("margin-end", margin_end),
        }
    }

    pub fn margin_start(self, margin_start: i32) -> Self {
        Self {
            builder: self.builder.property("margin-start", margin_start),
        }
    }

    pub fn margin_top(self, margin_top: i32) -> Self {
        Self {
            builder: self.builder.property("margin-top", margin_top),
        }
    }

    pub fn name(self, name: impl Into<glib::GString>) -> Self {
        Self {
            builder: self.builder.property("name", name.into()),
        }
    }

    pub fn opacity(self, opacity: f64) -> Self {
        Self {
            builder: self.builder.property("opacity", opacity),
        }
    }

    //pub fn overflow(self, overflow: /*Ignored*/gtk::Overflow) -> Self {
    //    Self { builder: self.builder.property("overflow", overflow), }
    //}

    pub fn receives_default(self, receives_default: bool) -> Self {
        Self {
            builder: self.builder.property("receives-default", receives_default),
        }
    }

    pub fn sensitive(self, sensitive: bool) -> Self {
        Self {
            builder: self.builder.property("sensitive", sensitive),
        }
    }

    pub fn tooltip_markup(self, tooltip_markup: impl Into<glib::GString>) -> Self {
        Self {
            builder: self
                .builder
                .property("tooltip-markup", tooltip_markup.into()),
        }
    }

    pub fn tooltip_text(self, tooltip_text: impl Into<glib::GString>) -> Self {
        Self {
            builder: self.builder.property("tooltip-text", tooltip_text.into()),
        }
    }

    pub fn valign(self, valign: gtk::Align) -> Self {
        Self {
            builder: self.builder.property("valign", valign),
        }
    }

    pub fn vexpand(self, vexpand: bool) -> Self {
        Self {
            builder: self.builder.property("vexpand", vexpand),
        }
    }

    pub fn vexpand_set(self, vexpand_set: bool) -> Self {
        Self {
            builder: self.builder.property("vexpand-set", vexpand_set),
        }
    }

    pub fn visible(self, visible: bool) -> Self {
        Self {
            builder: self.builder.property("visible", visible),
        }
    }

    pub fn width_request(self, width_request: i32) -> Self {
        Self {
            builder: self.builder.property("width-request", width_request),
        }
    }

    //pub fn accessible_role(self, accessible_role: /*Ignored*/gtk::AccessibleRole) -> Self {
    //    Self { builder: self.builder.property("accessible-role", accessible_role), }
    //}

    // rustdoc-stripper-ignore-next
    /// Build the [`DetailPane`].
    #[must_use = "Building the object from the builder is usually expensive and is not expected to have side effects"]
    pub fn build(self) -> DetailPane {
        assert_initialized_main_thread!();
        self.builder.build()
    }
}
