// This file was generated by gir (https://github.com/gtk-rs/gir)
// from build
// from subprojects/gir-files
// DO NOT EDIT

use crate::{ffi, PanelEdge, Surface};
use glib::{
    prelude::*,
    signal::{connect_raw, SignalHandlerId},
    translate::*,
};
use std::boxed::Box as Box_;

#[cfg(feature = "gtk_v4_10")]
#[cfg_attr(docsrs, doc(cfg(feature = "gtk_v4_10")))]
glib::wrapper! {
    #[doc(alias = "AwraEdgePanel")]
    pub struct EdgePanel(Object<ffi::AwraEdgePanel, ffi::AwraEdgePanelClass>) @extends gtk::Widget, gobject::InitiallyUnowned, @implements gtk::Accessible, gtk::Buildable, gtk::ConstraintTarget;

    match fn {
        type_ => || ffi::awra_edge_panel_get_type(),
    }
}

#[cfg(not(feature = "gtk_v4_10"))]
glib::wrapper! {
    #[doc(alias = "AwraEdgePanel")]
    pub struct EdgePanel(Object<ffi::AwraEdgePanel, ffi::AwraEdgePanelClass>) @extends gtk::Widget, gobject::InitiallyUnowned, @implements gtk::Buildable, gtk::ConstraintTarget;

    match fn {
        type_ => || ffi::awra_edge_panel_get_type(),
    }
}

impl EdgePanel {
    #[doc(alias = "awra_edge_panel_new")]
    pub fn new() -> EdgePanel {
        assert_initialized_main_thread!();
        unsafe { gtk::Widget::from_glib_none(ffi::awra_edge_panel_new()).unsafe_cast() }
    }

    // rustdoc-stripper-ignore-next
    /// Creates a new builder-pattern struct instance to construct [`EdgePanel`] objects.
    ///
    /// This method returns an instance of [`EdgePanelBuilder`](crate::builders::EdgePanelBuilder) which can be used to create [`EdgePanel`] objects.
    pub fn builder() -> EdgePanelBuilder {
        EdgePanelBuilder::new()
    }

    #[doc(alias = "awra_edge_panel_get_auto_hide")]
    #[doc(alias = "get_auto_hide")]
    #[doc(alias = "auto-hide")]
    pub fn is_auto_hide(&self) -> bool {
        unsafe { from_glib(ffi::awra_edge_panel_get_auto_hide(self.to_glib_none().0)) }
    }

    #[doc(alias = "awra_edge_panel_get_content")]
    #[doc(alias = "get_content")]
    pub fn content(&self) -> Option<gtk::Widget> {
        unsafe { from_glib_none(ffi::awra_edge_panel_get_content(self.to_glib_none().0)) }
    }

    #[doc(alias = "awra_edge_panel_get_edge")]
    #[doc(alias = "get_edge")]
    pub fn edge(&self) -> PanelEdge {
        unsafe { from_glib(ffi::awra_edge_panel_get_edge(self.to_glib_none().0)) }
    }

    #[doc(alias = "awra_edge_panel_get_hide_delay")]
    #[doc(alias = "get_hide_delay")]
    #[doc(alias = "hide-delay")]
    pub fn hide_delay(&self) -> u32 {
        unsafe { ffi::awra_edge_panel_get_hide_delay(self.to_glib_none().0) }
    }

    #[doc(alias = "awra_edge_panel_get_panel")]
    #[doc(alias = "get_panel")]
    pub fn panel(&self) -> Option<gtk::Widget> {
        unsafe { from_glib_none(ffi::awra_edge_panel_get_panel(self.to_glib_none().0)) }
    }

    #[doc(alias = "awra_edge_panel_get_panel_width")]
    #[doc(alias = "get_panel_width")]
    #[doc(alias = "panel-width")]
    pub fn panel_width(&self) -> u32 {
        unsafe { ffi::awra_edge_panel_get_panel_width(self.to_glib_none().0) }
    }

    #[doc(alias = "awra_edge_panel_get_reveal_width")]
    #[doc(alias = "get_reveal_width")]
    #[doc(alias = "reveal-width")]
    pub fn reveal_width(&self) -> u32 {
        unsafe { ffi::awra_edge_panel_get_reveal_width(self.to_glib_none().0) }
    }

    #[doc(alias = "awra_edge_panel_get_revealed")]
    #[doc(alias = "get_revealed")]
    #[doc(alias = "revealed")]
    pub fn is_revealed(&self) -> bool {
        unsafe { from_glib(ffi::awra_edge_panel_get_revealed(self.to_glib_none().0)) }
    }

    #[doc(alias = "awra_edge_panel_get_surface")]
    #[doc(alias = "get_surface")]
    pub fn surface(&self) -> Surface {
        unsafe { from_glib_none(ffi::awra_edge_panel_get_surface(self.to_glib_none().0)) }
    }

    #[doc(alias = "awra_edge_panel_set_auto_hide")]
    #[doc(alias = "auto-hide")]
    pub fn set_auto_hide(&self, auto_hide: bool) {
        unsafe {
            ffi::awra_edge_panel_set_auto_hide(self.to_glib_none().0, auto_hide.into_glib());
        }
    }

    #[doc(alias = "awra_edge_panel_set_content")]
    #[doc(alias = "content")]
    pub fn set_content(&self, content: Option<&impl IsA<gtk::Widget>>) {
        unsafe {
            ffi::awra_edge_panel_set_content(
                self.to_glib_none().0,
                content.map(|p| p.as_ref()).to_glib_none().0,
            );
        }
    }

    #[doc(alias = "awra_edge_panel_set_edge")]
    #[doc(alias = "edge")]
    pub fn set_edge(&self, edge: PanelEdge) {
        unsafe {
            ffi::awra_edge_panel_set_edge(self.to_glib_none().0, edge.into_glib());
        }
    }

    #[doc(alias = "awra_edge_panel_set_hide_delay")]
    #[doc(alias = "hide-delay")]
    pub fn set_hide_delay(&self, delay_ms: u32) {
        unsafe {
            ffi::awra_edge_panel_set_hide_delay(self.to_glib_none().0, delay_ms);
        }
    }

    #[doc(alias = "awra_edge_panel_set_panel")]
    #[doc(alias = "panel")]
    pub fn set_panel(&self, panel: Option<&impl IsA<gtk::Widget>>) {
        unsafe {
            ffi::awra_edge_panel_set_panel(
                self.to_glib_none().0,
                panel.map(|p| p.as_ref()).to_glib_none().0,
            );
        }
    }

    #[doc(alias = "awra_edge_panel_set_panel_width")]
    #[doc(alias = "panel-width")]
    pub fn set_panel_width(&self, width: u32) {
        unsafe {
            ffi::awra_edge_panel_set_panel_width(self.to_glib_none().0, width);
        }
    }

    #[doc(alias = "awra_edge_panel_set_reveal_width")]
    #[doc(alias = "reveal-width")]
    pub fn set_reveal_width(&self, width: u32) {
        unsafe {
            ffi::awra_edge_panel_set_reveal_width(self.to_glib_none().0, width);
        }
    }

    #[doc(alias = "awra_edge_panel_set_revealed")]
    #[doc(alias = "revealed")]
    pub fn set_revealed(&self, revealed: bool) {
        unsafe {
            ffi::awra_edge_panel_set_revealed(self.to_glib_none().0, revealed.into_glib());
        }
    }

    #[doc(alias = "auto-hide")]
    pub fn connect_auto_hide_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_auto_hide_trampoline<F: Fn(&EdgePanel) + 'static>(
            this: *mut ffi::AwraEdgePanel,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::auto-hide".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_auto_hide_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "content")]
    pub fn connect_content_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_content_trampoline<F: Fn(&EdgePanel) + 'static>(
            this: *mut ffi::AwraEdgePanel,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::content".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_content_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "edge")]
    pub fn connect_edge_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_edge_trampoline<F: Fn(&EdgePanel) + 'static>(
            this: *mut ffi::AwraEdgePanel,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::edge".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_edge_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "hide-delay")]
    pub fn connect_hide_delay_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_hide_delay_trampoline<F: Fn(&EdgePanel) + 'static>(
            this: *mut ffi::AwraEdgePanel,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::hide-delay".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_hide_delay_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "panel")]
    pub fn connect_panel_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_panel_trampoline<F: Fn(&EdgePanel) + 'static>(
            this: *mut ffi::AwraEdgePanel,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::panel".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_panel_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "panel-width")]
    pub fn connect_panel_width_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_panel_width_trampoline<F: Fn(&EdgePanel) + 'static>(
            this: *mut ffi::AwraEdgePanel,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::panel-width".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_panel_width_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "reveal-width")]
    pub fn connect_reveal_width_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_reveal_width_trampoline<F: Fn(&EdgePanel) + 'static>(
            this: *mut ffi::AwraEdgePanel,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::reveal-width".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_reveal_width_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "revealed")]
    pub fn connect_revealed_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_revealed_trampoline<F: Fn(&EdgePanel) + 'static>(
            this: *mut ffi::AwraEdgePanel,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::revealed".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_revealed_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "surface")]
    pub fn connect_surface_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_surface_trampoline<F: Fn(&EdgePanel) + 'static>(
            this: *mut ffi::AwraEdgePanel,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::surface".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_surface_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }
}

impl Default for EdgePanel {
    fn default() -> Self {
        Self::new()
    }
}

// rustdoc-stripper-ignore-next
/// A [builder-pattern] type to construct [`EdgePanel`] objects.
///
/// [builder-pattern]: https://doc.rust-lang.org/1.0.0/style/ownership/builders.html
#[must_use = "The builder must be built to be used"]
pub struct EdgePanelBuilder {
    builder: glib::object::ObjectBuilder<'static, EdgePanel>,
}

impl EdgePanelBuilder {
    fn new() -> Self {
        Self {
            builder: glib::object::Object::builder(),
        }
    }

    pub fn auto_hide(self, auto_hide: bool) -> Self {
        Self {
            builder: self.builder.property("auto-hide", auto_hide),
        }
    }

    pub fn content(self, content: &impl IsA<gtk::Widget>) -> Self {
        Self {
            builder: self.builder.property("content", content.clone().upcast()),
        }
    }

    pub fn edge(self, edge: PanelEdge) -> Self {
        Self {
            builder: self.builder.property("edge", edge),
        }
    }

    pub fn hide_delay(self, hide_delay: u32) -> Self {
        Self {
            builder: self.builder.property("hide-delay", hide_delay),
        }
    }

    pub fn panel(self, panel: &impl IsA<gtk::Widget>) -> Self {
        Self {
            builder: self.builder.property("panel", panel.clone().upcast()),
        }
    }

    pub fn panel_width(self, panel_width: u32) -> Self {
        Self {
            builder: self.builder.property("panel-width", panel_width),
        }
    }

    pub fn reveal_width(self, reveal_width: u32) -> Self {
        Self {
            builder: self.builder.property("reveal-width", reveal_width),
        }
    }

    pub fn revealed(self, revealed: bool) -> Self {
        Self {
            builder: self.builder.property("revealed", revealed),
        }
    }

    pub fn can_focus(self, can_focus: bool) -> Self {
        Self {
            builder: self.builder.property("can-focus", can_focus),
        }
    }

    pub fn can_target(self, can_target: bool) -> Self {
        Self {
            builder: self.builder.property("can-target", can_target),
        }
    }

    pub fn css_classes(self, css_classes: impl Into<glib::StrV>) -> Self {
        Self {
            builder: self.builder.property("css-classes", css_classes.into()),
        }
    }

    pub fn css_name(self, css_name: impl Into<glib::GString>) -> Self {
        Self {
            builder: self.builder.property("css-name", css_name.into()),
        }
    }

    //pub fn cursor(self, cursor: /*Ignored*/&gdk::Cursor) -> Self {
    //    Self { builder: self.builder.property("cursor", cursor), }
    //}

    pub fn focus_on_click(self, focus_on_click: bool) -> Self {
        Self {
            builder: self.builder.property("focus-on-click", focus_on_click),
        }
    }

    pub fn focusable(self, focusable: bool) -> Self {
        Self {
            builder: self.builder.property("focusable", focusable),
        }
    }

    pub fn halign(self, halign: gtk::Align) -> Self {
        Self {
            builder: self.builder.property("halign", halign),
        }
    }

    pub fn has_tooltip(self, has_tooltip: bool) -> Self {
        Self {
            builder: self.builder.property("has-tooltip", has_tooltip),
        }
    }

    pub fn height_request(self, height_request: i32) -> Self {
        Self {
            builder: self.builder.property("height-request", height_request),
        }
    }

    pub fn hexpand(self, hexpand: bool) -> Self {
        Self {
            builder: self.builder.property("hexpand", hexpand),
        }
    }

    pub fn hexpand_set(self, hexpand_set: bool) -> Self {
        Self {
            builder: self.builder.property("hexpand-set", hexpand_set),
        }
    }

    //pub fn layout_manager(self, layout_manager: &impl IsA</*Ignored*/gtk::LayoutManager>) -> Self {
    //    Self { builder: self.builder.property("layout-manager", layout_manager.clone().upcast()), }
    //}

    #[cfg(feature = "gtk_v4_18")]
    #[cfg_attr(docsrs, doc(cfg(feature = "gtk_v4_18")))]
    pub fn limit_events(self, limit_events: bool) -> Self {
        Self {
            builder: self.builder.property("limit-events", limit_events),
        }
    }

    pub fn margin_bottom(self, margin_bottom: i32) -> Self {
        Self {
            builder: self.builder.property("margin-bottom", margin_bottom),
        }
    }

    pub fn margin_end(self, margin_end: i32) -> Self {
        Self {
            builder: self.builder.property("margin-end", margin_end),
        }
    }

    pub fn margin_start(self, margin_start: i32) -> Self {
        Self {
            builder: self.builder.property("margin-start", margin_start),
        }
    }

    pub fn margin_top(self, margin_top: i32) -> Self {
        Self {
            builder: self.builder.property("margin-top", margin_top),
        }
    }

    pub fn name(self, name: impl Into<glib::GString>) -> Self {
        Self {
            builder: self.builder.property("name", name.into()),
        }
    }

    pub fn opacity(self, opacity: f64) -> Self {
        Self {
            builder: self.builder.property("opacity", opacity),
        }
    }

    //pub fn overflow(self, overflow: /*Ignored*/gtk::Overflow) -> Self {
    //    Self { builder: self.builder.property("overflow", overflow), }
    //}

    pub fn receives_default(self, receives_default: bool) -> Self {
        Self {
            builder: self.builder.property("receives-default", receives_default),
        }
    }

    pub fn sensitive(self, sensitive: bool) -> Self {
        Self {
            builder: self.builder.property("sensitive", sensitive),
        }
    }

    pub fn tooltip_markup(self, tooltip_markup: impl Into<glib::GString>) -> Self {
        Self {
            builder: self
                .builder
                .property("tooltip-markup", tooltip_markup.into()),
        }
    }

    pub fn tooltip_text(self, tooltip_text: impl Into<glib::GString>) -> Self {
        Self {
            builder: self.builder.property("tooltip-text", tooltip_text.into()),
        }
    }

    pub fn valign(self, valign: gtk::Align) -> Self {
        Self {
            builder: self.builder.property("valign", valign),
        }
    }

    pub fn vexpand(self, vexpand: bool) -> Self {
        Self {
            builder: self.builder.property("vexpand", vexpand),
        }
    }

    pub fn vexpand_set(self, vexpand_set: bool) -> Self {
        Self {
            builder: self.builder.property("vexpand-set", vexpand_set),
        }
    }

    pub fn visible(self, visible: bool) -> Self {
        Self {
            builder: self.builder.property("visible", visible),
        }
    }

    pub fn width_request(self, width_request: i32) -> Self {
        Self {
            builder: self.builder.property("width-request", width_request),
        }
    }

    //pub fn accessible_role(self, accessible_role: /*Ignored*/gtk::AccessibleRole) -> Self {
    //    Self { builder: self.builder.property("accessible-role", accessible_role), }
    //}

    // rustdoc-stripper-ignore-next
    /// Build the [`EdgePanel`].
    #[must_use = "Building the object from the builder is usually expensive and is not expected to have side effects"]
    pub fn build(self) -> EdgePanel {
        assert_initialized_main_thread!();
        self.builder.build()
    }
}
