// This file was generated by gir (https://github.com/gtk-rs/gir)
// from build
// from subprojects/gir-files
// DO NOT EDIT

use crate::ffi;
use glib::{prelude::*, translate::*};

#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Clone, Copy)]
#[non_exhaustive]
#[doc(alias = "AwraAccentSource")]
pub enum AccentSource {
    #[doc(alias = "AWRA_ACCENT_SOURCE_SYSTEM")]
    System,
    #[doc(alias = "AWRA_ACCENT_SOURCE_DEFAULT")]
    Default,
    #[doc(alias = "AWRA_ACCENT_SOURCE_CUSTOM")]
    Custom,
    #[doc(hidden)]
    __Unknown(i32),
}

#[doc(hidden)]
impl IntoGlib for AccentSource {
    type GlibType = ffi::AwraAccentSource;

    #[inline]
    fn into_glib(self) -> ffi::AwraAccentSource {
        match self {
            Self::System => ffi::AWRA_ACCENT_SOURCE_SYSTEM,
            Self::Default => ffi::AWRA_ACCENT_SOURCE_DEFAULT,
            Self::Custom => ffi::AWRA_ACCENT_SOURCE_CUSTOM,
            Self::__Unknown(value) => value,
        }
    }
}

#[doc(hidden)]
impl FromGlib<ffi::AwraAccentSource> for AccentSource {
    #[inline]
    unsafe fn from_glib(value: ffi::AwraAccentSource) -> Self {
        skip_assert_initialized!();

        match value {
            ffi::AWRA_ACCENT_SOURCE_SYSTEM => Self::System,
            ffi::AWRA_ACCENT_SOURCE_DEFAULT => Self::Default,
            ffi::AWRA_ACCENT_SOURCE_CUSTOM => Self::Custom,
            value => Self::__Unknown(value),
        }
    }
}

impl StaticType for AccentSource {
    #[inline]
    #[doc(alias = "awra_accent_source_get_type")]
    fn static_type() -> glib::Type {
        unsafe { from_glib(ffi::awra_accent_source_get_type()) }
    }
}

impl glib::HasParamSpec for AccentSource {
    type ParamSpec = glib::ParamSpecEnum;
    type SetValue = Self;
    type BuilderFn = fn(&str, Self) -> glib::ParamSpecEnumBuilder<Self>;

    fn param_spec_builder() -> Self::BuilderFn {
        Self::ParamSpec::builder_with_default
    }
}

impl glib::value::ValueType for AccentSource {
    type Type = Self;
}

unsafe impl<'a> glib::value::FromValue<'a> for AccentSource {
    type Checker = glib::value::GenericValueTypeChecker<Self>;

    #[inline]
    unsafe fn from_value(value: &'a glib::Value) -> Self {
        skip_assert_initialized!();
        unsafe { from_glib(glib::gobject_ffi::g_value_get_enum(value.to_glib_none().0)) }
    }
}

impl ToValue for AccentSource {
    #[inline]
    fn to_value(&self) -> glib::Value {
        let mut value = glib::Value::for_value_type::<Self>();
        unsafe {
            glib::gobject_ffi::g_value_set_enum(value.to_glib_none_mut().0, self.into_glib());
        }
        value
    }

    #[inline]
    fn value_type(&self) -> glib::Type {
        Self::static_type()
    }
}

impl From<AccentSource> for glib::Value {
    #[inline]
    fn from(v: AccentSource) -> Self {
        skip_assert_initialized!();
        ToValue::to_value(&v)
    }
}

#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Clone, Copy)]
#[non_exhaustive]
#[doc(alias = "AwraAppearance")]
pub enum Appearance {
    #[doc(alias = "AWRA_APPEARANCE_SYSTEM")]
    System,
    #[doc(alias = "AWRA_APPEARANCE_LIGHT")]
    Light,
    #[doc(alias = "AWRA_APPEARANCE_DARK")]
    Dark,
    #[doc(hidden)]
    __Unknown(i32),
}

#[doc(hidden)]
impl IntoGlib for Appearance {
    type GlibType = ffi::AwraAppearance;

    #[inline]
    fn into_glib(self) -> ffi::AwraAppearance {
        match self {
            Self::System => ffi::AWRA_APPEARANCE_SYSTEM,
            Self::Light => ffi::AWRA_APPEARANCE_LIGHT,
            Self::Dark => ffi::AWRA_APPEARANCE_DARK,
            Self::__Unknown(value) => value,
        }
    }
}

#[doc(hidden)]
impl FromGlib<ffi::AwraAppearance> for Appearance {
    #[inline]
    unsafe fn from_glib(value: ffi::AwraAppearance) -> Self {
        skip_assert_initialized!();

        match value {
            ffi::AWRA_APPEARANCE_SYSTEM => Self::System,
            ffi::AWRA_APPEARANCE_LIGHT => Self::Light,
            ffi::AWRA_APPEARANCE_DARK => Self::Dark,
            value => Self::__Unknown(value),
        }
    }
}

impl StaticType for Appearance {
    #[inline]
    #[doc(alias = "awra_appearance_get_type")]
    fn static_type() -> glib::Type {
        unsafe { from_glib(ffi::awra_appearance_get_type()) }
    }
}

impl glib::HasParamSpec for Appearance {
    type ParamSpec = glib::ParamSpecEnum;
    type SetValue = Self;
    type BuilderFn = fn(&str, Self) -> glib::ParamSpecEnumBuilder<Self>;

    fn param_spec_builder() -> Self::BuilderFn {
        Self::ParamSpec::builder_with_default
    }
}

impl glib::value::ValueType for Appearance {
    type Type = Self;
}

unsafe impl<'a> glib::value::FromValue<'a> for Appearance {
    type Checker = glib::value::GenericValueTypeChecker<Self>;

    #[inline]
    unsafe fn from_value(value: &'a glib::Value) -> Self {
        skip_assert_initialized!();
        unsafe { from_glib(glib::gobject_ffi::g_value_get_enum(value.to_glib_none().0)) }
    }
}

impl ToValue for Appearance {
    #[inline]
    fn to_value(&self) -> glib::Value {
        let mut value = glib::Value::for_value_type::<Self>();
        unsafe {
            glib::gobject_ffi::g_value_set_enum(value.to_glib_none_mut().0, self.into_glib());
        }
        value
    }

    #[inline]
    fn value_type(&self) -> glib::Type {
        Self::static_type()
    }
}

impl From<Appearance> for glib::Value {
    #[inline]
    fn from(v: Appearance) -> Self {
        skip_assert_initialized!();
        ToValue::to_value(&v)
    }
}

#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Clone, Copy)]
#[non_exhaustive]
#[doc(alias = "AwraBadgeAppearance")]
pub enum BadgeAppearance {
    #[doc(alias = "AWRA_BADGE_APPEARANCE_NEUTRAL")]
    Neutral,
    #[doc(alias = "AWRA_BADGE_APPEARANCE_ACCENT")]
    Accent,
    #[doc(alias = "AWRA_BADGE_APPEARANCE_INFO")]
    Info,
    #[doc(alias = "AWRA_BADGE_APPEARANCE_SUCCESS")]
    Success,
    #[doc(alias = "AWRA_BADGE_APPEARANCE_WARNING")]
    Warning,
    #[doc(alias = "AWRA_BADGE_APPEARANCE_DANGER")]
    Danger,
    #[doc(hidden)]
    __Unknown(i32),
}

#[doc(hidden)]
impl IntoGlib for BadgeAppearance {
    type GlibType = ffi::AwraBadgeAppearance;

    #[inline]
    fn into_glib(self) -> ffi::AwraBadgeAppearance {
        match self {
            Self::Neutral => ffi::AWRA_BADGE_APPEARANCE_NEUTRAL,
            Self::Accent => ffi::AWRA_BADGE_APPEARANCE_ACCENT,
            Self::Info => ffi::AWRA_BADGE_APPEARANCE_INFO,
            Self::Success => ffi::AWRA_BADGE_APPEARANCE_SUCCESS,
            Self::Warning => ffi::AWRA_BADGE_APPEARANCE_WARNING,
            Self::Danger => ffi::AWRA_BADGE_APPEARANCE_DANGER,
            Self::__Unknown(value) => value,
        }
    }
}

#[doc(hidden)]
impl FromGlib<ffi::AwraBadgeAppearance> for BadgeAppearance {
    #[inline]
    unsafe fn from_glib(value: ffi::AwraBadgeAppearance) -> Self {
        skip_assert_initialized!();

        match value {
            ffi::AWRA_BADGE_APPEARANCE_NEUTRAL => Self::Neutral,
            ffi::AWRA_BADGE_APPEARANCE_ACCENT => Self::Accent,
            ffi::AWRA_BADGE_APPEARANCE_INFO => Self::Info,
            ffi::AWRA_BADGE_APPEARANCE_SUCCESS => Self::Success,
            ffi::AWRA_BADGE_APPEARANCE_WARNING => Self::Warning,
            ffi::AWRA_BADGE_APPEARANCE_DANGER => Self::Danger,
            value => Self::__Unknown(value),
        }
    }
}

impl StaticType for BadgeAppearance {
    #[inline]
    #[doc(alias = "awra_badge_appearance_get_type")]
    fn static_type() -> glib::Type {
        unsafe { from_glib(ffi::awra_badge_appearance_get_type()) }
    }
}

impl glib::HasParamSpec for BadgeAppearance {
    type ParamSpec = glib::ParamSpecEnum;
    type SetValue = Self;
    type BuilderFn = fn(&str, Self) -> glib::ParamSpecEnumBuilder<Self>;

    fn param_spec_builder() -> Self::BuilderFn {
        Self::ParamSpec::builder_with_default
    }
}

impl glib::value::ValueType for BadgeAppearance {
    type Type = Self;
}

unsafe impl<'a> glib::value::FromValue<'a> for BadgeAppearance {
    type Checker = glib::value::GenericValueTypeChecker<Self>;

    #[inline]
    unsafe fn from_value(value: &'a glib::Value) -> Self {
        skip_assert_initialized!();
        unsafe { from_glib(glib::gobject_ffi::g_value_get_enum(value.to_glib_none().0)) }
    }
}

impl ToValue for BadgeAppearance {
    #[inline]
    fn to_value(&self) -> glib::Value {
        let mut value = glib::Value::for_value_type::<Self>();
        unsafe {
            glib::gobject_ffi::g_value_set_enum(value.to_glib_none_mut().0, self.into_glib());
        }
        value
    }

    #[inline]
    fn value_type(&self) -> glib::Type {
        Self::static_type()
    }
}

impl From<BadgeAppearance> for glib::Value {
    #[inline]
    fn from(v: BadgeAppearance) -> Self {
        skip_assert_initialized!();
        ToValue::to_value(&v)
    }
}

#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Clone, Copy)]
#[non_exhaustive]
#[doc(alias = "AwraButtonAppearance")]
pub enum ButtonAppearance {
    #[doc(alias = "AWRA_BUTTON_APPEARANCE_PRIMARY")]
    Primary,
    #[doc(alias = "AWRA_BUTTON_APPEARANCE_SECONDARY")]
    Secondary,
    #[doc(alias = "AWRA_BUTTON_APPEARANCE_GHOST")]
    Ghost,
    #[doc(alias = "AWRA_BUTTON_APPEARANCE_DESTRUCTIVE")]
    Destructive,
    #[doc(alias = "AWRA_BUTTON_APPEARANCE_TOOLBAR")]
    Toolbar,
    #[doc(hidden)]
    __Unknown(i32),
}

#[doc(hidden)]
impl IntoGlib for ButtonAppearance {
    type GlibType = ffi::AwraButtonAppearance;

    #[inline]
    fn into_glib(self) -> ffi::AwraButtonAppearance {
        match self {
            Self::Primary => ffi::AWRA_BUTTON_APPEARANCE_PRIMARY,
            Self::Secondary => ffi::AWRA_BUTTON_APPEARANCE_SECONDARY,
            Self::Ghost => ffi::AWRA_BUTTON_APPEARANCE_GHOST,
            Self::Destructive => ffi::AWRA_BUTTON_APPEARANCE_DESTRUCTIVE,
            Self::Toolbar => ffi::AWRA_BUTTON_APPEARANCE_TOOLBAR,
            Self::__Unknown(value) => value,
        }
    }
}

#[doc(hidden)]
impl FromGlib<ffi::AwraButtonAppearance> for ButtonAppearance {
    #[inline]
    unsafe fn from_glib(value: ffi::AwraButtonAppearance) -> Self {
        skip_assert_initialized!();

        match value {
            ffi::AWRA_BUTTON_APPEARANCE_PRIMARY => Self::Primary,
            ffi::AWRA_BUTTON_APPEARANCE_SECONDARY => Self::Secondary,
            ffi::AWRA_BUTTON_APPEARANCE_GHOST => Self::Ghost,
            ffi::AWRA_BUTTON_APPEARANCE_DESTRUCTIVE => Self::Destructive,
            ffi::AWRA_BUTTON_APPEARANCE_TOOLBAR => Self::Toolbar,
            value => Self::__Unknown(value),
        }
    }
}

impl StaticType for ButtonAppearance {
    #[inline]
    #[doc(alias = "awra_button_appearance_get_type")]
    fn static_type() -> glib::Type {
        unsafe { from_glib(ffi::awra_button_appearance_get_type()) }
    }
}

impl glib::HasParamSpec for ButtonAppearance {
    type ParamSpec = glib::ParamSpecEnum;
    type SetValue = Self;
    type BuilderFn = fn(&str, Self) -> glib::ParamSpecEnumBuilder<Self>;

    fn param_spec_builder() -> Self::BuilderFn {
        Self::ParamSpec::builder_with_default
    }
}

impl glib::value::ValueType for ButtonAppearance {
    type Type = Self;
}

unsafe impl<'a> glib::value::FromValue<'a> for ButtonAppearance {
    type Checker = glib::value::GenericValueTypeChecker<Self>;

    #[inline]
    unsafe fn from_value(value: &'a glib::Value) -> Self {
        skip_assert_initialized!();
        unsafe { from_glib(glib::gobject_ffi::g_value_get_enum(value.to_glib_none().0)) }
    }
}

impl ToValue for ButtonAppearance {
    #[inline]
    fn to_value(&self) -> glib::Value {
        let mut value = glib::Value::for_value_type::<Self>();
        unsafe {
            glib::gobject_ffi::g_value_set_enum(value.to_glib_none_mut().0, self.into_glib());
        }
        value
    }

    #[inline]
    fn value_type(&self) -> glib::Type {
        Self::static_type()
    }
}

impl From<ButtonAppearance> for glib::Value {
    #[inline]
    fn from(v: ButtonAppearance) -> Self {
        skip_assert_initialized!();
        ToValue::to_value(&v)
    }
}

#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Clone, Copy)]
#[non_exhaustive]
#[doc(alias = "AwraCardAppearance")]
pub enum CardAppearance {
    #[doc(alias = "AWRA_CARD_APPEARANCE_PLAIN")]
    Plain,
    #[doc(alias = "AWRA_CARD_APPEARANCE_TINTED")]
    Tinted,
    #[doc(alias = "AWRA_CARD_APPEARANCE_RAISED")]
    Raised,
    #[doc(hidden)]
    __Unknown(i32),
}

#[doc(hidden)]
impl IntoGlib for CardAppearance {
    type GlibType = ffi::AwraCardAppearance;

    #[inline]
    fn into_glib(self) -> ffi::AwraCardAppearance {
        match self {
            Self::Plain => ffi::AWRA_CARD_APPEARANCE_PLAIN,
            Self::Tinted => ffi::AWRA_CARD_APPEARANCE_TINTED,
            Self::Raised => ffi::AWRA_CARD_APPEARANCE_RAISED,
            Self::__Unknown(value) => value,
        }
    }
}

#[doc(hidden)]
impl FromGlib<ffi::AwraCardAppearance> for CardAppearance {
    #[inline]
    unsafe fn from_glib(value: ffi::AwraCardAppearance) -> Self {
        skip_assert_initialized!();

        match value {
            ffi::AWRA_CARD_APPEARANCE_PLAIN => Self::Plain,
            ffi::AWRA_CARD_APPEARANCE_TINTED => Self::Tinted,
            ffi::AWRA_CARD_APPEARANCE_RAISED => Self::Raised,
            value => Self::__Unknown(value),
        }
    }
}

impl StaticType for CardAppearance {
    #[inline]
    #[doc(alias = "awra_card_appearance_get_type")]
    fn static_type() -> glib::Type {
        unsafe { from_glib(ffi::awra_card_appearance_get_type()) }
    }
}

impl glib::HasParamSpec for CardAppearance {
    type ParamSpec = glib::ParamSpecEnum;
    type SetValue = Self;
    type BuilderFn = fn(&str, Self) -> glib::ParamSpecEnumBuilder<Self>;

    fn param_spec_builder() -> Self::BuilderFn {
        Self::ParamSpec::builder_with_default
    }
}

impl glib::value::ValueType for CardAppearance {
    type Type = Self;
}

unsafe impl<'a> glib::value::FromValue<'a> for CardAppearance {
    type Checker = glib::value::GenericValueTypeChecker<Self>;

    #[inline]
    unsafe fn from_value(value: &'a glib::Value) -> Self {
        skip_assert_initialized!();
        unsafe { from_glib(glib::gobject_ffi::g_value_get_enum(value.to_glib_none().0)) }
    }
}

impl ToValue for CardAppearance {
    #[inline]
    fn to_value(&self) -> glib::Value {
        let mut value = glib::Value::for_value_type::<Self>();
        unsafe {
            glib::gobject_ffi::g_value_set_enum(value.to_glib_none_mut().0, self.into_glib());
        }
        value
    }

    #[inline]
    fn value_type(&self) -> glib::Type {
        Self::static_type()
    }
}

impl From<CardAppearance> for glib::Value {
    #[inline]
    fn from(v: CardAppearance) -> Self {
        skip_assert_initialized!();
        ToValue::to_value(&v)
    }
}

#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Clone, Copy)]
#[non_exhaustive]
#[doc(alias = "AwraDataViewState")]
pub enum DataViewState {
    #[doc(alias = "AWRA_DATA_VIEW_STATE_CONTENT")]
    Content,
    #[doc(alias = "AWRA_DATA_VIEW_STATE_EMPTY")]
    Empty,
    #[doc(alias = "AWRA_DATA_VIEW_STATE_LOADING")]
    Loading,
    #[doc(alias = "AWRA_DATA_VIEW_STATE_ERROR")]
    Error,
    #[doc(hidden)]
    __Unknown(i32),
}

#[doc(hidden)]
impl IntoGlib for DataViewState {
    type GlibType = ffi::AwraDataViewState;

    #[inline]
    fn into_glib(self) -> ffi::AwraDataViewState {
        match self {
            Self::Content => ffi::AWRA_DATA_VIEW_STATE_CONTENT,
            Self::Empty => ffi::AWRA_DATA_VIEW_STATE_EMPTY,
            Self::Loading => ffi::AWRA_DATA_VIEW_STATE_LOADING,
            Self::Error => ffi::AWRA_DATA_VIEW_STATE_ERROR,
            Self::__Unknown(value) => value,
        }
    }
}

#[doc(hidden)]
impl FromGlib<ffi::AwraDataViewState> for DataViewState {
    #[inline]
    unsafe fn from_glib(value: ffi::AwraDataViewState) -> Self {
        skip_assert_initialized!();

        match value {
            ffi::AWRA_DATA_VIEW_STATE_CONTENT => Self::Content,
            ffi::AWRA_DATA_VIEW_STATE_EMPTY => Self::Empty,
            ffi::AWRA_DATA_VIEW_STATE_LOADING => Self::Loading,
            ffi::AWRA_DATA_VIEW_STATE_ERROR => Self::Error,
            value => Self::__Unknown(value),
        }
    }
}

impl StaticType for DataViewState {
    #[inline]
    #[doc(alias = "awra_data_view_state_get_type")]
    fn static_type() -> glib::Type {
        unsafe { from_glib(ffi::awra_data_view_state_get_type()) }
    }
}

impl glib::HasParamSpec for DataViewState {
    type ParamSpec = glib::ParamSpecEnum;
    type SetValue = Self;
    type BuilderFn = fn(&str, Self) -> glib::ParamSpecEnumBuilder<Self>;

    fn param_spec_builder() -> Self::BuilderFn {
        Self::ParamSpec::builder_with_default
    }
}

impl glib::value::ValueType for DataViewState {
    type Type = Self;
}

unsafe impl<'a> glib::value::FromValue<'a> for DataViewState {
    type Checker = glib::value::GenericValueTypeChecker<Self>;

    #[inline]
    unsafe fn from_value(value: &'a glib::Value) -> Self {
        skip_assert_initialized!();
        unsafe { from_glib(glib::gobject_ffi::g_value_get_enum(value.to_glib_none().0)) }
    }
}

impl ToValue for DataViewState {
    #[inline]
    fn to_value(&self) -> glib::Value {
        let mut value = glib::Value::for_value_type::<Self>();
        unsafe {
            glib::gobject_ffi::g_value_set_enum(value.to_glib_none_mut().0, self.into_glib());
        }
        value
    }

    #[inline]
    fn value_type(&self) -> glib::Type {
        Self::static_type()
    }
}

impl From<DataViewState> for glib::Value {
    #[inline]
    fn from(v: DataViewState) -> Self {
        skip_assert_initialized!();
        ToValue::to_value(&v)
    }
}

#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Clone, Copy)]
#[non_exhaustive]
#[doc(alias = "AwraElevation")]
pub enum Elevation {
    #[doc(alias = "AWRA_ELEVATION_FLAT")]
    Flat,
    #[doc(alias = "AWRA_ELEVATION_RAISED")]
    Raised,
    #[doc(alias = "AWRA_ELEVATION_FLOATING")]
    Floating,
    #[doc(alias = "AWRA_ELEVATION_MODAL")]
    Modal,
    #[doc(hidden)]
    __Unknown(i32),
}

#[doc(hidden)]
impl IntoGlib for Elevation {
    type GlibType = ffi::AwraElevation;

    #[inline]
    fn into_glib(self) -> ffi::AwraElevation {
        match self {
            Self::Flat => ffi::AWRA_ELEVATION_FLAT,
            Self::Raised => ffi::AWRA_ELEVATION_RAISED,
            Self::Floating => ffi::AWRA_ELEVATION_FLOATING,
            Self::Modal => ffi::AWRA_ELEVATION_MODAL,
            Self::__Unknown(value) => value,
        }
    }
}

#[doc(hidden)]
impl FromGlib<ffi::AwraElevation> for Elevation {
    #[inline]
    unsafe fn from_glib(value: ffi::AwraElevation) -> Self {
        skip_assert_initialized!();

        match value {
            ffi::AWRA_ELEVATION_FLAT => Self::Flat,
            ffi::AWRA_ELEVATION_RAISED => Self::Raised,
            ffi::AWRA_ELEVATION_FLOATING => Self::Floating,
            ffi::AWRA_ELEVATION_MODAL => Self::Modal,
            value => Self::__Unknown(value),
        }
    }
}

impl StaticType for Elevation {
    #[inline]
    #[doc(alias = "awra_elevation_get_type")]
    fn static_type() -> glib::Type {
        unsafe { from_glib(ffi::awra_elevation_get_type()) }
    }
}

impl glib::HasParamSpec for Elevation {
    type ParamSpec = glib::ParamSpecEnum;
    type SetValue = Self;
    type BuilderFn = fn(&str, Self) -> glib::ParamSpecEnumBuilder<Self>;

    fn param_spec_builder() -> Self::BuilderFn {
        Self::ParamSpec::builder_with_default
    }
}

impl glib::value::ValueType for Elevation {
    type Type = Self;
}

unsafe impl<'a> glib::value::FromValue<'a> for Elevation {
    type Checker = glib::value::GenericValueTypeChecker<Self>;

    #[inline]
    unsafe fn from_value(value: &'a glib::Value) -> Self {
        skip_assert_initialized!();
        unsafe { from_glib(glib::gobject_ffi::g_value_get_enum(value.to_glib_none().0)) }
    }
}

impl ToValue for Elevation {
    #[inline]
    fn to_value(&self) -> glib::Value {
        let mut value = glib::Value::for_value_type::<Self>();
        unsafe {
            glib::gobject_ffi::g_value_set_enum(value.to_glib_none_mut().0, self.into_glib());
        }
        value
    }

    #[inline]
    fn value_type(&self) -> glib::Type {
        Self::static_type()
    }
}

impl From<Elevation> for glib::Value {
    #[inline]
    fn from(v: Elevation) -> Self {
        skip_assert_initialized!();
        ToValue::to_value(&v)
    }
}

#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Clone, Copy)]
#[non_exhaustive]
#[doc(alias = "AwraLayoutMode")]
pub enum LayoutMode {
    #[doc(alias = "AWRA_LAYOUT_MODE_COMPACT")]
    Compact,
    #[doc(alias = "AWRA_LAYOUT_MODE_MEDIUM")]
    Medium,
    #[doc(alias = "AWRA_LAYOUT_MODE_EXPANDED")]
    Expanded,
    #[doc(hidden)]
    __Unknown(i32),
}

#[doc(hidden)]
impl IntoGlib for LayoutMode {
    type GlibType = ffi::AwraLayoutMode;

    #[inline]
    fn into_glib(self) -> ffi::AwraLayoutMode {
        match self {
            Self::Compact => ffi::AWRA_LAYOUT_MODE_COMPACT,
            Self::Medium => ffi::AWRA_LAYOUT_MODE_MEDIUM,
            Self::Expanded => ffi::AWRA_LAYOUT_MODE_EXPANDED,
            Self::__Unknown(value) => value,
        }
    }
}

#[doc(hidden)]
impl FromGlib<ffi::AwraLayoutMode> for LayoutMode {
    #[inline]
    unsafe fn from_glib(value: ffi::AwraLayoutMode) -> Self {
        skip_assert_initialized!();

        match value {
            ffi::AWRA_LAYOUT_MODE_COMPACT => Self::Compact,
            ffi::AWRA_LAYOUT_MODE_MEDIUM => Self::Medium,
            ffi::AWRA_LAYOUT_MODE_EXPANDED => Self::Expanded,
            value => Self::__Unknown(value),
        }
    }
}

impl StaticType for LayoutMode {
    #[inline]
    #[doc(alias = "awra_layout_mode_get_type")]
    fn static_type() -> glib::Type {
        unsafe { from_glib(ffi::awra_layout_mode_get_type()) }
    }
}

impl glib::HasParamSpec for LayoutMode {
    type ParamSpec = glib::ParamSpecEnum;
    type SetValue = Self;
    type BuilderFn = fn(&str, Self) -> glib::ParamSpecEnumBuilder<Self>;

    fn param_spec_builder() -> Self::BuilderFn {
        Self::ParamSpec::builder_with_default
    }
}

impl glib::value::ValueType for LayoutMode {
    type Type = Self;
}

unsafe impl<'a> glib::value::FromValue<'a> for LayoutMode {
    type Checker = glib::value::GenericValueTypeChecker<Self>;

    #[inline]
    unsafe fn from_value(value: &'a glib::Value) -> Self {
        skip_assert_initialized!();
        unsafe { from_glib(glib::gobject_ffi::g_value_get_enum(value.to_glib_none().0)) }
    }
}

impl ToValue for LayoutMode {
    #[inline]
    fn to_value(&self) -> glib::Value {
        let mut value = glib::Value::for_value_type::<Self>();
        unsafe {
            glib::gobject_ffi::g_value_set_enum(value.to_glib_none_mut().0, self.into_glib());
        }
        value
    }

    #[inline]
    fn value_type(&self) -> glib::Type {
        Self::static_type()
    }
}

impl From<LayoutMode> for glib::Value {
    #[inline]
    fn from(v: LayoutMode) -> Self {
        skip_assert_initialized!();
        ToValue::to_value(&v)
    }
}

#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Clone, Copy)]
#[non_exhaustive]
#[doc(alias = "AwraLayoutPreset")]
pub enum LayoutPreset {
    #[doc(alias = "AWRA_LAYOUT_PRESET_COMPACT")]
    Compact,
    #[doc(alias = "AWRA_LAYOUT_PRESET_CONTROL_GROUP")]
    ControlGroup,
    #[doc(alias = "AWRA_LAYOUT_PRESET_SECTION")]
    Section,
    #[doc(alias = "AWRA_LAYOUT_PRESET_CONTENT")]
    Content,
    #[doc(alias = "AWRA_LAYOUT_PRESET_PAGE")]
    Page,
    #[doc(alias = "AWRA_LAYOUT_PRESET_TOOLBAR")]
    Toolbar,
    #[doc(alias = "AWRA_LAYOUT_PRESET_OVERLAY")]
    Overlay,
    #[doc(hidden)]
    __Unknown(i32),
}

#[doc(hidden)]
impl IntoGlib for LayoutPreset {
    type GlibType = ffi::AwraLayoutPreset;

    #[inline]
    fn into_glib(self) -> ffi::AwraLayoutPreset {
        match self {
            Self::Compact => ffi::AWRA_LAYOUT_PRESET_COMPACT,
            Self::ControlGroup => ffi::AWRA_LAYOUT_PRESET_CONTROL_GROUP,
            Self::Section => ffi::AWRA_LAYOUT_PRESET_SECTION,
            Self::Content => ffi::AWRA_LAYOUT_PRESET_CONTENT,
            Self::Page => ffi::AWRA_LAYOUT_PRESET_PAGE,
            Self::Toolbar => ffi::AWRA_LAYOUT_PRESET_TOOLBAR,
            Self::Overlay => ffi::AWRA_LAYOUT_PRESET_OVERLAY,
            Self::__Unknown(value) => value,
        }
    }
}

#[doc(hidden)]
impl FromGlib<ffi::AwraLayoutPreset> for LayoutPreset {
    #[inline]
    unsafe fn from_glib(value: ffi::AwraLayoutPreset) -> Self {
        skip_assert_initialized!();

        match value {
            ffi::AWRA_LAYOUT_PRESET_COMPACT => Self::Compact,
            ffi::AWRA_LAYOUT_PRESET_CONTROL_GROUP => Self::ControlGroup,
            ffi::AWRA_LAYOUT_PRESET_SECTION => Self::Section,
            ffi::AWRA_LAYOUT_PRESET_CONTENT => Self::Content,
            ffi::AWRA_LAYOUT_PRESET_PAGE => Self::Page,
            ffi::AWRA_LAYOUT_PRESET_TOOLBAR => Self::Toolbar,
            ffi::AWRA_LAYOUT_PRESET_OVERLAY => Self::Overlay,
            value => Self::__Unknown(value),
        }
    }
}

impl StaticType for LayoutPreset {
    #[inline]
    #[doc(alias = "awra_layout_preset_get_type")]
    fn static_type() -> glib::Type {
        unsafe { from_glib(ffi::awra_layout_preset_get_type()) }
    }
}

impl glib::HasParamSpec for LayoutPreset {
    type ParamSpec = glib::ParamSpecEnum;
    type SetValue = Self;
    type BuilderFn = fn(&str, Self) -> glib::ParamSpecEnumBuilder<Self>;

    fn param_spec_builder() -> Self::BuilderFn {
        Self::ParamSpec::builder_with_default
    }
}

impl glib::value::ValueType for LayoutPreset {
    type Type = Self;
}

unsafe impl<'a> glib::value::FromValue<'a> for LayoutPreset {
    type Checker = glib::value::GenericValueTypeChecker<Self>;

    #[inline]
    unsafe fn from_value(value: &'a glib::Value) -> Self {
        skip_assert_initialized!();
        unsafe { from_glib(glib::gobject_ffi::g_value_get_enum(value.to_glib_none().0)) }
    }
}

impl ToValue for LayoutPreset {
    #[inline]
    fn to_value(&self) -> glib::Value {
        let mut value = glib::Value::for_value_type::<Self>();
        unsafe {
            glib::gobject_ffi::g_value_set_enum(value.to_glib_none_mut().0, self.into_glib());
        }
        value
    }

    #[inline]
    fn value_type(&self) -> glib::Type {
        Self::static_type()
    }
}

impl From<LayoutPreset> for glib::Value {
    #[inline]
    fn from(v: LayoutPreset) -> Self {
        skip_assert_initialized!();
        ToValue::to_value(&v)
    }
}

#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Clone, Copy)]
#[non_exhaustive]
#[doc(alias = "AwraMasterDetailPane")]
pub enum MasterDetailPane {
    #[doc(alias = "AWRA_MASTER_DETAIL_PANE_MASTER")]
    Master,
    #[doc(alias = "AWRA_MASTER_DETAIL_PANE_DETAIL")]
    Detail,
    #[doc(hidden)]
    __Unknown(i32),
}

#[doc(hidden)]
impl IntoGlib for MasterDetailPane {
    type GlibType = ffi::AwraMasterDetailPane;

    #[inline]
    fn into_glib(self) -> ffi::AwraMasterDetailPane {
        match self {
            Self::Master => ffi::AWRA_MASTER_DETAIL_PANE_MASTER,
            Self::Detail => ffi::AWRA_MASTER_DETAIL_PANE_DETAIL,
            Self::__Unknown(value) => value,
        }
    }
}

#[doc(hidden)]
impl FromGlib<ffi::AwraMasterDetailPane> for MasterDetailPane {
    #[inline]
    unsafe fn from_glib(value: ffi::AwraMasterDetailPane) -> Self {
        skip_assert_initialized!();

        match value {
            ffi::AWRA_MASTER_DETAIL_PANE_MASTER => Self::Master,
            ffi::AWRA_MASTER_DETAIL_PANE_DETAIL => Self::Detail,
            value => Self::__Unknown(value),
        }
    }
}

impl StaticType for MasterDetailPane {
    #[inline]
    #[doc(alias = "awra_master_detail_pane_get_type")]
    fn static_type() -> glib::Type {
        unsafe { from_glib(ffi::awra_master_detail_pane_get_type()) }
    }
}

impl glib::HasParamSpec for MasterDetailPane {
    type ParamSpec = glib::ParamSpecEnum;
    type SetValue = Self;
    type BuilderFn = fn(&str, Self) -> glib::ParamSpecEnumBuilder<Self>;

    fn param_spec_builder() -> Self::BuilderFn {
        Self::ParamSpec::builder_with_default
    }
}

impl glib::value::ValueType for MasterDetailPane {
    type Type = Self;
}

unsafe impl<'a> glib::value::FromValue<'a> for MasterDetailPane {
    type Checker = glib::value::GenericValueTypeChecker<Self>;

    #[inline]
    unsafe fn from_value(value: &'a glib::Value) -> Self {
        skip_assert_initialized!();
        unsafe { from_glib(glib::gobject_ffi::g_value_get_enum(value.to_glib_none().0)) }
    }
}

impl ToValue for MasterDetailPane {
    #[inline]
    fn to_value(&self) -> glib::Value {
        let mut value = glib::Value::for_value_type::<Self>();
        unsafe {
            glib::gobject_ffi::g_value_set_enum(value.to_glib_none_mut().0, self.into_glib());
        }
        value
    }

    #[inline]
    fn value_type(&self) -> glib::Type {
        Self::static_type()
    }
}

impl From<MasterDetailPane> for glib::Value {
    #[inline]
    fn from(v: MasterDetailPane) -> Self {
        skip_assert_initialized!();
        ToValue::to_value(&v)
    }
}

#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Clone, Copy)]
#[non_exhaustive]
#[doc(alias = "AwraMaterialKind")]
pub enum MaterialKind {
    #[doc(alias = "AWRA_MATERIAL_KIND_SOLID")]
    Solid,
    #[doc(alias = "AWRA_MATERIAL_KIND_TRANSLUCENT")]
    Translucent,
    #[doc(alias = "AWRA_MATERIAL_KIND_FROSTED")]
    Frosted,
    #[doc(alias = "AWRA_MATERIAL_KIND_LIQUID")]
    Liquid,
    #[doc(hidden)]
    __Unknown(i32),
}

#[doc(hidden)]
impl IntoGlib for MaterialKind {
    type GlibType = ffi::AwraMaterialKind;

    #[inline]
    fn into_glib(self) -> ffi::AwraMaterialKind {
        match self {
            Self::Solid => ffi::AWRA_MATERIAL_KIND_SOLID,
            Self::Translucent => ffi::AWRA_MATERIAL_KIND_TRANSLUCENT,
            Self::Frosted => ffi::AWRA_MATERIAL_KIND_FROSTED,
            Self::Liquid => ffi::AWRA_MATERIAL_KIND_LIQUID,
            Self::__Unknown(value) => value,
        }
    }
}

#[doc(hidden)]
impl FromGlib<ffi::AwraMaterialKind> for MaterialKind {
    #[inline]
    unsafe fn from_glib(value: ffi::AwraMaterialKind) -> Self {
        skip_assert_initialized!();

        match value {
            ffi::AWRA_MATERIAL_KIND_SOLID => Self::Solid,
            ffi::AWRA_MATERIAL_KIND_TRANSLUCENT => Self::Translucent,
            ffi::AWRA_MATERIAL_KIND_FROSTED => Self::Frosted,
            ffi::AWRA_MATERIAL_KIND_LIQUID => Self::Liquid,
            value => Self::__Unknown(value),
        }
    }
}

impl StaticType for MaterialKind {
    #[inline]
    #[doc(alias = "awra_material_kind_get_type")]
    fn static_type() -> glib::Type {
        unsafe { from_glib(ffi::awra_material_kind_get_type()) }
    }
}

impl glib::HasParamSpec for MaterialKind {
    type ParamSpec = glib::ParamSpecEnum;
    type SetValue = Self;
    type BuilderFn = fn(&str, Self) -> glib::ParamSpecEnumBuilder<Self>;

    fn param_spec_builder() -> Self::BuilderFn {
        Self::ParamSpec::builder_with_default
    }
}

impl glib::value::ValueType for MaterialKind {
    type Type = Self;
}

unsafe impl<'a> glib::value::FromValue<'a> for MaterialKind {
    type Checker = glib::value::GenericValueTypeChecker<Self>;

    #[inline]
    unsafe fn from_value(value: &'a glib::Value) -> Self {
        skip_assert_initialized!();
        unsafe { from_glib(glib::gobject_ffi::g_value_get_enum(value.to_glib_none().0)) }
    }
}

impl ToValue for MaterialKind {
    #[inline]
    fn to_value(&self) -> glib::Value {
        let mut value = glib::Value::for_value_type::<Self>();
        unsafe {
            glib::gobject_ffi::g_value_set_enum(value.to_glib_none_mut().0, self.into_glib());
        }
        value
    }

    #[inline]
    fn value_type(&self) -> glib::Type {
        Self::static_type()
    }
}

impl From<MaterialKind> for glib::Value {
    #[inline]
    fn from(v: MaterialKind) -> Self {
        skip_assert_initialized!();
        ToValue::to_value(&v)
    }
}

#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Clone, Copy)]
#[non_exhaustive]
#[doc(alias = "AwraMaterialPreset")]
pub enum MaterialPreset {
    #[doc(alias = "AWRA_MATERIAL_PRESET_NONE")]
    None,
    #[doc(alias = "AWRA_MATERIAL_PRESET_CANVAS")]
    Canvas,
    #[doc(alias = "AWRA_MATERIAL_PRESET_CONTENT")]
    Content,
    #[doc(alias = "AWRA_MATERIAL_PRESET_CHROME")]
    Chrome,
    #[doc(alias = "AWRA_MATERIAL_PRESET_LAYER")]
    Layer,
    #[doc(alias = "AWRA_MATERIAL_PRESET_FLOATING")]
    Floating,
    #[doc(alias = "AWRA_MATERIAL_PRESET_OPAQUE")]
    Opaque,
    #[doc(hidden)]
    __Unknown(i32),
}

#[doc(hidden)]
impl IntoGlib for MaterialPreset {
    type GlibType = ffi::AwraMaterialPreset;

    #[inline]
    fn into_glib(self) -> ffi::AwraMaterialPreset {
        match self {
            Self::None => ffi::AWRA_MATERIAL_PRESET_NONE,
            Self::Canvas => ffi::AWRA_MATERIAL_PRESET_CANVAS,
            Self::Content => ffi::AWRA_MATERIAL_PRESET_CONTENT,
            Self::Chrome => ffi::AWRA_MATERIAL_PRESET_CHROME,
            Self::Layer => ffi::AWRA_MATERIAL_PRESET_LAYER,
            Self::Floating => ffi::AWRA_MATERIAL_PRESET_FLOATING,
            Self::Opaque => ffi::AWRA_MATERIAL_PRESET_OPAQUE,
            Self::__Unknown(value) => value,
        }
    }
}

#[doc(hidden)]
impl FromGlib<ffi::AwraMaterialPreset> for MaterialPreset {
    #[inline]
    unsafe fn from_glib(value: ffi::AwraMaterialPreset) -> Self {
        skip_assert_initialized!();

        match value {
            ffi::AWRA_MATERIAL_PRESET_NONE => Self::None,
            ffi::AWRA_MATERIAL_PRESET_CANVAS => Self::Canvas,
            ffi::AWRA_MATERIAL_PRESET_CONTENT => Self::Content,
            ffi::AWRA_MATERIAL_PRESET_CHROME => Self::Chrome,
            ffi::AWRA_MATERIAL_PRESET_LAYER => Self::Layer,
            ffi::AWRA_MATERIAL_PRESET_FLOATING => Self::Floating,
            ffi::AWRA_MATERIAL_PRESET_OPAQUE => Self::Opaque,
            value => Self::__Unknown(value),
        }
    }
}

impl StaticType for MaterialPreset {
    #[inline]
    #[doc(alias = "awra_material_preset_get_type")]
    fn static_type() -> glib::Type {
        unsafe { from_glib(ffi::awra_material_preset_get_type()) }
    }
}

impl glib::HasParamSpec for MaterialPreset {
    type ParamSpec = glib::ParamSpecEnum;
    type SetValue = Self;
    type BuilderFn = fn(&str, Self) -> glib::ParamSpecEnumBuilder<Self>;

    fn param_spec_builder() -> Self::BuilderFn {
        Self::ParamSpec::builder_with_default
    }
}

impl glib::value::ValueType for MaterialPreset {
    type Type = Self;
}

unsafe impl<'a> glib::value::FromValue<'a> for MaterialPreset {
    type Checker = glib::value::GenericValueTypeChecker<Self>;

    #[inline]
    unsafe fn from_value(value: &'a glib::Value) -> Self {
        skip_assert_initialized!();
        unsafe { from_glib(glib::gobject_ffi::g_value_get_enum(value.to_glib_none().0)) }
    }
}

impl ToValue for MaterialPreset {
    #[inline]
    fn to_value(&self) -> glib::Value {
        let mut value = glib::Value::for_value_type::<Self>();
        unsafe {
            glib::gobject_ffi::g_value_set_enum(value.to_glib_none_mut().0, self.into_glib());
        }
        value
    }

    #[inline]
    fn value_type(&self) -> glib::Type {
        Self::static_type()
    }
}

impl From<MaterialPreset> for glib::Value {
    #[inline]
    fn from(v: MaterialPreset) -> Self {
        skip_assert_initialized!();
        ToValue::to_value(&v)
    }
}

#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Clone, Copy)]
#[non_exhaustive]
#[doc(alias = "AwraMotionPreset")]
pub enum MotionPreset {
    #[doc(alias = "AWRA_MOTION_PRESET_INSTANT")]
    Instant,
    #[doc(alias = "AWRA_MOTION_PRESET_FAST")]
    Fast,
    #[doc(alias = "AWRA_MOTION_PRESET_NORMAL")]
    Normal,
    #[doc(alias = "AWRA_MOTION_PRESET_SLOW")]
    Slow,
    #[doc(hidden)]
    __Unknown(i32),
}

#[doc(hidden)]
impl IntoGlib for MotionPreset {
    type GlibType = ffi::AwraMotionPreset;

    #[inline]
    fn into_glib(self) -> ffi::AwraMotionPreset {
        match self {
            Self::Instant => ffi::AWRA_MOTION_PRESET_INSTANT,
            Self::Fast => ffi::AWRA_MOTION_PRESET_FAST,
            Self::Normal => ffi::AWRA_MOTION_PRESET_NORMAL,
            Self::Slow => ffi::AWRA_MOTION_PRESET_SLOW,
            Self::__Unknown(value) => value,
        }
    }
}

#[doc(hidden)]
impl FromGlib<ffi::AwraMotionPreset> for MotionPreset {
    #[inline]
    unsafe fn from_glib(value: ffi::AwraMotionPreset) -> Self {
        skip_assert_initialized!();

        match value {
            ffi::AWRA_MOTION_PRESET_INSTANT => Self::Instant,
            ffi::AWRA_MOTION_PRESET_FAST => Self::Fast,
            ffi::AWRA_MOTION_PRESET_NORMAL => Self::Normal,
            ffi::AWRA_MOTION_PRESET_SLOW => Self::Slow,
            value => Self::__Unknown(value),
        }
    }
}

impl StaticType for MotionPreset {
    #[inline]
    #[doc(alias = "awra_motion_preset_get_type")]
    fn static_type() -> glib::Type {
        unsafe { from_glib(ffi::awra_motion_preset_get_type()) }
    }
}

impl glib::HasParamSpec for MotionPreset {
    type ParamSpec = glib::ParamSpecEnum;
    type SetValue = Self;
    type BuilderFn = fn(&str, Self) -> glib::ParamSpecEnumBuilder<Self>;

    fn param_spec_builder() -> Self::BuilderFn {
        Self::ParamSpec::builder_with_default
    }
}

impl glib::value::ValueType for MotionPreset {
    type Type = Self;
}

unsafe impl<'a> glib::value::FromValue<'a> for MotionPreset {
    type Checker = glib::value::GenericValueTypeChecker<Self>;

    #[inline]
    unsafe fn from_value(value: &'a glib::Value) -> Self {
        skip_assert_initialized!();
        unsafe { from_glib(glib::gobject_ffi::g_value_get_enum(value.to_glib_none().0)) }
    }
}

impl ToValue for MotionPreset {
    #[inline]
    fn to_value(&self) -> glib::Value {
        let mut value = glib::Value::for_value_type::<Self>();
        unsafe {
            glib::gobject_ffi::g_value_set_enum(value.to_glib_none_mut().0, self.into_glib());
        }
        value
    }

    #[inline]
    fn value_type(&self) -> glib::Type {
        Self::static_type()
    }
}

impl From<MotionPreset> for glib::Value {
    #[inline]
    fn from(v: MotionPreset) -> Self {
        skip_assert_initialized!();
        ToValue::to_value(&v)
    }
}

#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Clone, Copy)]
#[non_exhaustive]
#[doc(alias = "AwraPanelEdge")]
pub enum PanelEdge {
    #[doc(alias = "AWRA_PANEL_EDGE_START")]
    Start,
    #[doc(alias = "AWRA_PANEL_EDGE_END")]
    End,
    #[doc(hidden)]
    __Unknown(i32),
}

#[doc(hidden)]
impl IntoGlib for PanelEdge {
    type GlibType = ffi::AwraPanelEdge;

    #[inline]
    fn into_glib(self) -> ffi::AwraPanelEdge {
        match self {
            Self::Start => ffi::AWRA_PANEL_EDGE_START,
            Self::End => ffi::AWRA_PANEL_EDGE_END,
            Self::__Unknown(value) => value,
        }
    }
}

#[doc(hidden)]
impl FromGlib<ffi::AwraPanelEdge> for PanelEdge {
    #[inline]
    unsafe fn from_glib(value: ffi::AwraPanelEdge) -> Self {
        skip_assert_initialized!();

        match value {
            ffi::AWRA_PANEL_EDGE_START => Self::Start,
            ffi::AWRA_PANEL_EDGE_END => Self::End,
            value => Self::__Unknown(value),
        }
    }
}

impl StaticType for PanelEdge {
    #[inline]
    #[doc(alias = "awra_panel_edge_get_type")]
    fn static_type() -> glib::Type {
        unsafe { from_glib(ffi::awra_panel_edge_get_type()) }
    }
}

impl glib::HasParamSpec for PanelEdge {
    type ParamSpec = glib::ParamSpecEnum;
    type SetValue = Self;
    type BuilderFn = fn(&str, Self) -> glib::ParamSpecEnumBuilder<Self>;

    fn param_spec_builder() -> Self::BuilderFn {
        Self::ParamSpec::builder_with_default
    }
}

impl glib::value::ValueType for PanelEdge {
    type Type = Self;
}

unsafe impl<'a> glib::value::FromValue<'a> for PanelEdge {
    type Checker = glib::value::GenericValueTypeChecker<Self>;

    #[inline]
    unsafe fn from_value(value: &'a glib::Value) -> Self {
        skip_assert_initialized!();
        unsafe { from_glib(glib::gobject_ffi::g_value_get_enum(value.to_glib_none().0)) }
    }
}

impl ToValue for PanelEdge {
    #[inline]
    fn to_value(&self) -> glib::Value {
        let mut value = glib::Value::for_value_type::<Self>();
        unsafe {
            glib::gobject_ffi::g_value_set_enum(value.to_glib_none_mut().0, self.into_glib());
        }
        value
    }

    #[inline]
    fn value_type(&self) -> glib::Type {
        Self::static_type()
    }
}

impl From<PanelEdge> for glib::Value {
    #[inline]
    fn from(v: PanelEdge) -> Self {
        skip_assert_initialized!();
        ToValue::to_value(&v)
    }
}

#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Clone, Copy)]
#[non_exhaustive]
#[doc(alias = "AwraRadius")]
pub enum Radius {
    #[doc(alias = "AWRA_RADIUS_SMALL")]
    Small,
    #[doc(alias = "AWRA_RADIUS_MEDIUM")]
    Medium,
    #[doc(alias = "AWRA_RADIUS_LARGE")]
    Large,
    #[doc(alias = "AWRA_RADIUS_WINDOW")]
    Window,
    #[doc(alias = "AWRA_RADIUS_PILL")]
    Pill,
    #[doc(hidden)]
    __Unknown(i32),
}

#[doc(hidden)]
impl IntoGlib for Radius {
    type GlibType = ffi::AwraRadius;

    #[inline]
    fn into_glib(self) -> ffi::AwraRadius {
        match self {
            Self::Small => ffi::AWRA_RADIUS_SMALL,
            Self::Medium => ffi::AWRA_RADIUS_MEDIUM,
            Self::Large => ffi::AWRA_RADIUS_LARGE,
            Self::Window => ffi::AWRA_RADIUS_WINDOW,
            Self::Pill => ffi::AWRA_RADIUS_PILL,
            Self::__Unknown(value) => value,
        }
    }
}

#[doc(hidden)]
impl FromGlib<ffi::AwraRadius> for Radius {
    #[inline]
    unsafe fn from_glib(value: ffi::AwraRadius) -> Self {
        skip_assert_initialized!();

        match value {
            ffi::AWRA_RADIUS_SMALL => Self::Small,
            ffi::AWRA_RADIUS_MEDIUM => Self::Medium,
            ffi::AWRA_RADIUS_LARGE => Self::Large,
            ffi::AWRA_RADIUS_WINDOW => Self::Window,
            ffi::AWRA_RADIUS_PILL => Self::Pill,
            value => Self::__Unknown(value),
        }
    }
}

impl StaticType for Radius {
    #[inline]
    #[doc(alias = "awra_radius_get_type")]
    fn static_type() -> glib::Type {
        unsafe { from_glib(ffi::awra_radius_get_type()) }
    }
}

impl glib::HasParamSpec for Radius {
    type ParamSpec = glib::ParamSpecEnum;
    type SetValue = Self;
    type BuilderFn = fn(&str, Self) -> glib::ParamSpecEnumBuilder<Self>;

    fn param_spec_builder() -> Self::BuilderFn {
        Self::ParamSpec::builder_with_default
    }
}

impl glib::value::ValueType for Radius {
    type Type = Self;
}

unsafe impl<'a> glib::value::FromValue<'a> for Radius {
    type Checker = glib::value::GenericValueTypeChecker<Self>;

    #[inline]
    unsafe fn from_value(value: &'a glib::Value) -> Self {
        skip_assert_initialized!();
        unsafe { from_glib(glib::gobject_ffi::g_value_get_enum(value.to_glib_none().0)) }
    }
}

impl ToValue for Radius {
    #[inline]
    fn to_value(&self) -> glib::Value {
        let mut value = glib::Value::for_value_type::<Self>();
        unsafe {
            glib::gobject_ffi::g_value_set_enum(value.to_glib_none_mut().0, self.into_glib());
        }
        value
    }

    #[inline]
    fn value_type(&self) -> glib::Type {
        Self::static_type()
    }
}

impl From<Radius> for glib::Value {
    #[inline]
    fn from(v: Radius) -> Self {
        skip_assert_initialized!();
        ToValue::to_value(&v)
    }
}

#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Clone, Copy)]
#[non_exhaustive]
#[doc(alias = "AwraSpacing")]
pub enum Spacing {
    #[doc(alias = "AWRA_SPACING_XS")]
    Xs,
    #[doc(alias = "AWRA_SPACING_SM")]
    Sm,
    #[doc(alias = "AWRA_SPACING_MD")]
    Md,
    #[doc(alias = "AWRA_SPACING_LG")]
    Lg,
    #[doc(alias = "AWRA_SPACING_XL")]
    Xl,
    #[doc(alias = "AWRA_SPACING_XXL")]
    Xxl,
    #[doc(alias = "AWRA_SPACING_NONE")]
    None,
    #[doc(hidden)]
    __Unknown(i32),
}

impl Spacing {
    #[doc(alias = "awra_spacing_resolve")]
    pub fn resolve(widget: &impl IsA<gtk::Widget>, spacing: Spacing) -> i32 {
        assert_initialized_main_thread!();
        unsafe { ffi::awra_spacing_resolve(widget.as_ref().to_glib_none().0, spacing.into_glib()) }
    }
}

#[doc(hidden)]
impl IntoGlib for Spacing {
    type GlibType = ffi::AwraSpacing;

    #[inline]
    fn into_glib(self) -> ffi::AwraSpacing {
        match self {
            Self::Xs => ffi::AWRA_SPACING_XS,
            Self::Sm => ffi::AWRA_SPACING_SM,
            Self::Md => ffi::AWRA_SPACING_MD,
            Self::Lg => ffi::AWRA_SPACING_LG,
            Self::Xl => ffi::AWRA_SPACING_XL,
            Self::Xxl => ffi::AWRA_SPACING_XXL,
            Self::None => ffi::AWRA_SPACING_NONE,
            Self::__Unknown(value) => value,
        }
    }
}

#[doc(hidden)]
impl FromGlib<ffi::AwraSpacing> for Spacing {
    #[inline]
    unsafe fn from_glib(value: ffi::AwraSpacing) -> Self {
        skip_assert_initialized!();

        match value {
            ffi::AWRA_SPACING_XS => Self::Xs,
            ffi::AWRA_SPACING_SM => Self::Sm,
            ffi::AWRA_SPACING_MD => Self::Md,
            ffi::AWRA_SPACING_LG => Self::Lg,
            ffi::AWRA_SPACING_XL => Self::Xl,
            ffi::AWRA_SPACING_XXL => Self::Xxl,
            ffi::AWRA_SPACING_NONE => Self::None,
            value => Self::__Unknown(value),
        }
    }
}

impl StaticType for Spacing {
    #[inline]
    #[doc(alias = "awra_spacing_get_type")]
    fn static_type() -> glib::Type {
        unsafe { from_glib(ffi::awra_spacing_get_type()) }
    }
}

impl glib::HasParamSpec for Spacing {
    type ParamSpec = glib::ParamSpecEnum;
    type SetValue = Self;
    type BuilderFn = fn(&str, Self) -> glib::ParamSpecEnumBuilder<Self>;

    fn param_spec_builder() -> Self::BuilderFn {
        Self::ParamSpec::builder_with_default
    }
}

impl glib::value::ValueType for Spacing {
    type Type = Self;
}

unsafe impl<'a> glib::value::FromValue<'a> for Spacing {
    type Checker = glib::value::GenericValueTypeChecker<Self>;

    #[inline]
    unsafe fn from_value(value: &'a glib::Value) -> Self {
        skip_assert_initialized!();
        unsafe { from_glib(glib::gobject_ffi::g_value_get_enum(value.to_glib_none().0)) }
    }
}

impl ToValue for Spacing {
    #[inline]
    fn to_value(&self) -> glib::Value {
        let mut value = glib::Value::for_value_type::<Self>();
        unsafe {
            glib::gobject_ffi::g_value_set_enum(value.to_glib_none_mut().0, self.into_glib());
        }
        value
    }

    #[inline]
    fn value_type(&self) -> glib::Type {
        Self::static_type()
    }
}

impl From<Spacing> for glib::Value {
    #[inline]
    fn from(v: Spacing) -> Self {
        skip_assert_initialized!();
        ToValue::to_value(&v)
    }
}

#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Clone, Copy)]
#[non_exhaustive]
#[doc(alias = "AwraStatusAppearance")]
pub enum StatusAppearance {
    #[doc(alias = "AWRA_STATUS_APPEARANCE_INFO")]
    Info,
    #[doc(alias = "AWRA_STATUS_APPEARANCE_SUCCESS")]
    Success,
    #[doc(alias = "AWRA_STATUS_APPEARANCE_WARNING")]
    Warning,
    #[doc(alias = "AWRA_STATUS_APPEARANCE_ERROR")]
    Error,
    #[doc(hidden)]
    __Unknown(i32),
}

#[doc(hidden)]
impl IntoGlib for StatusAppearance {
    type GlibType = ffi::AwraStatusAppearance;

    #[inline]
    fn into_glib(self) -> ffi::AwraStatusAppearance {
        match self {
            Self::Info => ffi::AWRA_STATUS_APPEARANCE_INFO,
            Self::Success => ffi::AWRA_STATUS_APPEARANCE_SUCCESS,
            Self::Warning => ffi::AWRA_STATUS_APPEARANCE_WARNING,
            Self::Error => ffi::AWRA_STATUS_APPEARANCE_ERROR,
            Self::__Unknown(value) => value,
        }
    }
}

#[doc(hidden)]
impl FromGlib<ffi::AwraStatusAppearance> for StatusAppearance {
    #[inline]
    unsafe fn from_glib(value: ffi::AwraStatusAppearance) -> Self {
        skip_assert_initialized!();

        match value {
            ffi::AWRA_STATUS_APPEARANCE_INFO => Self::Info,
            ffi::AWRA_STATUS_APPEARANCE_SUCCESS => Self::Success,
            ffi::AWRA_STATUS_APPEARANCE_WARNING => Self::Warning,
            ffi::AWRA_STATUS_APPEARANCE_ERROR => Self::Error,
            value => Self::__Unknown(value),
        }
    }
}

impl StaticType for StatusAppearance {
    #[inline]
    #[doc(alias = "awra_status_appearance_get_type")]
    fn static_type() -> glib::Type {
        unsafe { from_glib(ffi::awra_status_appearance_get_type()) }
    }
}

impl glib::HasParamSpec for StatusAppearance {
    type ParamSpec = glib::ParamSpecEnum;
    type SetValue = Self;
    type BuilderFn = fn(&str, Self) -> glib::ParamSpecEnumBuilder<Self>;

    fn param_spec_builder() -> Self::BuilderFn {
        Self::ParamSpec::builder_with_default
    }
}

impl glib::value::ValueType for StatusAppearance {
    type Type = Self;
}

unsafe impl<'a> glib::value::FromValue<'a> for StatusAppearance {
    type Checker = glib::value::GenericValueTypeChecker<Self>;

    #[inline]
    unsafe fn from_value(value: &'a glib::Value) -> Self {
        skip_assert_initialized!();
        unsafe { from_glib(glib::gobject_ffi::g_value_get_enum(value.to_glib_none().0)) }
    }
}

impl ToValue for StatusAppearance {
    #[inline]
    fn to_value(&self) -> glib::Value {
        let mut value = glib::Value::for_value_type::<Self>();
        unsafe {
            glib::gobject_ffi::g_value_set_enum(value.to_glib_none_mut().0, self.into_glib());
        }
        value
    }

    #[inline]
    fn value_type(&self) -> glib::Type {
        Self::static_type()
    }
}

impl From<StatusAppearance> for glib::Value {
    #[inline]
    fn from(v: StatusAppearance) -> Self {
        skip_assert_initialized!();
        ToValue::to_value(&v)
    }
}

#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Clone, Copy)]
#[non_exhaustive]
#[doc(alias = "AwraSurfaceRole")]
pub enum SurfaceRole {
    #[doc(alias = "AWRA_SURFACE_ROLE_WINDOW")]
    Window,
    #[doc(alias = "AWRA_SURFACE_ROLE_CONTENT")]
    Content,
    #[doc(alias = "AWRA_SURFACE_ROLE_SIDEBAR")]
    Sidebar,
    #[doc(alias = "AWRA_SURFACE_ROLE_CARD")]
    Card,
    #[doc(alias = "AWRA_SURFACE_ROLE_TOOLBAR")]
    Toolbar,
    #[doc(alias = "AWRA_SURFACE_ROLE_FLOATING")]
    Floating,
    #[doc(alias = "AWRA_SURFACE_ROLE_POPOVER")]
    Popover,
    #[doc(alias = "AWRA_SURFACE_ROLE_MENU")]
    Menu,
    #[doc(alias = "AWRA_SURFACE_ROLE_DIALOG")]
    Dialog,
    #[doc(alias = "AWRA_SURFACE_ROLE_TOOLTIP")]
    Tooltip,
    #[doc(alias = "AWRA_SURFACE_ROLE_HUD")]
    Hud,
    #[doc(hidden)]
    __Unknown(i32),
}

#[doc(hidden)]
impl IntoGlib for SurfaceRole {
    type GlibType = ffi::AwraSurfaceRole;

    #[inline]
    fn into_glib(self) -> ffi::AwraSurfaceRole {
        match self {
            Self::Window => ffi::AWRA_SURFACE_ROLE_WINDOW,
            Self::Content => ffi::AWRA_SURFACE_ROLE_CONTENT,
            Self::Sidebar => ffi::AWRA_SURFACE_ROLE_SIDEBAR,
            Self::Card => ffi::AWRA_SURFACE_ROLE_CARD,
            Self::Toolbar => ffi::AWRA_SURFACE_ROLE_TOOLBAR,
            Self::Floating => ffi::AWRA_SURFACE_ROLE_FLOATING,
            Self::Popover => ffi::AWRA_SURFACE_ROLE_POPOVER,
            Self::Menu => ffi::AWRA_SURFACE_ROLE_MENU,
            Self::Dialog => ffi::AWRA_SURFACE_ROLE_DIALOG,
            Self::Tooltip => ffi::AWRA_SURFACE_ROLE_TOOLTIP,
            Self::Hud => ffi::AWRA_SURFACE_ROLE_HUD,
            Self::__Unknown(value) => value,
        }
    }
}

#[doc(hidden)]
impl FromGlib<ffi::AwraSurfaceRole> for SurfaceRole {
    #[inline]
    unsafe fn from_glib(value: ffi::AwraSurfaceRole) -> Self {
        skip_assert_initialized!();

        match value {
            ffi::AWRA_SURFACE_ROLE_WINDOW => Self::Window,
            ffi::AWRA_SURFACE_ROLE_CONTENT => Self::Content,
            ffi::AWRA_SURFACE_ROLE_SIDEBAR => Self::Sidebar,
            ffi::AWRA_SURFACE_ROLE_CARD => Self::Card,
            ffi::AWRA_SURFACE_ROLE_TOOLBAR => Self::Toolbar,
            ffi::AWRA_SURFACE_ROLE_FLOATING => Self::Floating,
            ffi::AWRA_SURFACE_ROLE_POPOVER => Self::Popover,
            ffi::AWRA_SURFACE_ROLE_MENU => Self::Menu,
            ffi::AWRA_SURFACE_ROLE_DIALOG => Self::Dialog,
            ffi::AWRA_SURFACE_ROLE_TOOLTIP => Self::Tooltip,
            ffi::AWRA_SURFACE_ROLE_HUD => Self::Hud,
            value => Self::__Unknown(value),
        }
    }
}

impl StaticType for SurfaceRole {
    #[inline]
    #[doc(alias = "awra_surface_role_get_type")]
    fn static_type() -> glib::Type {
        unsafe { from_glib(ffi::awra_surface_role_get_type()) }
    }
}

impl glib::HasParamSpec for SurfaceRole {
    type ParamSpec = glib::ParamSpecEnum;
    type SetValue = Self;
    type BuilderFn = fn(&str, Self) -> glib::ParamSpecEnumBuilder<Self>;

    fn param_spec_builder() -> Self::BuilderFn {
        Self::ParamSpec::builder_with_default
    }
}

impl glib::value::ValueType for SurfaceRole {
    type Type = Self;
}

unsafe impl<'a> glib::value::FromValue<'a> for SurfaceRole {
    type Checker = glib::value::GenericValueTypeChecker<Self>;

    #[inline]
    unsafe fn from_value(value: &'a glib::Value) -> Self {
        skip_assert_initialized!();
        unsafe { from_glib(glib::gobject_ffi::g_value_get_enum(value.to_glib_none().0)) }
    }
}

impl ToValue for SurfaceRole {
    #[inline]
    fn to_value(&self) -> glib::Value {
        let mut value = glib::Value::for_value_type::<Self>();
        unsafe {
            glib::gobject_ffi::g_value_set_enum(value.to_glib_none_mut().0, self.into_glib());
        }
        value
    }

    #[inline]
    fn value_type(&self) -> glib::Type {
        Self::static_type()
    }
}

impl From<SurfaceRole> for glib::Value {
    #[inline]
    fn from(v: SurfaceRole) -> Self {
        skip_assert_initialized!();
        ToValue::to_value(&v)
    }
}

#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Clone, Copy)]
#[non_exhaustive]
#[doc(alias = "AwraTypography")]
pub enum Typography {
    #[doc(alias = "AWRA_TYPOGRAPHY_BODY")]
    Body,
    #[doc(alias = "AWRA_TYPOGRAPHY_MUTED")]
    Muted,
    #[doc(alias = "AWRA_TYPOGRAPHY_EYEBROW")]
    Eyebrow,
    #[doc(alias = "AWRA_TYPOGRAPHY_TITLE_3")]
    Title3,
    #[doc(alias = "AWRA_TYPOGRAPHY_TITLE_2")]
    Title2,
    #[doc(alias = "AWRA_TYPOGRAPHY_TITLE_1")]
    Title1,
    #[doc(alias = "AWRA_TYPOGRAPHY_DISPLAY")]
    Display,
    #[doc(alias = "AWRA_TYPOGRAPHY_MONOSPACE")]
    Monospace,
    #[doc(hidden)]
    __Unknown(i32),
}

#[doc(hidden)]
impl IntoGlib for Typography {
    type GlibType = ffi::AwraTypography;

    #[inline]
    fn into_glib(self) -> ffi::AwraTypography {
        match self {
            Self::Body => ffi::AWRA_TYPOGRAPHY_BODY,
            Self::Muted => ffi::AWRA_TYPOGRAPHY_MUTED,
            Self::Eyebrow => ffi::AWRA_TYPOGRAPHY_EYEBROW,
            Self::Title3 => ffi::AWRA_TYPOGRAPHY_TITLE_3,
            Self::Title2 => ffi::AWRA_TYPOGRAPHY_TITLE_2,
            Self::Title1 => ffi::AWRA_TYPOGRAPHY_TITLE_1,
            Self::Display => ffi::AWRA_TYPOGRAPHY_DISPLAY,
            Self::Monospace => ffi::AWRA_TYPOGRAPHY_MONOSPACE,
            Self::__Unknown(value) => value,
        }
    }
}

#[doc(hidden)]
impl FromGlib<ffi::AwraTypography> for Typography {
    #[inline]
    unsafe fn from_glib(value: ffi::AwraTypography) -> Self {
        skip_assert_initialized!();

        match value {
            ffi::AWRA_TYPOGRAPHY_BODY => Self::Body,
            ffi::AWRA_TYPOGRAPHY_MUTED => Self::Muted,
            ffi::AWRA_TYPOGRAPHY_EYEBROW => Self::Eyebrow,
            ffi::AWRA_TYPOGRAPHY_TITLE_3 => Self::Title3,
            ffi::AWRA_TYPOGRAPHY_TITLE_2 => Self::Title2,
            ffi::AWRA_TYPOGRAPHY_TITLE_1 => Self::Title1,
            ffi::AWRA_TYPOGRAPHY_DISPLAY => Self::Display,
            ffi::AWRA_TYPOGRAPHY_MONOSPACE => Self::Monospace,
            value => Self::__Unknown(value),
        }
    }
}

impl StaticType for Typography {
    #[inline]
    #[doc(alias = "awra_typography_get_type")]
    fn static_type() -> glib::Type {
        unsafe { from_glib(ffi::awra_typography_get_type()) }
    }
}

impl glib::HasParamSpec for Typography {
    type ParamSpec = glib::ParamSpecEnum;
    type SetValue = Self;
    type BuilderFn = fn(&str, Self) -> glib::ParamSpecEnumBuilder<Self>;

    fn param_spec_builder() -> Self::BuilderFn {
        Self::ParamSpec::builder_with_default
    }
}

impl glib::value::ValueType for Typography {
    type Type = Self;
}

unsafe impl<'a> glib::value::FromValue<'a> for Typography {
    type Checker = glib::value::GenericValueTypeChecker<Self>;

    #[inline]
    unsafe fn from_value(value: &'a glib::Value) -> Self {
        skip_assert_initialized!();
        unsafe { from_glib(glib::gobject_ffi::g_value_get_enum(value.to_glib_none().0)) }
    }
}

impl ToValue for Typography {
    #[inline]
    fn to_value(&self) -> glib::Value {
        let mut value = glib::Value::for_value_type::<Self>();
        unsafe {
            glib::gobject_ffi::g_value_set_enum(value.to_glib_none_mut().0, self.into_glib());
        }
        value
    }

    #[inline]
    fn value_type(&self) -> glib::Type {
        Self::static_type()
    }
}

impl From<Typography> for glib::Value {
    #[inline]
    fn from(v: Typography) -> Self {
        skip_assert_initialized!();
        ToValue::to_value(&v)
    }
}

#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Clone, Copy)]
#[non_exhaustive]
#[doc(alias = "AwraValidationState")]
pub enum ValidationState {
    #[doc(alias = "AWRA_VALIDATION_STATE_NONE")]
    None,
    #[doc(alias = "AWRA_VALIDATION_STATE_SUCCESS")]
    Success,
    #[doc(alias = "AWRA_VALIDATION_STATE_WARNING")]
    Warning,
    #[doc(alias = "AWRA_VALIDATION_STATE_ERROR")]
    Error,
    #[doc(hidden)]
    __Unknown(i32),
}

#[doc(hidden)]
impl IntoGlib for ValidationState {
    type GlibType = ffi::AwraValidationState;

    #[inline]
    fn into_glib(self) -> ffi::AwraValidationState {
        match self {
            Self::None => ffi::AWRA_VALIDATION_STATE_NONE,
            Self::Success => ffi::AWRA_VALIDATION_STATE_SUCCESS,
            Self::Warning => ffi::AWRA_VALIDATION_STATE_WARNING,
            Self::Error => ffi::AWRA_VALIDATION_STATE_ERROR,
            Self::__Unknown(value) => value,
        }
    }
}

#[doc(hidden)]
impl FromGlib<ffi::AwraValidationState> for ValidationState {
    #[inline]
    unsafe fn from_glib(value: ffi::AwraValidationState) -> Self {
        skip_assert_initialized!();

        match value {
            ffi::AWRA_VALIDATION_STATE_NONE => Self::None,
            ffi::AWRA_VALIDATION_STATE_SUCCESS => Self::Success,
            ffi::AWRA_VALIDATION_STATE_WARNING => Self::Warning,
            ffi::AWRA_VALIDATION_STATE_ERROR => Self::Error,
            value => Self::__Unknown(value),
        }
    }
}

impl StaticType for ValidationState {
    #[inline]
    #[doc(alias = "awra_validation_state_get_type")]
    fn static_type() -> glib::Type {
        unsafe { from_glib(ffi::awra_validation_state_get_type()) }
    }
}

impl glib::HasParamSpec for ValidationState {
    type ParamSpec = glib::ParamSpecEnum;
    type SetValue = Self;
    type BuilderFn = fn(&str, Self) -> glib::ParamSpecEnumBuilder<Self>;

    fn param_spec_builder() -> Self::BuilderFn {
        Self::ParamSpec::builder_with_default
    }
}

impl glib::value::ValueType for ValidationState {
    type Type = Self;
}

unsafe impl<'a> glib::value::FromValue<'a> for ValidationState {
    type Checker = glib::value::GenericValueTypeChecker<Self>;

    #[inline]
    unsafe fn from_value(value: &'a glib::Value) -> Self {
        skip_assert_initialized!();
        unsafe { from_glib(glib::gobject_ffi::g_value_get_enum(value.to_glib_none().0)) }
    }
}

impl ToValue for ValidationState {
    #[inline]
    fn to_value(&self) -> glib::Value {
        let mut value = glib::Value::for_value_type::<Self>();
        unsafe {
            glib::gobject_ffi::g_value_set_enum(value.to_glib_none_mut().0, self.into_glib());
        }
        value
    }

    #[inline]
    fn value_type(&self) -> glib::Type {
        Self::static_type()
    }
}

impl From<ValidationState> for glib::Value {
    #[inline]
    fn from(v: ValidationState) -> Self {
        skip_assert_initialized!();
        ToValue::to_value(&v)
    }
}
