// This file was generated by gir (https://github.com/gtk-rs/gir)
// from build
// from subprojects/gir-files
// DO NOT EDIT

use crate::ffi;
use glib::{bitflags::bitflags, prelude::*, translate::*};

bitflags! {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
    #[doc(alias = "AwraEffectCapability")]
    pub struct EffectCapability: u32 {
        #[doc(alias = "AWRA_EFFECT_CAPABILITY_NONE")]
        const NONE = ffi::AWRA_EFFECT_CAPABILITY_NONE as _;
        #[doc(alias = "AWRA_EFFECT_CAPABILITY_BLUR")]
        const BLUR = ffi::AWRA_EFFECT_CAPABILITY_BLUR as _;
    }
}

#[doc(hidden)]
impl IntoGlib for EffectCapability {
    type GlibType = ffi::AwraEffectCapability;

    #[inline]
    fn into_glib(self) -> ffi::AwraEffectCapability {
        self.bits()
    }
}

#[doc(hidden)]
impl FromGlib<ffi::AwraEffectCapability> for EffectCapability {
    #[inline]
    unsafe fn from_glib(value: ffi::AwraEffectCapability) -> Self {
        skip_assert_initialized!();
        Self::from_bits_truncate(value)
    }
}

impl StaticType for EffectCapability {
    #[inline]
    #[doc(alias = "awra_effect_capability_get_type")]
    fn static_type() -> glib::Type {
        unsafe { from_glib(ffi::awra_effect_capability_get_type()) }
    }
}

impl glib::HasParamSpec for EffectCapability {
    type ParamSpec = glib::ParamSpecFlags;
    type SetValue = Self;
    type BuilderFn = fn(&str) -> glib::ParamSpecFlagsBuilder<Self>;

    fn param_spec_builder() -> Self::BuilderFn {
        Self::ParamSpec::builder
    }
}

impl glib::value::ValueType for EffectCapability {
    type Type = Self;
}

unsafe impl<'a> glib::value::FromValue<'a> for EffectCapability {
    type Checker = glib::value::GenericValueTypeChecker<Self>;

    #[inline]
    unsafe fn from_value(value: &'a glib::Value) -> Self {
        skip_assert_initialized!();
        unsafe { from_glib(glib::gobject_ffi::g_value_get_flags(value.to_glib_none().0)) }
    }
}

impl ToValue for EffectCapability {
    #[inline]
    fn to_value(&self) -> glib::Value {
        let mut value = glib::Value::for_value_type::<Self>();
        unsafe {
            glib::gobject_ffi::g_value_set_flags(value.to_glib_none_mut().0, self.into_glib());
        }
        value
    }

    #[inline]
    fn value_type(&self) -> glib::Type {
        Self::static_type()
    }
}

impl From<EffectCapability> for glib::Value {
    #[inline]
    fn from(v: EffectCapability) -> Self {
        skip_assert_initialized!();
        ToValue::to_value(&v)
    }
}

bitflags! {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
    #[doc(alias = "AwraSurfaceCorner")]
    pub struct SurfaceCorner: u32 {
        #[doc(alias = "AWRA_SURFACE_CORNER_NONE")]
        const NONE = ffi::AWRA_SURFACE_CORNER_NONE as _;
        #[doc(alias = "AWRA_SURFACE_CORNER_TOP_START")]
        const TOP_START = ffi::AWRA_SURFACE_CORNER_TOP_START as _;
        #[doc(alias = "AWRA_SURFACE_CORNER_TOP_END")]
        const TOP_END = ffi::AWRA_SURFACE_CORNER_TOP_END as _;
        #[doc(alias = "AWRA_SURFACE_CORNER_BOTTOM_END")]
        const BOTTOM_END = ffi::AWRA_SURFACE_CORNER_BOTTOM_END as _;
        #[doc(alias = "AWRA_SURFACE_CORNER_BOTTOM_START")]
        const BOTTOM_START = ffi::AWRA_SURFACE_CORNER_BOTTOM_START as _;
        #[doc(alias = "AWRA_SURFACE_CORNER_ALL")]
        const ALL = ffi::AWRA_SURFACE_CORNER_ALL as _;
    }
}

#[doc(hidden)]
impl IntoGlib for SurfaceCorner {
    type GlibType = ffi::AwraSurfaceCorner;

    #[inline]
    fn into_glib(self) -> ffi::AwraSurfaceCorner {
        self.bits()
    }
}

#[doc(hidden)]
impl FromGlib<ffi::AwraSurfaceCorner> for SurfaceCorner {
    #[inline]
    unsafe fn from_glib(value: ffi::AwraSurfaceCorner) -> Self {
        skip_assert_initialized!();
        Self::from_bits_truncate(value)
    }
}

impl StaticType for SurfaceCorner {
    #[inline]
    #[doc(alias = "awra_surface_corner_get_type")]
    fn static_type() -> glib::Type {
        unsafe { from_glib(ffi::awra_surface_corner_get_type()) }
    }
}

impl glib::HasParamSpec for SurfaceCorner {
    type ParamSpec = glib::ParamSpecFlags;
    type SetValue = Self;
    type BuilderFn = fn(&str) -> glib::ParamSpecFlagsBuilder<Self>;

    fn param_spec_builder() -> Self::BuilderFn {
        Self::ParamSpec::builder
    }
}

impl glib::value::ValueType for SurfaceCorner {
    type Type = Self;
}

unsafe impl<'a> glib::value::FromValue<'a> for SurfaceCorner {
    type Checker = glib::value::GenericValueTypeChecker<Self>;

    #[inline]
    unsafe fn from_value(value: &'a glib::Value) -> Self {
        skip_assert_initialized!();
        unsafe { from_glib(glib::gobject_ffi::g_value_get_flags(value.to_glib_none().0)) }
    }
}

impl ToValue for SurfaceCorner {
    #[inline]
    fn to_value(&self) -> glib::Value {
        let mut value = glib::Value::for_value_type::<Self>();
        unsafe {
            glib::gobject_ffi::g_value_set_flags(value.to_glib_none_mut().0, self.into_glib());
        }
        value
    }

    #[inline]
    fn value_type(&self) -> glib::Type {
        Self::static_type()
    }
}

impl From<SurfaceCorner> for glib::Value {
    #[inline]
    fn from(v: SurfaceCorner) -> Self {
        skip_assert_initialized!();
        ToValue::to_value(&v)
    }
}

bitflags! {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
    #[doc(alias = "AwraSurfaceEdge")]
    pub struct SurfaceEdge: u32 {
        #[doc(alias = "AWRA_SURFACE_EDGE_NONE")]
        const NONE = ffi::AWRA_SURFACE_EDGE_NONE as _;
        #[doc(alias = "AWRA_SURFACE_EDGE_TOP")]
        const TOP = ffi::AWRA_SURFACE_EDGE_TOP as _;
        #[doc(alias = "AWRA_SURFACE_EDGE_END")]
        const END = ffi::AWRA_SURFACE_EDGE_END as _;
        #[doc(alias = "AWRA_SURFACE_EDGE_BOTTOM")]
        const BOTTOM = ffi::AWRA_SURFACE_EDGE_BOTTOM as _;
        #[doc(alias = "AWRA_SURFACE_EDGE_START")]
        const START = ffi::AWRA_SURFACE_EDGE_START as _;
        #[doc(alias = "AWRA_SURFACE_EDGE_ALL")]
        const ALL = ffi::AWRA_SURFACE_EDGE_ALL as _;
    }
}

#[doc(hidden)]
impl IntoGlib for SurfaceEdge {
    type GlibType = ffi::AwraSurfaceEdge;

    #[inline]
    fn into_glib(self) -> ffi::AwraSurfaceEdge {
        self.bits()
    }
}

#[doc(hidden)]
impl FromGlib<ffi::AwraSurfaceEdge> for SurfaceEdge {
    #[inline]
    unsafe fn from_glib(value: ffi::AwraSurfaceEdge) -> Self {
        skip_assert_initialized!();
        Self::from_bits_truncate(value)
    }
}

impl StaticType for SurfaceEdge {
    #[inline]
    #[doc(alias = "awra_surface_edge_get_type")]
    fn static_type() -> glib::Type {
        unsafe { from_glib(ffi::awra_surface_edge_get_type()) }
    }
}

impl glib::HasParamSpec for SurfaceEdge {
    type ParamSpec = glib::ParamSpecFlags;
    type SetValue = Self;
    type BuilderFn = fn(&str) -> glib::ParamSpecFlagsBuilder<Self>;

    fn param_spec_builder() -> Self::BuilderFn {
        Self::ParamSpec::builder
    }
}

impl glib::value::ValueType for SurfaceEdge {
    type Type = Self;
}

unsafe impl<'a> glib::value::FromValue<'a> for SurfaceEdge {
    type Checker = glib::value::GenericValueTypeChecker<Self>;

    #[inline]
    unsafe fn from_value(value: &'a glib::Value) -> Self {
        skip_assert_initialized!();
        unsafe { from_glib(glib::gobject_ffi::g_value_get_flags(value.to_glib_none().0)) }
    }
}

impl ToValue for SurfaceEdge {
    #[inline]
    fn to_value(&self) -> glib::Value {
        let mut value = glib::Value::for_value_type::<Self>();
        unsafe {
            glib::gobject_ffi::g_value_set_flags(value.to_glib_none_mut().0, self.into_glib());
        }
        value
    }

    #[inline]
    fn value_type(&self) -> glib::Type {
        Self::static_type()
    }
}

impl From<SurfaceEdge> for glib::Value {
    #[inline]
    fn from(v: SurfaceEdge) -> Self {
        skip_assert_initialized!();
        ToValue::to_value(&v)
    }
}
