// This file was generated by gir (https://github.com/gtk-rs/gir)
// from build
// from subprojects/gir-files
// DO NOT EDIT

use crate::{ffi, ValidationState};
use glib::{
    prelude::*,
    signal::{connect_raw, SignalHandlerId},
    translate::*,
};
use std::boxed::Box as Box_;

#[cfg(feature = "gtk_v4_10")]
#[cfg_attr(docsrs, doc(cfg(feature = "gtk_v4_10")))]
glib::wrapper! {
    #[doc(alias = "AwraFormRow")]
    pub struct FormRow(Object<ffi::AwraFormRow, ffi::AwraFormRowClass>) @extends gtk::Widget, gobject::InitiallyUnowned, @implements gtk::Accessible, gtk::Buildable, gtk::ConstraintTarget;

    match fn {
        type_ => || ffi::awra_form_row_get_type(),
    }
}

#[cfg(not(feature = "gtk_v4_10"))]
glib::wrapper! {
    #[doc(alias = "AwraFormRow")]
    pub struct FormRow(Object<ffi::AwraFormRow, ffi::AwraFormRowClass>) @extends gtk::Widget, gobject::InitiallyUnowned, @implements gtk::Buildable, gtk::ConstraintTarget;

    match fn {
        type_ => || ffi::awra_form_row_get_type(),
    }
}

impl FormRow {
    #[doc(alias = "awra_form_row_new")]
    pub fn new() -> FormRow {
        assert_initialized_main_thread!();
        unsafe { gtk::Widget::from_glib_none(ffi::awra_form_row_new()).unsafe_cast() }
    }

    // rustdoc-stripper-ignore-next
    /// Creates a new builder-pattern struct instance to construct [`FormRow`] objects.
    ///
    /// This method returns an instance of [`FormRowBuilder`](crate::builders::FormRowBuilder) which can be used to create [`FormRow`] objects.
    pub fn builder() -> FormRowBuilder {
        FormRowBuilder::new()
    }

    #[doc(alias = "awra_form_row_get_control")]
    #[doc(alias = "get_control")]
    pub fn control(&self) -> Option<gtk::Widget> {
        unsafe { from_glib_none(ffi::awra_form_row_get_control(self.to_glib_none().0)) }
    }

    #[doc(alias = "awra_form_row_get_error_message")]
    #[doc(alias = "get_error_message")]
    #[doc(alias = "error-message")]
    pub fn error_message(&self) -> Option<glib::GString> {
        unsafe { from_glib_none(ffi::awra_form_row_get_error_message(self.to_glib_none().0)) }
    }

    #[doc(alias = "awra_form_row_get_help_text")]
    #[doc(alias = "get_help_text")]
    #[doc(alias = "help-text")]
    pub fn help_text(&self) -> Option<glib::GString> {
        unsafe { from_glib_none(ffi::awra_form_row_get_help_text(self.to_glib_none().0)) }
    }

    #[doc(alias = "awra_form_row_get_label")]
    #[doc(alias = "get_label")]
    pub fn label(&self) -> Option<glib::GString> {
        unsafe { from_glib_none(ffi::awra_form_row_get_label(self.to_glib_none().0)) }
    }

    #[doc(alias = "awra_form_row_get_required")]
    #[doc(alias = "get_required")]
    #[doc(alias = "required")]
    pub fn is_required(&self) -> bool {
        unsafe { from_glib(ffi::awra_form_row_get_required(self.to_glib_none().0)) }
    }

    #[doc(alias = "awra_form_row_get_validation_state")]
    #[doc(alias = "get_validation_state")]
    #[doc(alias = "validation-state")]
    pub fn validation_state(&self) -> ValidationState {
        unsafe {
            from_glib(ffi::awra_form_row_get_validation_state(
                self.to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "awra_form_row_set_control")]
    #[doc(alias = "control")]
    pub fn set_control(&self, control: Option<&impl IsA<gtk::Widget>>) {
        unsafe {
            ffi::awra_form_row_set_control(
                self.to_glib_none().0,
                control.map(|p| p.as_ref()).to_glib_none().0,
            );
        }
    }

    #[doc(alias = "awra_form_row_set_error_message")]
    #[doc(alias = "error-message")]
    pub fn set_error_message(&self, message: Option<&str>) {
        unsafe {
            ffi::awra_form_row_set_error_message(self.to_glib_none().0, message.to_glib_none().0);
        }
    }

    #[doc(alias = "awra_form_row_set_help_text")]
    #[doc(alias = "help-text")]
    pub fn set_help_text(&self, help_text: Option<&str>) {
        unsafe {
            ffi::awra_form_row_set_help_text(self.to_glib_none().0, help_text.to_glib_none().0);
        }
    }

    #[doc(alias = "awra_form_row_set_label")]
    #[doc(alias = "label")]
    pub fn set_label(&self, label: Option<&str>) {
        unsafe {
            ffi::awra_form_row_set_label(self.to_glib_none().0, label.to_glib_none().0);
        }
    }

    #[doc(alias = "awra_form_row_set_required")]
    #[doc(alias = "required")]
    pub fn set_required(&self, required: bool) {
        unsafe {
            ffi::awra_form_row_set_required(self.to_glib_none().0, required.into_glib());
        }
    }

    #[doc(alias = "awra_form_row_set_validation_state")]
    #[doc(alias = "validation-state")]
    pub fn set_validation_state(&self, state: ValidationState) {
        unsafe {
            ffi::awra_form_row_set_validation_state(self.to_glib_none().0, state.into_glib());
        }
    }

    #[doc(alias = "control")]
    pub fn connect_control_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_control_trampoline<F: Fn(&FormRow) + 'static>(
            this: *mut ffi::AwraFormRow,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::control".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_control_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "error-message")]
    pub fn connect_error_message_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_error_message_trampoline<F: Fn(&FormRow) + 'static>(
            this: *mut ffi::AwraFormRow,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::error-message".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_error_message_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "help-text")]
    pub fn connect_help_text_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_help_text_trampoline<F: Fn(&FormRow) + 'static>(
            this: *mut ffi::AwraFormRow,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::help-text".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_help_text_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "label")]
    pub fn connect_label_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_label_trampoline<F: Fn(&FormRow) + 'static>(
            this: *mut ffi::AwraFormRow,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::label".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_label_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "required")]
    pub fn connect_required_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_required_trampoline<F: Fn(&FormRow) + 'static>(
            this: *mut ffi::AwraFormRow,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::required".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_required_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "validation-state")]
    pub fn connect_validation_state_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_validation_state_trampoline<F: Fn(&FormRow) + 'static>(
            this: *mut ffi::AwraFormRow,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::validation-state".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_validation_state_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }
}

impl Default for FormRow {
    fn default() -> Self {
        Self::new()
    }
}

// rustdoc-stripper-ignore-next
/// A [builder-pattern] type to construct [`FormRow`] objects.
///
/// [builder-pattern]: https://doc.rust-lang.org/1.0.0/style/ownership/builders.html
#[must_use = "The builder must be built to be used"]
pub struct FormRowBuilder {
    builder: glib::object::ObjectBuilder<'static, FormRow>,
}

impl FormRowBuilder {
    fn new() -> Self {
        Self {
            builder: glib::object::Object::builder(),
        }
    }

    pub fn control(self, control: &impl IsA<gtk::Widget>) -> Self {
        Self {
            builder: self.builder.property("control", control.clone().upcast()),
        }
    }

    pub fn error_message(self, error_message: impl Into<glib::GString>) -> Self {
        Self {
            builder: self.builder.property("error-message", error_message.into()),
        }
    }

    pub fn help_text(self, help_text: impl Into<glib::GString>) -> Self {
        Self {
            builder: self.builder.property("help-text", help_text.into()),
        }
    }

    pub fn label(self, label: impl Into<glib::GString>) -> Self {
        Self {
            builder: self.builder.property("label", label.into()),
        }
    }

    pub fn required(self, required: bool) -> Self {
        Self {
            builder: self.builder.property("required", required),
        }
    }

    pub fn validation_state(self, validation_state: ValidationState) -> Self {
        Self {
            builder: self.builder.property("validation-state", validation_state),
        }
    }

    pub fn can_focus(self, can_focus: bool) -> Self {
        Self {
            builder: self.builder.property("can-focus", can_focus),
        }
    }

    pub fn can_target(self, can_target: bool) -> Self {
        Self {
            builder: self.builder.property("can-target", can_target),
        }
    }

    pub fn css_classes(self, css_classes: impl Into<glib::StrV>) -> Self {
        Self {
            builder: self.builder.property("css-classes", css_classes.into()),
        }
    }

    pub fn css_name(self, css_name: impl Into<glib::GString>) -> Self {
        Self {
            builder: self.builder.property("css-name", css_name.into()),
        }
    }

    //pub fn cursor(self, cursor: /*Ignored*/&gdk::Cursor) -> Self {
    //    Self { builder: self.builder.property("cursor", cursor), }
    //}

    pub fn focus_on_click(self, focus_on_click: bool) -> Self {
        Self {
            builder: self.builder.property("focus-on-click", focus_on_click),
        }
    }

    pub fn focusable(self, focusable: bool) -> Self {
        Self {
            builder: self.builder.property("focusable", focusable),
        }
    }

    pub fn halign(self, halign: gtk::Align) -> Self {
        Self {
            builder: self.builder.property("halign", halign),
        }
    }

    pub fn has_tooltip(self, has_tooltip: bool) -> Self {
        Self {
            builder: self.builder.property("has-tooltip", has_tooltip),
        }
    }

    pub fn height_request(self, height_request: i32) -> Self {
        Self {
            builder: self.builder.property("height-request", height_request),
        }
    }

    pub fn hexpand(self, hexpand: bool) -> Self {
        Self {
            builder: self.builder.property("hexpand", hexpand),
        }
    }

    pub fn hexpand_set(self, hexpand_set: bool) -> Self {
        Self {
            builder: self.builder.property("hexpand-set", hexpand_set),
        }
    }

    //pub fn layout_manager(self, layout_manager: &impl IsA</*Ignored*/gtk::LayoutManager>) -> Self {
    //    Self { builder: self.builder.property("layout-manager", layout_manager.clone().upcast()), }
    //}

    #[cfg(feature = "gtk_v4_18")]
    #[cfg_attr(docsrs, doc(cfg(feature = "gtk_v4_18")))]
    pub fn limit_events(self, limit_events: bool) -> Self {
        Self {
            builder: self.builder.property("limit-events", limit_events),
        }
    }

    pub fn margin_bottom(self, margin_bottom: i32) -> Self {
        Self {
            builder: self.builder.property("margin-bottom", margin_bottom),
        }
    }

    pub fn margin_end(self, margin_end: i32) -> Self {
        Self {
            builder: self.builder.property("margin-end", margin_end),
        }
    }

    pub fn margin_start(self, margin_start: i32) -> Self {
        Self {
            builder: self.builder.property("margin-start", margin_start),
        }
    }

    pub fn margin_top(self, margin_top: i32) -> Self {
        Self {
            builder: self.builder.property("margin-top", margin_top),
        }
    }

    pub fn name(self, name: impl Into<glib::GString>) -> Self {
        Self {
            builder: self.builder.property("name", name.into()),
        }
    }

    pub fn opacity(self, opacity: f64) -> Self {
        Self {
            builder: self.builder.property("opacity", opacity),
        }
    }

    //pub fn overflow(self, overflow: /*Ignored*/gtk::Overflow) -> Self {
    //    Self { builder: self.builder.property("overflow", overflow), }
    //}

    pub fn receives_default(self, receives_default: bool) -> Self {
        Self {
            builder: self.builder.property("receives-default", receives_default),
        }
    }

    pub fn sensitive(self, sensitive: bool) -> Self {
        Self {
            builder: self.builder.property("sensitive", sensitive),
        }
    }

    pub fn tooltip_markup(self, tooltip_markup: impl Into<glib::GString>) -> Self {
        Self {
            builder: self
                .builder
                .property("tooltip-markup", tooltip_markup.into()),
        }
    }

    pub fn tooltip_text(self, tooltip_text: impl Into<glib::GString>) -> Self {
        Self {
            builder: self.builder.property("tooltip-text", tooltip_text.into()),
        }
    }

    pub fn valign(self, valign: gtk::Align) -> Self {
        Self {
            builder: self.builder.property("valign", valign),
        }
    }

    pub fn vexpand(self, vexpand: bool) -> Self {
        Self {
            builder: self.builder.property("vexpand", vexpand),
        }
    }

    pub fn vexpand_set(self, vexpand_set: bool) -> Self {
        Self {
            builder: self.builder.property("vexpand-set", vexpand_set),
        }
    }

    pub fn visible(self, visible: bool) -> Self {
        Self {
            builder: self.builder.property("visible", visible),
        }
    }

    pub fn width_request(self, width_request: i32) -> Self {
        Self {
            builder: self.builder.property("width-request", width_request),
        }
    }

    //pub fn accessible_role(self, accessible_role: /*Ignored*/gtk::AccessibleRole) -> Self {
    //    Self { builder: self.builder.property("accessible-role", accessible_role), }
    //}

    // rustdoc-stripper-ignore-next
    /// Build the [`FormRow`].
    #[must_use = "Building the object from the builder is usually expensive and is not expected to have side effects"]
    pub fn build(self) -> FormRow {
        assert_initialized_main_thread!();
        self.builder.build()
    }
}
