// This file was generated by gir (https://github.com/gtk-rs/gir)
// from build
// from subprojects/gir-files
// DO NOT EDIT

use crate::{ffi, SurfaceEdge};
use glib::{
    prelude::*,
    signal::{connect_raw, SignalHandlerId},
    translate::*,
};
use std::boxed::Box as Box_;

glib::wrapper! {
    #[doc(alias = "AwraMaterialResolution")]
    pub struct MaterialResolution(Object<ffi::AwraMaterialResolution, ffi::AwraMaterialResolutionClass>);

    match fn {
        type_ => || ffi::awra_material_resolution_get_type(),
    }
}

impl MaterialResolution {
    #[doc(alias = "awra_material_resolution_get_border")]
    #[doc(alias = "get_border")]
    pub fn border(&self) -> gdk::RGBA {
        unsafe {
            from_glib_none(ffi::awra_material_resolution_get_border(
                self.to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "awra_material_resolution_get_border_edges")]
    #[doc(alias = "get_border_edges")]
    #[doc(alias = "border-edges")]
    pub fn border_edges(&self) -> SurfaceEdge {
        unsafe {
            from_glib(ffi::awra_material_resolution_get_border_edges(
                self.to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "awra_material_resolution_get_border_width")]
    #[doc(alias = "get_border_width")]
    #[doc(alias = "border-width")]
    pub fn border_width(&self) -> f64 {
        unsafe { ffi::awra_material_resolution_get_border_width(self.to_glib_none().0) }
    }

    #[doc(alias = "awra_material_resolution_get_fallback")]
    #[doc(alias = "get_fallback")]
    #[doc(alias = "fallback")]
    pub fn is_fallback(&self) -> bool {
        unsafe {
            from_glib(ffi::awra_material_resolution_get_fallback(
                self.to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "awra_material_resolution_get_fill")]
    #[doc(alias = "get_fill")]
    pub fn fill(&self) -> gdk::RGBA {
        unsafe {
            from_glib_none(ffi::awra_material_resolution_get_fill(
                self.to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "awra_material_resolution_get_highlight")]
    #[doc(alias = "get_highlight")]
    pub fn highlight(&self) -> gdk::RGBA {
        unsafe {
            from_glib_none(ffi::awra_material_resolution_get_highlight(
                self.to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "awra_material_resolution_get_radius")]
    #[doc(alias = "get_radius")]
    pub fn radius(&self) -> f64 {
        unsafe { ffi::awra_material_resolution_get_radius(self.to_glib_none().0) }
    }

    #[doc(alias = "awra_material_resolution_get_request_blur")]
    #[doc(alias = "get_request_blur")]
    #[doc(alias = "request-blur")]
    pub fn is_request_blur(&self) -> bool {
        unsafe {
            from_glib(ffi::awra_material_resolution_get_request_blur(
                self.to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "awra_material_resolution_get_shadow")]
    #[doc(alias = "get_shadow")]
    pub fn shadow(&self) -> gdk::RGBA {
        unsafe {
            from_glib_none(ffi::awra_material_resolution_get_shadow(
                self.to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "border")]
    pub fn connect_border_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_border_trampoline<F: Fn(&MaterialResolution) + 'static>(
            this: *mut ffi::AwraMaterialResolution,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::border".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_border_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "border-edges")]
    pub fn connect_border_edges_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_border_edges_trampoline<
            F: Fn(&MaterialResolution) + 'static,
        >(
            this: *mut ffi::AwraMaterialResolution,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::border-edges".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_border_edges_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "border-width")]
    pub fn connect_border_width_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_border_width_trampoline<
            F: Fn(&MaterialResolution) + 'static,
        >(
            this: *mut ffi::AwraMaterialResolution,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::border-width".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_border_width_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "fallback")]
    pub fn connect_fallback_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_fallback_trampoline<F: Fn(&MaterialResolution) + 'static>(
            this: *mut ffi::AwraMaterialResolution,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::fallback".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_fallback_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "fill")]
    pub fn connect_fill_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_fill_trampoline<F: Fn(&MaterialResolution) + 'static>(
            this: *mut ffi::AwraMaterialResolution,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::fill".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_fill_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "highlight")]
    pub fn connect_highlight_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_highlight_trampoline<F: Fn(&MaterialResolution) + 'static>(
            this: *mut ffi::AwraMaterialResolution,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::highlight".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_highlight_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "radius")]
    pub fn connect_radius_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_radius_trampoline<F: Fn(&MaterialResolution) + 'static>(
            this: *mut ffi::AwraMaterialResolution,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::radius".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_radius_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "request-blur")]
    pub fn connect_request_blur_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_request_blur_trampoline<
            F: Fn(&MaterialResolution) + 'static,
        >(
            this: *mut ffi::AwraMaterialResolution,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::request-blur".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_request_blur_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "shadow")]
    pub fn connect_shadow_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_shadow_trampoline<F: Fn(&MaterialResolution) + 'static>(
            this: *mut ffi::AwraMaterialResolution,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::shadow".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_shadow_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }
}
