// This file was generated by gir (https://github.com/gtk-rs/gir)
// from build
// from subprojects/gir-files
// DO NOT EDIT

use crate::{ffi, AccentSource, Appearance, Material, TokenSet};
use glib::{
    prelude::*,
    signal::{connect_raw, SignalHandlerId},
    translate::*,
};
use std::boxed::Box as Box_;

glib::wrapper! {
    #[doc(alias = "AwraStyleManager")]
    pub struct StyleManager(Object<ffi::AwraStyleManager, ffi::AwraStyleManagerClass>);

    match fn {
        type_ => || ffi::awra_style_manager_get_type(),
    }
}

impl StyleManager {
    // rustdoc-stripper-ignore-next
    /// Creates a new builder-pattern struct instance to construct [`StyleManager`] objects.
    ///
    /// This method returns an instance of [`StyleManagerBuilder`](crate::builders::StyleManagerBuilder) which can be used to create [`StyleManager`] objects.
    pub fn builder() -> StyleManagerBuilder {
        StyleManagerBuilder::new()
    }

    #[doc(alias = "awra_style_manager_get_accent")]
    #[doc(alias = "get_accent")]
    pub fn accent(&self) -> gdk::RGBA {
        unsafe { from_glib_none(ffi::awra_style_manager_get_accent(self.to_glib_none().0)) }
    }

    #[doc(alias = "awra_style_manager_get_accent_source")]
    #[doc(alias = "get_accent_source")]
    #[doc(alias = "accent-source")]
    pub fn accent_source(&self) -> AccentSource {
        unsafe {
            from_glib(ffi::awra_style_manager_get_accent_source(
                self.to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "awra_style_manager_get_appearance")]
    #[doc(alias = "get_appearance")]
    pub fn appearance(&self) -> Appearance {
        unsafe {
            from_glib(ffi::awra_style_manager_get_appearance(
                self.to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "awra_style_manager_get_canvas_tint")]
    #[doc(alias = "get_canvas_tint")]
    #[doc(alias = "canvas-tint")]
    pub fn canvas_tint(&self) -> gdk::RGBA {
        unsafe {
            from_glib_none(ffi::awra_style_manager_get_canvas_tint(
                self.to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "awra_style_manager_get_grain_scale")]
    #[doc(alias = "get_grain_scale")]
    #[doc(alias = "grain-scale")]
    pub fn grain_scale(&self) -> f64 {
        unsafe { ffi::awra_style_manager_get_grain_scale(self.to_glib_none().0) }
    }

    #[doc(alias = "awra_style_manager_get_high_contrast")]
    #[doc(alias = "get_high_contrast")]
    #[doc(alias = "high-contrast")]
    pub fn is_high_contrast(&self) -> bool {
        unsafe {
            from_glib(ffi::awra_style_manager_get_high_contrast(
                self.to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "awra_style_manager_get_material_blur_enabled")]
    #[doc(alias = "get_material_blur_enabled")]
    pub fn is_material_blur_enabled(&self, material: &Material) -> bool {
        unsafe {
            from_glib(ffi::awra_style_manager_get_material_blur_enabled(
                self.to_glib_none().0,
                material.to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "awra_style_manager_get_material_grain_scale")]
    #[doc(alias = "get_material_grain_scale")]
    pub fn material_grain_scale(&self, material: &Material) -> f64 {
        unsafe {
            ffi::awra_style_manager_get_material_grain_scale(
                self.to_glib_none().0,
                material.to_glib_none().0,
            )
        }
    }

    #[doc(alias = "awra_style_manager_get_material_highlight_strength")]
    #[doc(alias = "get_material_highlight_strength")]
    pub fn material_highlight_strength(&self, material: &Material) -> f64 {
        unsafe {
            ffi::awra_style_manager_get_material_highlight_strength(
                self.to_glib_none().0,
                material.to_glib_none().0,
            )
        }
    }

    #[doc(alias = "awra_style_manager_get_material_outline_strength")]
    #[doc(alias = "get_material_outline_strength")]
    pub fn material_outline_strength(&self, material: &Material) -> f64 {
        unsafe {
            ffi::awra_style_manager_get_material_outline_strength(
                self.to_glib_none().0,
                material.to_glib_none().0,
            )
        }
    }

    #[doc(alias = "awra_style_manager_get_material_radius")]
    #[doc(alias = "get_material_radius")]
    pub fn material_radius(&self, material: &Material) -> f64 {
        unsafe {
            ffi::awra_style_manager_get_material_radius(
                self.to_glib_none().0,
                material.to_glib_none().0,
            )
        }
    }

    #[doc(alias = "awra_style_manager_get_material_tint")]
    #[doc(alias = "get_material_tint")]
    pub fn material_tint(&self, material: &Material) -> gdk::RGBA {
        unsafe {
            from_glib_none(ffi::awra_style_manager_get_material_tint(
                self.to_glib_none().0,
                material.to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "awra_style_manager_get_native_blur_enabled")]
    #[doc(alias = "get_native_blur_enabled")]
    #[doc(alias = "native-blur-enabled")]
    pub fn is_native_blur_enabled(&self) -> bool {
        unsafe {
            from_glib(ffi::awra_style_manager_get_native_blur_enabled(
                self.to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "awra_style_manager_get_reduced_motion")]
    #[doc(alias = "get_reduced_motion")]
    #[doc(alias = "reduced-motion")]
    pub fn is_reduced_motion(&self) -> bool {
        unsafe {
            from_glib(ffi::awra_style_manager_get_reduced_motion(
                self.to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "awra_style_manager_get_reduced_transparency")]
    #[doc(alias = "get_reduced_transparency")]
    #[doc(alias = "reduced-transparency")]
    pub fn is_reduced_transparency(&self) -> bool {
        unsafe {
            from_glib(ffi::awra_style_manager_get_reduced_transparency(
                self.to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "awra_style_manager_get_system_accent_available")]
    #[doc(alias = "get_system_accent_available")]
    #[doc(alias = "system-accent-available")]
    pub fn is_system_accent_available(&self) -> bool {
        unsafe {
            from_glib(ffi::awra_style_manager_get_system_accent_available(
                self.to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "awra_style_manager_get_token_set")]
    #[doc(alias = "get_token_set")]
    #[doc(alias = "token-set")]
    pub fn token_set(&self) -> TokenSet {
        unsafe { from_glib_none(ffi::awra_style_manager_get_token_set(self.to_glib_none().0)) }
    }

    #[doc(alias = "awra_style_manager_reset_material_tuning")]
    pub fn reset_material_tuning(&self) {
        unsafe {
            ffi::awra_style_manager_reset_material_tuning(self.to_glib_none().0);
        }
    }

    #[doc(alias = "awra_style_manager_reset_material_tuning_for_material")]
    pub fn reset_material_tuning_for_material(&self, material: &Material) {
        unsafe {
            ffi::awra_style_manager_reset_material_tuning_for_material(
                self.to_glib_none().0,
                material.to_glib_none().0,
            );
        }
    }

    #[doc(alias = "awra_style_manager_set_accent")]
    #[doc(alias = "accent")]
    pub fn set_accent(&self, accent: &gdk::RGBA) {
        unsafe {
            ffi::awra_style_manager_set_accent(self.to_glib_none().0, accent.to_glib_none().0);
        }
    }

    #[doc(alias = "awra_style_manager_set_accent_source")]
    #[doc(alias = "accent-source")]
    pub fn set_accent_source(&self, source: AccentSource) {
        unsafe {
            ffi::awra_style_manager_set_accent_source(self.to_glib_none().0, source.into_glib());
        }
    }

    #[doc(alias = "awra_style_manager_set_appearance")]
    #[doc(alias = "appearance")]
    pub fn set_appearance(&self, appearance: Appearance) {
        unsafe {
            ffi::awra_style_manager_set_appearance(self.to_glib_none().0, appearance.into_glib());
        }
    }

    #[doc(alias = "awra_style_manager_set_canvas_tint")]
    #[doc(alias = "canvas-tint")]
    pub fn set_canvas_tint(&self, tint: &gdk::RGBA) {
        unsafe {
            ffi::awra_style_manager_set_canvas_tint(self.to_glib_none().0, tint.to_glib_none().0);
        }
    }

    #[doc(alias = "awra_style_manager_set_grain_scale")]
    #[doc(alias = "grain-scale")]
    pub fn set_grain_scale(&self, scale: f64) {
        unsafe {
            ffi::awra_style_manager_set_grain_scale(self.to_glib_none().0, scale);
        }
    }

    #[doc(alias = "awra_style_manager_set_high_contrast")]
    #[doc(alias = "high-contrast")]
    pub fn set_high_contrast(&self, high_contrast: bool) {
        unsafe {
            ffi::awra_style_manager_set_high_contrast(
                self.to_glib_none().0,
                high_contrast.into_glib(),
            );
        }
    }

    #[doc(alias = "awra_style_manager_set_material_blur_enabled")]
    pub fn set_material_blur_enabled(&self, material: &Material, enabled: bool) {
        unsafe {
            ffi::awra_style_manager_set_material_blur_enabled(
                self.to_glib_none().0,
                material.to_glib_none().0,
                enabled.into_glib(),
            );
        }
    }

    #[doc(alias = "awra_style_manager_set_material_grain_scale")]
    pub fn set_material_grain_scale(&self, material: &Material, scale: f64) {
        unsafe {
            ffi::awra_style_manager_set_material_grain_scale(
                self.to_glib_none().0,
                material.to_glib_none().0,
                scale,
            );
        }
    }

    #[doc(alias = "awra_style_manager_set_material_highlight_strength")]
    pub fn set_material_highlight_strength(&self, material: &Material, strength: f64) {
        unsafe {
            ffi::awra_style_manager_set_material_highlight_strength(
                self.to_glib_none().0,
                material.to_glib_none().0,
                strength,
            );
        }
    }

    #[doc(alias = "awra_style_manager_set_material_outline_strength")]
    pub fn set_material_outline_strength(&self, material: &Material, strength: f64) {
        unsafe {
            ffi::awra_style_manager_set_material_outline_strength(
                self.to_glib_none().0,
                material.to_glib_none().0,
                strength,
            );
        }
    }

    #[doc(alias = "awra_style_manager_set_material_radius")]
    pub fn set_material_radius(&self, material: &Material, radius: f64) {
        unsafe {
            ffi::awra_style_manager_set_material_radius(
                self.to_glib_none().0,
                material.to_glib_none().0,
                radius,
            );
        }
    }

    #[doc(alias = "awra_style_manager_set_material_tint")]
    pub fn set_material_tint(&self, material: &Material, tint: &gdk::RGBA) {
        unsafe {
            ffi::awra_style_manager_set_material_tint(
                self.to_glib_none().0,
                material.to_glib_none().0,
                tint.to_glib_none().0,
            );
        }
    }

    #[doc(alias = "awra_style_manager_set_native_blur_enabled")]
    #[doc(alias = "native-blur-enabled")]
    pub fn set_native_blur_enabled(&self, enabled: bool) {
        unsafe {
            ffi::awra_style_manager_set_native_blur_enabled(
                self.to_glib_none().0,
                enabled.into_glib(),
            );
        }
    }

    #[doc(alias = "awra_style_manager_set_reduced_motion")]
    #[doc(alias = "reduced-motion")]
    pub fn set_reduced_motion(&self, reduced_motion: bool) {
        unsafe {
            ffi::awra_style_manager_set_reduced_motion(
                self.to_glib_none().0,
                reduced_motion.into_glib(),
            );
        }
    }

    #[doc(alias = "awra_style_manager_set_reduced_transparency")]
    #[doc(alias = "reduced-transparency")]
    pub fn set_reduced_transparency(&self, reduced_transparency: bool) {
        unsafe {
            ffi::awra_style_manager_set_reduced_transparency(
                self.to_glib_none().0,
                reduced_transparency.into_glib(),
            );
        }
    }

    #[doc(alias = "accent")]
    pub fn connect_accent_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_accent_trampoline<F: Fn(&StyleManager) + 'static>(
            this: *mut ffi::AwraStyleManager,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::accent".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_accent_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "accent-source")]
    pub fn connect_accent_source_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_accent_source_trampoline<F: Fn(&StyleManager) + 'static>(
            this: *mut ffi::AwraStyleManager,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::accent-source".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_accent_source_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "appearance")]
    pub fn connect_appearance_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_appearance_trampoline<F: Fn(&StyleManager) + 'static>(
            this: *mut ffi::AwraStyleManager,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::appearance".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_appearance_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "canvas-tint")]
    pub fn connect_canvas_tint_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_canvas_tint_trampoline<F: Fn(&StyleManager) + 'static>(
            this: *mut ffi::AwraStyleManager,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::canvas-tint".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_canvas_tint_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "grain-scale")]
    pub fn connect_grain_scale_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_grain_scale_trampoline<F: Fn(&StyleManager) + 'static>(
            this: *mut ffi::AwraStyleManager,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::grain-scale".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_grain_scale_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "high-contrast")]
    pub fn connect_high_contrast_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_high_contrast_trampoline<F: Fn(&StyleManager) + 'static>(
            this: *mut ffi::AwraStyleManager,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::high-contrast".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_high_contrast_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "native-blur-enabled")]
    pub fn connect_native_blur_enabled_notify<F: Fn(&Self) + 'static>(
        &self,
        f: F,
    ) -> SignalHandlerId {
        unsafe extern "C" fn notify_native_blur_enabled_trampoline<
            F: Fn(&StyleManager) + 'static,
        >(
            this: *mut ffi::AwraStyleManager,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::native-blur-enabled".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_native_blur_enabled_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "reduced-motion")]
    pub fn connect_reduced_motion_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_reduced_motion_trampoline<F: Fn(&StyleManager) + 'static>(
            this: *mut ffi::AwraStyleManager,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::reduced-motion".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_reduced_motion_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "reduced-transparency")]
    pub fn connect_reduced_transparency_notify<F: Fn(&Self) + 'static>(
        &self,
        f: F,
    ) -> SignalHandlerId {
        unsafe extern "C" fn notify_reduced_transparency_trampoline<
            F: Fn(&StyleManager) + 'static,
        >(
            this: *mut ffi::AwraStyleManager,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::reduced-transparency".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_reduced_transparency_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "system-accent-available")]
    pub fn connect_system_accent_available_notify<F: Fn(&Self) + 'static>(
        &self,
        f: F,
    ) -> SignalHandlerId {
        unsafe extern "C" fn notify_system_accent_available_trampoline<
            F: Fn(&StyleManager) + 'static,
        >(
            this: *mut ffi::AwraStyleManager,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::system-accent-available".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_system_accent_available_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "token-set")]
    pub fn connect_token_set_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_token_set_trampoline<F: Fn(&StyleManager) + 'static>(
            this: *mut ffi::AwraStyleManager,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::token-set".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_token_set_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }
}

// rustdoc-stripper-ignore-next
/// A [builder-pattern] type to construct [`StyleManager`] objects.
///
/// [builder-pattern]: https://doc.rust-lang.org/1.0.0/style/ownership/builders.html
#[must_use = "The builder must be built to be used"]
pub struct StyleManagerBuilder {
    builder: glib::object::ObjectBuilder<'static, StyleManager>,
}

impl StyleManagerBuilder {
    fn new() -> Self {
        Self {
            builder: glib::object::Object::builder(),
        }
    }

    pub fn accent(self, accent: &gdk::RGBA) -> Self {
        Self {
            builder: self.builder.property("accent", accent),
        }
    }

    pub fn accent_source(self, accent_source: AccentSource) -> Self {
        Self {
            builder: self.builder.property("accent-source", accent_source),
        }
    }

    pub fn appearance(self, appearance: Appearance) -> Self {
        Self {
            builder: self.builder.property("appearance", appearance),
        }
    }

    pub fn canvas_tint(self, canvas_tint: &gdk::RGBA) -> Self {
        Self {
            builder: self.builder.property("canvas-tint", canvas_tint),
        }
    }

    pub fn grain_scale(self, grain_scale: f64) -> Self {
        Self {
            builder: self.builder.property("grain-scale", grain_scale),
        }
    }

    pub fn high_contrast(self, high_contrast: bool) -> Self {
        Self {
            builder: self.builder.property("high-contrast", high_contrast),
        }
    }

    pub fn native_blur_enabled(self, native_blur_enabled: bool) -> Self {
        Self {
            builder: self
                .builder
                .property("native-blur-enabled", native_blur_enabled),
        }
    }

    pub fn reduced_motion(self, reduced_motion: bool) -> Self {
        Self {
            builder: self.builder.property("reduced-motion", reduced_motion),
        }
    }

    pub fn reduced_transparency(self, reduced_transparency: bool) -> Self {
        Self {
            builder: self
                .builder
                .property("reduced-transparency", reduced_transparency),
        }
    }

    // rustdoc-stripper-ignore-next
    /// Build the [`StyleManager`].
    #[must_use = "Building the object from the builder is usually expensive and is not expected to have side effects"]
    pub fn build(self) -> StyleManager {
        assert_initialized_main_thread!();
        self.builder.build()
    }
}
