// This file was generated by gir (https://github.com/gtk-rs/gir)
// from build
// from subprojects/gir-files
// DO NOT EDIT

use crate::{ffi, Elevation, Material, SurfaceCorner, SurfaceEdge, SurfaceRole};
use glib::{
    prelude::*,
    signal::{connect_raw, SignalHandlerId},
    translate::*,
};
use std::boxed::Box as Box_;

#[cfg(feature = "gtk_v4_10")]
#[cfg_attr(docsrs, doc(cfg(feature = "gtk_v4_10")))]
glib::wrapper! {
    #[doc(alias = "AwraSurface")]
    pub struct Surface(Object<ffi::AwraSurface, ffi::AwraSurfaceClass>) @extends gtk::Widget, gobject::InitiallyUnowned, @implements gtk::Accessible, gtk::Buildable, gtk::ConstraintTarget;

    match fn {
        type_ => || ffi::awra_surface_get_type(),
    }
}

#[cfg(not(feature = "gtk_v4_10"))]
glib::wrapper! {
    #[doc(alias = "AwraSurface")]
    pub struct Surface(Object<ffi::AwraSurface, ffi::AwraSurfaceClass>) @extends gtk::Widget, gobject::InitiallyUnowned, @implements gtk::Buildable, gtk::ConstraintTarget;

    match fn {
        type_ => || ffi::awra_surface_get_type(),
    }
}

impl Surface {
    #[doc(alias = "awra_surface_new")]
    pub fn new() -> Surface {
        assert_initialized_main_thread!();
        unsafe { gtk::Widget::from_glib_none(ffi::awra_surface_new()).unsafe_cast() }
    }

    #[doc(alias = "awra_surface_new_with_role")]
    #[doc(alias = "new_with_role")]
    pub fn with_role(role: SurfaceRole) -> Surface {
        assert_initialized_main_thread!();
        unsafe {
            gtk::Widget::from_glib_none(ffi::awra_surface_new_with_role(role.into_glib()))
                .unsafe_cast()
        }
    }

    // rustdoc-stripper-ignore-next
    /// Creates a new builder-pattern struct instance to construct [`Surface`] objects.
    ///
    /// This method returns an instance of [`SurfaceBuilder`](crate::builders::SurfaceBuilder) which can be used to create [`Surface`] objects.
    pub fn builder() -> SurfaceBuilder {
        SurfaceBuilder::new()
    }

    #[doc(alias = "awra_surface_get_child")]
    #[doc(alias = "get_child")]
    pub fn child(&self) -> Option<gtk::Widget> {
        unsafe { from_glib_none(ffi::awra_surface_get_child(self.to_glib_none().0)) }
    }

    #[doc(alias = "awra_surface_get_clip_child")]
    #[doc(alias = "get_clip_child")]
    #[doc(alias = "clip-child")]
    pub fn is_clip_child(&self) -> bool {
        unsafe { from_glib(ffi::awra_surface_get_clip_child(self.to_glib_none().0)) }
    }

    #[doc(alias = "awra_surface_get_corner_mask")]
    #[doc(alias = "get_corner_mask")]
    #[doc(alias = "corner-mask")]
    pub fn corner_mask(&self) -> SurfaceCorner {
        unsafe { from_glib(ffi::awra_surface_get_corner_mask(self.to_glib_none().0)) }
    }

    #[doc(alias = "awra_surface_get_edge_mask")]
    #[doc(alias = "get_edge_mask")]
    #[doc(alias = "edge-mask")]
    pub fn edge_mask(&self) -> SurfaceEdge {
        unsafe { from_glib(ffi::awra_surface_get_edge_mask(self.to_glib_none().0)) }
    }

    #[doc(alias = "awra_surface_get_elevation")]
    #[doc(alias = "get_elevation")]
    pub fn elevation(&self) -> u32 {
        unsafe { ffi::awra_surface_get_elevation(self.to_glib_none().0) }
    }

    #[doc(alias = "awra_surface_get_elevation_level")]
    #[doc(alias = "get_elevation_level")]
    pub fn elevation_level(&self) -> Elevation {
        unsafe { from_glib(ffi::awra_surface_get_elevation_level(self.to_glib_none().0)) }
    }

    #[doc(alias = "awra_surface_get_material")]
    #[doc(alias = "get_material")]
    pub fn material(&self) -> Material {
        unsafe { from_glib_none(ffi::awra_surface_get_material(self.to_glib_none().0)) }
    }

    #[doc(alias = "awra_surface_get_radius")]
    #[doc(alias = "get_radius")]
    pub fn radius(&self) -> f64 {
        unsafe { ffi::awra_surface_get_radius(self.to_glib_none().0) }
    }

    #[doc(alias = "awra_surface_get_role")]
    #[doc(alias = "get_role")]
    pub fn role(&self) -> SurfaceRole {
        unsafe { from_glib(ffi::awra_surface_get_role(self.to_glib_none().0)) }
    }

    #[doc(alias = "awra_surface_set_child")]
    #[doc(alias = "child")]
    pub fn set_child(&self, child: Option<&impl IsA<gtk::Widget>>) {
        unsafe {
            ffi::awra_surface_set_child(
                self.to_glib_none().0,
                child.map(|p| p.as_ref()).to_glib_none().0,
            );
        }
    }

    #[doc(alias = "awra_surface_set_clip_child")]
    #[doc(alias = "clip-child")]
    pub fn set_clip_child(&self, clip_child: bool) {
        unsafe {
            ffi::awra_surface_set_clip_child(self.to_glib_none().0, clip_child.into_glib());
        }
    }

    #[doc(alias = "awra_surface_set_corner_mask")]
    #[doc(alias = "corner-mask")]
    pub fn set_corner_mask(&self, corners: SurfaceCorner) {
        unsafe {
            ffi::awra_surface_set_corner_mask(self.to_glib_none().0, corners.into_glib());
        }
    }

    #[doc(alias = "awra_surface_set_edge_mask")]
    #[doc(alias = "edge-mask")]
    pub fn set_edge_mask(&self, edges: SurfaceEdge) {
        unsafe {
            ffi::awra_surface_set_edge_mask(self.to_glib_none().0, edges.into_glib());
        }
    }

    #[doc(alias = "awra_surface_set_elevation")]
    #[doc(alias = "elevation")]
    pub fn set_elevation(&self, elevation: u32) {
        unsafe {
            ffi::awra_surface_set_elevation(self.to_glib_none().0, elevation);
        }
    }

    #[doc(alias = "awra_surface_set_elevation_level")]
    pub fn set_elevation_level(&self, elevation: Elevation) {
        unsafe {
            ffi::awra_surface_set_elevation_level(self.to_glib_none().0, elevation.into_glib());
        }
    }

    #[doc(alias = "awra_surface_set_material")]
    #[doc(alias = "material")]
    pub fn set_material(&self, material: &Material) {
        unsafe {
            ffi::awra_surface_set_material(self.to_glib_none().0, material.to_glib_none().0);
        }
    }

    #[doc(alias = "awra_surface_set_radius")]
    #[doc(alias = "radius")]
    pub fn set_radius(&self, radius: f64) {
        unsafe {
            ffi::awra_surface_set_radius(self.to_glib_none().0, radius);
        }
    }

    #[doc(alias = "awra_surface_set_role")]
    #[doc(alias = "role")]
    pub fn set_role(&self, role: SurfaceRole) {
        unsafe {
            ffi::awra_surface_set_role(self.to_glib_none().0, role.into_glib());
        }
    }

    #[doc(alias = "child")]
    pub fn connect_child_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_child_trampoline<F: Fn(&Surface) + 'static>(
            this: *mut ffi::AwraSurface,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::child".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_child_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "clip-child")]
    pub fn connect_clip_child_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_clip_child_trampoline<F: Fn(&Surface) + 'static>(
            this: *mut ffi::AwraSurface,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::clip-child".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_clip_child_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "corner-mask")]
    pub fn connect_corner_mask_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_corner_mask_trampoline<F: Fn(&Surface) + 'static>(
            this: *mut ffi::AwraSurface,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::corner-mask".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_corner_mask_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "edge-mask")]
    pub fn connect_edge_mask_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_edge_mask_trampoline<F: Fn(&Surface) + 'static>(
            this: *mut ffi::AwraSurface,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::edge-mask".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_edge_mask_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "elevation")]
    pub fn connect_elevation_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_elevation_trampoline<F: Fn(&Surface) + 'static>(
            this: *mut ffi::AwraSurface,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::elevation".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_elevation_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "material")]
    pub fn connect_material_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_material_trampoline<F: Fn(&Surface) + 'static>(
            this: *mut ffi::AwraSurface,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::material".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_material_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "radius")]
    pub fn connect_radius_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_radius_trampoline<F: Fn(&Surface) + 'static>(
            this: *mut ffi::AwraSurface,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::radius".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_radius_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "role")]
    pub fn connect_role_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_role_trampoline<F: Fn(&Surface) + 'static>(
            this: *mut ffi::AwraSurface,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::role".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_role_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }
}

impl Default for Surface {
    fn default() -> Self {
        Self::new()
    }
}

// rustdoc-stripper-ignore-next
/// A [builder-pattern] type to construct [`Surface`] objects.
///
/// [builder-pattern]: https://doc.rust-lang.org/1.0.0/style/ownership/builders.html
#[must_use = "The builder must be built to be used"]
pub struct SurfaceBuilder {
    builder: glib::object::ObjectBuilder<'static, Surface>,
}

impl SurfaceBuilder {
    fn new() -> Self {
        Self {
            builder: glib::object::Object::builder(),
        }
    }

    pub fn child(self, child: &impl IsA<gtk::Widget>) -> Self {
        Self {
            builder: self.builder.property("child", child.clone().upcast()),
        }
    }

    pub fn clip_child(self, clip_child: bool) -> Self {
        Self {
            builder: self.builder.property("clip-child", clip_child),
        }
    }

    pub fn corner_mask(self, corner_mask: SurfaceCorner) -> Self {
        Self {
            builder: self.builder.property("corner-mask", corner_mask),
        }
    }

    pub fn edge_mask(self, edge_mask: SurfaceEdge) -> Self {
        Self {
            builder: self.builder.property("edge-mask", edge_mask),
        }
    }

    pub fn elevation(self, elevation: u32) -> Self {
        Self {
            builder: self.builder.property("elevation", elevation),
        }
    }

    pub fn material(self, material: &Material) -> Self {
        Self {
            builder: self.builder.property("material", material.clone()),
        }
    }

    pub fn radius(self, radius: f64) -> Self {
        Self {
            builder: self.builder.property("radius", radius),
        }
    }

    pub fn role(self, role: SurfaceRole) -> Self {
        Self {
            builder: self.builder.property("role", role),
        }
    }

    pub fn can_focus(self, can_focus: bool) -> Self {
        Self {
            builder: self.builder.property("can-focus", can_focus),
        }
    }

    pub fn can_target(self, can_target: bool) -> Self {
        Self {
            builder: self.builder.property("can-target", can_target),
        }
    }

    pub fn css_classes(self, css_classes: impl Into<glib::StrV>) -> Self {
        Self {
            builder: self.builder.property("css-classes", css_classes.into()),
        }
    }

    pub fn css_name(self, css_name: impl Into<glib::GString>) -> Self {
        Self {
            builder: self.builder.property("css-name", css_name.into()),
        }
    }

    //pub fn cursor(self, cursor: /*Ignored*/&gdk::Cursor) -> Self {
    //    Self { builder: self.builder.property("cursor", cursor), }
    //}

    pub fn focus_on_click(self, focus_on_click: bool) -> Self {
        Self {
            builder: self.builder.property("focus-on-click", focus_on_click),
        }
    }

    pub fn focusable(self, focusable: bool) -> Self {
        Self {
            builder: self.builder.property("focusable", focusable),
        }
    }

    pub fn halign(self, halign: gtk::Align) -> Self {
        Self {
            builder: self.builder.property("halign", halign),
        }
    }

    pub fn has_tooltip(self, has_tooltip: bool) -> Self {
        Self {
            builder: self.builder.property("has-tooltip", has_tooltip),
        }
    }

    pub fn height_request(self, height_request: i32) -> Self {
        Self {
            builder: self.builder.property("height-request", height_request),
        }
    }

    pub fn hexpand(self, hexpand: bool) -> Self {
        Self {
            builder: self.builder.property("hexpand", hexpand),
        }
    }

    pub fn hexpand_set(self, hexpand_set: bool) -> Self {
        Self {
            builder: self.builder.property("hexpand-set", hexpand_set),
        }
    }

    //pub fn layout_manager(self, layout_manager: &impl IsA</*Ignored*/gtk::LayoutManager>) -> Self {
    //    Self { builder: self.builder.property("layout-manager", layout_manager.clone().upcast()), }
    //}

    #[cfg(feature = "gtk_v4_18")]
    #[cfg_attr(docsrs, doc(cfg(feature = "gtk_v4_18")))]
    pub fn limit_events(self, limit_events: bool) -> Self {
        Self {
            builder: self.builder.property("limit-events", limit_events),
        }
    }

    pub fn margin_bottom(self, margin_bottom: i32) -> Self {
        Self {
            builder: self.builder.property("margin-bottom", margin_bottom),
        }
    }

    pub fn margin_end(self, margin_end: i32) -> Self {
        Self {
            builder: self.builder.property("margin-end", margin_end),
        }
    }

    pub fn margin_start(self, margin_start: i32) -> Self {
        Self {
            builder: self.builder.property("margin-start", margin_start),
        }
    }

    pub fn margin_top(self, margin_top: i32) -> Self {
        Self {
            builder: self.builder.property("margin-top", margin_top),
        }
    }

    pub fn name(self, name: impl Into<glib::GString>) -> Self {
        Self {
            builder: self.builder.property("name", name.into()),
        }
    }

    pub fn opacity(self, opacity: f64) -> Self {
        Self {
            builder: self.builder.property("opacity", opacity),
        }
    }

    //pub fn overflow(self, overflow: /*Ignored*/gtk::Overflow) -> Self {
    //    Self { builder: self.builder.property("overflow", overflow), }
    //}

    pub fn receives_default(self, receives_default: bool) -> Self {
        Self {
            builder: self.builder.property("receives-default", receives_default),
        }
    }

    pub fn sensitive(self, sensitive: bool) -> Self {
        Self {
            builder: self.builder.property("sensitive", sensitive),
        }
    }

    pub fn tooltip_markup(self, tooltip_markup: impl Into<glib::GString>) -> Self {
        Self {
            builder: self
                .builder
                .property("tooltip-markup", tooltip_markup.into()),
        }
    }

    pub fn tooltip_text(self, tooltip_text: impl Into<glib::GString>) -> Self {
        Self {
            builder: self.builder.property("tooltip-text", tooltip_text.into()),
        }
    }

    pub fn valign(self, valign: gtk::Align) -> Self {
        Self {
            builder: self.builder.property("valign", valign),
        }
    }

    pub fn vexpand(self, vexpand: bool) -> Self {
        Self {
            builder: self.builder.property("vexpand", vexpand),
        }
    }

    pub fn vexpand_set(self, vexpand_set: bool) -> Self {
        Self {
            builder: self.builder.property("vexpand-set", vexpand_set),
        }
    }

    pub fn visible(self, visible: bool) -> Self {
        Self {
            builder: self.builder.property("visible", visible),
        }
    }

    pub fn width_request(self, width_request: i32) -> Self {
        Self {
            builder: self.builder.property("width-request", width_request),
        }
    }

    //pub fn accessible_role(self, accessible_role: /*Ignored*/gtk::AccessibleRole) -> Self {
    //    Self { builder: self.builder.property("accessible-role", accessible_role), }
    //}

    // rustdoc-stripper-ignore-next
    /// Build the [`Surface`].
    #[must_use = "Building the object from the builder is usually expensive and is not expected to have side effects"]
    pub fn build(self) -> Surface {
        assert_initialized_main_thread!();
        self.builder.build()
    }
}
