[package]
name = "awra-sys"
version = "1.0.0"
edition = "2021"
build = "build.rs"
license = "LGPL-2.1-or-later"
description = "Unsafe generated FFI bindings for Awra"
publish = false

[package.metadata.system-deps.awra_1]
name = "awra-1"
version = "1.0"

[package.metadata.docs.rs]
rustdoc-args = ["--generate-link-to-definition"]
all-features = true

[lib]
name = "awra_sys"

[dependencies]
libc = "0.2"

[dependencies.glib-sys]
version = "0.22.0"

[dependencies.gobject-sys]
version = "0.22.0"

[dependencies.gio-sys]
version = "0.22.0"

[dependencies.gdk-sys]
package = "gdk4-sys"
version = "0.11.0"

[dependencies.gtk-sys]
package = "gtk4-sys"
version = "0.11.0"

[build-dependencies]
system-deps = "7"

[dev-dependencies]
shell-words = "1.0.0"
tempfile = "3"

[features]
