/* SPDX-License-Identifier: LGPL-2.1-or-later */

#include <awra/awra-context.h>
#include <awra/awra-motion.h>
#include <awra/awra-navigation-view.h>

typedef struct {
  char *name;
  GWeakRef focus;
} NavigationEntry;

struct _AwraNavigationView { GtkWidget parent_instance; GtkStack *stack; GPtrArray *history; AwraStyleManager *style; gulong style_handler; };
enum { PROP_0, PROP_CAN_POP, PROP_VISIBLE_PAGE_NAME, PROP_STACK, N_PROPS };
static GParamSpec *properties[N_PROPS];
G_DEFINE_FINAL_TYPE (AwraNavigationView, awra_navigation_view, GTK_TYPE_WIDGET)
static void update_motion (AwraNavigationView *self) { guint duration = self->style != NULL ? awra_motion_get_duration (self->style, AWRA_MOTION_PRESET_NORMAL) : 0; gtk_stack_set_transition_duration (self->stack, duration); gtk_stack_set_transition_type (self->stack, duration == 0 ? GTK_STACK_TRANSITION_TYPE_NONE : GTK_STACK_TRANSITION_TYPE_SLIDE_LEFT_RIGHT); }
static void style_notify_cb (AwraStyleManager *style, GParamSpec *pspec, AwraNavigationView *self) { (void) style; (void) pspec; update_motion (self); }
static void awra_navigation_view_map (GtkWidget *widget) { AwraNavigationView *self = AWRA_NAVIGATION_VIEW (widget); AwraContext *context; GTK_WIDGET_CLASS (awra_navigation_view_parent_class)->map (widget); context = awra_context_get_for_display (gtk_widget_get_display (widget)); self->style = awra_context_get_style_manager (context); update_motion (self); self->style_handler = g_signal_connect (self->style, "notify::reduced-motion", G_CALLBACK (style_notify_cb), self); }
static void awra_navigation_view_unmap (GtkWidget *widget) { AwraNavigationView *self = AWRA_NAVIGATION_VIEW (widget); if (self->style_handler != 0) { g_signal_handler_disconnect (self->style, self->style_handler); self->style_handler = 0; self->style = NULL; } GTK_WIDGET_CLASS (awra_navigation_view_parent_class)->unmap (widget); }
static void navigation_entry_free (gpointer data) { NavigationEntry *entry = data; g_weak_ref_clear (&entry->focus); g_free (entry->name); g_free (entry); }
static NavigationEntry *navigation_entry_new (const char *name) { NavigationEntry *entry = g_new0 (NavigationEntry, 1); entry->name = g_strdup (name); g_weak_ref_init (&entry->focus, NULL); return entry; }
static void remember_current_focus (AwraNavigationView *self) { GtkRoot *root; GtkWidget *focus; NavigationEntry *entry; if (self->history->len == 0) return; root = gtk_widget_get_root (GTK_WIDGET (self)); focus = root != NULL ? gtk_root_get_focus (root) : NULL; if (focus == NULL || !gtk_widget_is_ancestor (focus, GTK_WIDGET (self->stack))) return; entry = g_ptr_array_index (self->history, self->history->len - 1); g_weak_ref_set (&entry->focus, focus); }
static void restore_entry_focus (AwraNavigationView *self, NavigationEntry *entry) { g_autoptr (GtkWidget) focus = g_weak_ref_get (&entry->focus); GtkWidget *page = gtk_stack_get_child_by_name (self->stack, entry->name); if (focus != NULL && gtk_widget_get_mapped (focus) && gtk_widget_get_sensitive (focus)) gtk_widget_grab_focus (focus); else if (page != NULL) gtk_widget_child_focus (page, GTK_DIR_TAB_FORWARD); }
static void awra_navigation_view_dispose (GObject *object) { AwraNavigationView *self = AWRA_NAVIGATION_VIEW (object); if (self->style_handler != 0) { g_signal_handler_disconnect (self->style, self->style_handler); self->style_handler = 0; } if (self->stack != NULL) { gtk_widget_unparent (GTK_WIDGET (self->stack)); self->stack = NULL; } g_clear_pointer (&self->history, g_ptr_array_unref); G_OBJECT_CLASS (awra_navigation_view_parent_class)->dispose (object); }
static void awra_navigation_view_snapshot (GtkWidget *widget, GtkSnapshot *snapshot) { gtk_widget_snapshot_child (widget, GTK_WIDGET (AWRA_NAVIGATION_VIEW (widget)->stack), snapshot); }
static void awra_navigation_view_get_property (GObject *object, guint id, GValue *value, GParamSpec *pspec) { AwraNavigationView *self = AWRA_NAVIGATION_VIEW (object); if (id == PROP_CAN_POP) g_value_set_boolean (value, awra_navigation_view_get_can_pop (self)); else if (id == PROP_VISIBLE_PAGE_NAME) g_value_set_string (value, awra_navigation_view_get_visible_page_name (self)); else if (id == PROP_STACK) g_value_set_object (value, self->stack); else G_OBJECT_WARN_INVALID_PROPERTY_ID (object, id, pspec); }
static void awra_navigation_view_class_init (AwraNavigationViewClass *klass) { GObjectClass *oc = G_OBJECT_CLASS (klass); GtkWidgetClass *wc = GTK_WIDGET_CLASS (klass); oc->dispose = awra_navigation_view_dispose; oc->get_property = awra_navigation_view_get_property; wc->map = awra_navigation_view_map; wc->unmap = awra_navigation_view_unmap; wc->snapshot = awra_navigation_view_snapshot; properties[PROP_CAN_POP] = g_param_spec_boolean ("can-pop", NULL, NULL, FALSE, G_PARAM_READABLE | G_PARAM_STATIC_STRINGS); properties[PROP_VISIBLE_PAGE_NAME] = g_param_spec_string ("visible-page-name", NULL, NULL, NULL, G_PARAM_READABLE | G_PARAM_STATIC_STRINGS); properties[PROP_STACK] = g_param_spec_object ("stack", NULL, NULL, GTK_TYPE_STACK, G_PARAM_READABLE | G_PARAM_STATIC_STRINGS); g_object_class_install_properties (oc, N_PROPS, properties); gtk_widget_class_set_layout_manager_type (wc, GTK_TYPE_BIN_LAYOUT); gtk_widget_class_set_css_name (wc, "awranavigationview"); }
static void awra_navigation_view_init (AwraNavigationView *self) { self->stack = GTK_STACK (gtk_stack_new ()); self->history = g_ptr_array_new_with_free_func (navigation_entry_free); gtk_widget_set_parent (GTK_WIDGET (self->stack), GTK_WIDGET (self)); }
static void history_changed (AwraNavigationView *self) { g_object_notify_by_pspec (G_OBJECT (self), properties[PROP_CAN_POP]); g_object_notify_by_pspec (G_OBJECT (self), properties[PROP_VISIBLE_PAGE_NAME]); }
GtkWidget *awra_navigation_view_new (void) { return g_object_new (AWRA_TYPE_NAVIGATION_VIEW, NULL); }
void awra_navigation_view_add (AwraNavigationView *self, GtkWidget *page, const char *name) { g_return_if_fail (AWRA_IS_NAVIGATION_VIEW (self)); g_return_if_fail (GTK_IS_WIDGET (page)); g_return_if_fail (name != NULL && *name != '\0'); gtk_stack_add_named (self->stack, page, name); }
gboolean awra_navigation_view_push (AwraNavigationView *self, const char *name) { NavigationEntry *entry; g_return_val_if_fail (AWRA_IS_NAVIGATION_VIEW (self), FALSE); if (gtk_stack_get_child_by_name (self->stack, name) == NULL) return FALSE; if (self->history->len > 0) { entry = g_ptr_array_index (self->history, self->history->len - 1); if (g_str_equal (entry->name, name)) return TRUE; remember_current_focus (self); } g_ptr_array_add (self->history, navigation_entry_new (name)); gtk_stack_set_visible_child_name (self->stack, name); history_changed (self); return TRUE; }
gboolean awra_navigation_view_pop (AwraNavigationView *self) { NavigationEntry *entry; g_return_val_if_fail (AWRA_IS_NAVIGATION_VIEW (self), FALSE); if (self->history->len <= 1) return FALSE; g_ptr_array_remove_index (self->history, self->history->len - 1); entry = g_ptr_array_index (self->history, self->history->len - 1); gtk_stack_set_visible_child_name (self->stack, entry->name); restore_entry_focus (self, entry); history_changed (self); return TRUE; }
gboolean awra_navigation_view_replace (AwraNavigationView *self, const char *name) { g_return_val_if_fail (AWRA_IS_NAVIGATION_VIEW (self), FALSE); if (gtk_stack_get_child_by_name (self->stack, name) == NULL) return FALSE; if (self->history->len > 0) g_ptr_array_remove_index (self->history, self->history->len - 1); g_ptr_array_add (self->history, navigation_entry_new (name)); gtk_stack_set_visible_child_name (self->stack, name); history_changed (self); return TRUE; }
gboolean awra_navigation_view_get_can_pop (AwraNavigationView *self) { g_return_val_if_fail (AWRA_IS_NAVIGATION_VIEW (self), FALSE); return self->history->len > 1; }
const char *awra_navigation_view_get_visible_page_name (AwraNavigationView *self) { g_return_val_if_fail (AWRA_IS_NAVIGATION_VIEW (self), NULL); return gtk_stack_get_visible_child_name (self->stack); }
GtkStack *awra_navigation_view_get_stack (AwraNavigationView *self) { g_return_val_if_fail (AWRA_IS_NAVIGATION_VIEW (self), NULL); return self->stack; }
