# SPDX-License-Identifier: LGPL-2.1-or-later

install_data(
  'org.awra.Showcase.desktop',
  install_dir: get_option('datadir') / 'applications',
)
install_data(
  'org.awra.Showcase.metainfo.xml',
  install_dir: get_option('datadir') / 'metainfo',
)
install_data(
  'org.awra.Showcase.svg',
  install_dir: get_option('datadir') / 'icons/hicolor/scalable/apps',
)
