/* SPDX-License-Identifier: LGPL-2.1-or-later */

#include <awra/awra-badge-group.h>
#include <awra/awra-layout.h>
#include <awra/awra-metadata-group.h>
#include <awra/awra-progress-bar.h>
#include <awra/awra-stat-bar.h>
#include <awra/awra-typography.h>

struct _AwraMetricRow { GtkWidget parent_instance; GtkBox *root; GtkImage *icon; GtkLabel *label_widget; GtkLabel *value_widget; char *label; char *value; char *icon_name; };
enum { METRIC_PROP_0, METRIC_PROP_LABEL, METRIC_PROP_VALUE, METRIC_PROP_ICON_NAME, METRIC_N_PROPS };
static GParamSpec *metric_properties[METRIC_N_PROPS];
G_DEFINE_FINAL_TYPE (AwraMetricRow, awra_metric_row, GTK_TYPE_WIDGET)
static void metric_dispose (GObject *object) { AwraMetricRow *self = AWRA_METRIC_ROW (object); if (self->root != NULL) { gtk_widget_unparent (GTK_WIDGET (self->root)); self->root = NULL; } G_OBJECT_CLASS (awra_metric_row_parent_class)->dispose (object); }
static void metric_finalize (GObject *object) { AwraMetricRow *self = AWRA_METRIC_ROW (object); g_free (self->label); g_free (self->value); g_free (self->icon_name); G_OBJECT_CLASS (awra_metric_row_parent_class)->finalize (object); }
static void metric_snapshot (GtkWidget *widget, GtkSnapshot *snapshot) { gtk_widget_snapshot_child (widget, GTK_WIDGET (AWRA_METRIC_ROW (widget)->root), snapshot); }
static void metric_get_property (GObject *object, guint id, GValue *value, GParamSpec *pspec) { AwraMetricRow *self = AWRA_METRIC_ROW (object); switch (id) { case METRIC_PROP_LABEL: g_value_set_string (value, self->label); break; case METRIC_PROP_VALUE: g_value_set_string (value, self->value); break; case METRIC_PROP_ICON_NAME: g_value_set_string (value, self->icon_name); break; default: G_OBJECT_WARN_INVALID_PROPERTY_ID (object, id, pspec); } }
static void metric_set_property (GObject *object, guint id, const GValue *value, GParamSpec *pspec) { switch (id) { case METRIC_PROP_LABEL: awra_metric_row_set_label (AWRA_METRIC_ROW (object), g_value_get_string (value)); break; case METRIC_PROP_VALUE: awra_metric_row_set_value (AWRA_METRIC_ROW (object), g_value_get_string (value)); break; case METRIC_PROP_ICON_NAME: awra_metric_row_set_icon_name (AWRA_METRIC_ROW (object), g_value_get_string (value)); break; default: G_OBJECT_WARN_INVALID_PROPERTY_ID (object, id, pspec); } }
static void awra_metric_row_class_init (AwraMetricRowClass *klass) { GObjectClass *oc = G_OBJECT_CLASS (klass); GtkWidgetClass *wc = GTK_WIDGET_CLASS (klass); oc->dispose = metric_dispose; oc->finalize = metric_finalize; oc->get_property = metric_get_property; oc->set_property = metric_set_property; wc->snapshot = metric_snapshot; metric_properties[METRIC_PROP_LABEL] = g_param_spec_string ("label", NULL, NULL, NULL, G_PARAM_READWRITE | G_PARAM_EXPLICIT_NOTIFY | G_PARAM_STATIC_STRINGS); metric_properties[METRIC_PROP_VALUE] = g_param_spec_string ("value", NULL, NULL, NULL, G_PARAM_READWRITE | G_PARAM_EXPLICIT_NOTIFY | G_PARAM_STATIC_STRINGS); metric_properties[METRIC_PROP_ICON_NAME] = g_param_spec_string ("icon-name", NULL, NULL, NULL, G_PARAM_READWRITE | G_PARAM_EXPLICIT_NOTIFY | G_PARAM_STATIC_STRINGS); g_object_class_install_properties (oc, METRIC_N_PROPS, metric_properties); gtk_widget_class_set_layout_manager_type (wc, GTK_TYPE_BIN_LAYOUT); gtk_widget_class_set_css_name (wc, "awrametricrow"); gtk_widget_class_set_accessible_role (wc, GTK_ACCESSIBLE_ROLE_GROUP); }
static void awra_metric_row_init (AwraMetricRow *self) { self->root = GTK_BOX (gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 0)); self->icon = GTK_IMAGE (gtk_image_new ()); self->label_widget = GTK_LABEL (gtk_label_new (NULL)); self->value_widget = GTK_LABEL (gtk_label_new (NULL)); awra_box_set_spacing (self->root, AWRA_SPACING_SM); gtk_widget_set_visible (GTK_WIDGET (self->icon), FALSE); gtk_widget_set_hexpand (GTK_WIDGET (self->label_widget), TRUE); gtk_label_set_xalign (self->label_widget, 0.0f); gtk_label_set_xalign (self->value_widget, 1.0f); gtk_label_set_ellipsize (self->label_widget, PANGO_ELLIPSIZE_END); awra_widget_set_typography (GTK_WIDGET (self->label_widget), AWRA_TYPOGRAPHY_BODY); awra_widget_set_typography (GTK_WIDGET (self->value_widget), AWRA_TYPOGRAPHY_MONOSPACE); gtk_box_append (self->root, GTK_WIDGET (self->icon)); gtk_box_append (self->root, GTK_WIDGET (self->label_widget)); gtk_box_append (self->root, GTK_WIDGET (self->value_widget)); gtk_widget_set_parent (GTK_WIDGET (self->root), GTK_WIDGET (self)); }
GtkWidget *awra_metric_row_new (const char *label, const char *value) { return g_object_new (AWRA_TYPE_METRIC_ROW, "label", label, "value", value, NULL); }
const char *awra_metric_row_get_label (AwraMetricRow *self) { g_return_val_if_fail (AWRA_IS_METRIC_ROW (self), NULL); return self->label; }
void awra_metric_row_set_label (AwraMetricRow *self, const char *label) { g_return_if_fail (AWRA_IS_METRIC_ROW (self)); if (g_strcmp0 (self->label, label) == 0) return; g_free (self->label); self->label = g_strdup (label); gtk_label_set_text (self->label_widget, label != NULL ? label : ""); gtk_accessible_update_property (GTK_ACCESSIBLE (self), GTK_ACCESSIBLE_PROPERTY_LABEL, label != NULL ? label : "", -1); g_object_notify_by_pspec (G_OBJECT (self), metric_properties[METRIC_PROP_LABEL]); }
const char *awra_metric_row_get_value (AwraMetricRow *self) { g_return_val_if_fail (AWRA_IS_METRIC_ROW (self), NULL); return self->value; }
void awra_metric_row_set_value (AwraMetricRow *self, const char *value) { g_return_if_fail (AWRA_IS_METRIC_ROW (self)); if (g_strcmp0 (self->value, value) == 0) return; g_free (self->value); self->value = g_strdup (value); gtk_label_set_text (self->value_widget, value != NULL ? value : ""); gtk_accessible_update_property (GTK_ACCESSIBLE (self), GTK_ACCESSIBLE_PROPERTY_DESCRIPTION, value != NULL ? value : "", -1); g_object_notify_by_pspec (G_OBJECT (self), metric_properties[METRIC_PROP_VALUE]); }
const char *awra_metric_row_get_icon_name (AwraMetricRow *self) { g_return_val_if_fail (AWRA_IS_METRIC_ROW (self), NULL); return self->icon_name; }
void awra_metric_row_set_icon_name (AwraMetricRow *self, const char *icon_name) { g_return_if_fail (AWRA_IS_METRIC_ROW (self)); if (g_strcmp0 (self->icon_name, icon_name) == 0) return; g_free (self->icon_name); self->icon_name = g_strdup (icon_name); gtk_image_set_from_icon_name (self->icon, icon_name); gtk_widget_set_visible (GTK_WIDGET (self->icon), icon_name != NULL && *icon_name != '\0'); g_object_notify_by_pspec (G_OBJECT (self), metric_properties[METRIC_PROP_ICON_NAME]); }

struct _AwraStatBar { GtkWidget parent_instance; GtkBox *root; GtkLabel *label_widget; GtkLabel *value_widget; AwraProgressBar *progress; char *label; double value; double maximum; gboolean show_value; };
enum { STAT_PROP_0, STAT_PROP_LABEL, STAT_PROP_VALUE, STAT_PROP_MAXIMUM, STAT_PROP_SHOW_VALUE, STAT_N_PROPS };
static GParamSpec *stat_properties[STAT_N_PROPS];
G_DEFINE_FINAL_TYPE (AwraStatBar, awra_stat_bar, GTK_TYPE_WIDGET)
static void update_stat (AwraStatBar *self) { g_autofree char *text = g_strdup_printf ("%.0f", self->value); awra_progress_bar_set_fraction (self->progress, self->maximum > 0.0 ? self->value / self->maximum : 0.0); gtk_label_set_text (self->value_widget, text); gtk_widget_set_visible (GTK_WIDGET (self->value_widget), self->show_value); gtk_accessible_update_property (GTK_ACCESSIBLE (self), GTK_ACCESSIBLE_PROPERTY_LABEL, self->label != NULL ? self->label : "", GTK_ACCESSIBLE_PROPERTY_VALUE_MIN, 0.0, GTK_ACCESSIBLE_PROPERTY_VALUE_MAX, self->maximum, GTK_ACCESSIBLE_PROPERTY_VALUE_NOW, self->value, GTK_ACCESSIBLE_PROPERTY_VALUE_TEXT, text, -1); }
static void stat_dispose (GObject *object) { AwraStatBar *self = AWRA_STAT_BAR (object); if (self->root != NULL) { gtk_widget_unparent (GTK_WIDGET (self->root)); self->root = NULL; } G_OBJECT_CLASS (awra_stat_bar_parent_class)->dispose (object); }
static void stat_finalize (GObject *object) { g_free (AWRA_STAT_BAR (object)->label); G_OBJECT_CLASS (awra_stat_bar_parent_class)->finalize (object); }
static void stat_snapshot (GtkWidget *widget, GtkSnapshot *snapshot) { gtk_widget_snapshot_child (widget, GTK_WIDGET (AWRA_STAT_BAR (widget)->root), snapshot); }
static void stat_get_property (GObject *object, guint id, GValue *value, GParamSpec *pspec) { AwraStatBar *self = AWRA_STAT_BAR (object); switch (id) { case STAT_PROP_LABEL: g_value_set_string (value, self->label); break; case STAT_PROP_VALUE: g_value_set_double (value, self->value); break; case STAT_PROP_MAXIMUM: g_value_set_double (value, self->maximum); break; case STAT_PROP_SHOW_VALUE: g_value_set_boolean (value, self->show_value); break; default: G_OBJECT_WARN_INVALID_PROPERTY_ID (object, id, pspec); } }
static void stat_set_property (GObject *object, guint id, const GValue *value, GParamSpec *pspec) { switch (id) { case STAT_PROP_LABEL: awra_stat_bar_set_label (AWRA_STAT_BAR (object), g_value_get_string (value)); break; case STAT_PROP_VALUE: awra_stat_bar_set_value (AWRA_STAT_BAR (object), g_value_get_double (value)); break; case STAT_PROP_MAXIMUM: awra_stat_bar_set_maximum (AWRA_STAT_BAR (object), g_value_get_double (value)); break; case STAT_PROP_SHOW_VALUE: awra_stat_bar_set_show_value (AWRA_STAT_BAR (object), g_value_get_boolean (value)); break; default: G_OBJECT_WARN_INVALID_PROPERTY_ID (object, id, pspec); } }
static void awra_stat_bar_class_init (AwraStatBarClass *klass) { GObjectClass *oc = G_OBJECT_CLASS (klass); GtkWidgetClass *wc = GTK_WIDGET_CLASS (klass); oc->dispose = stat_dispose; oc->finalize = stat_finalize; oc->get_property = stat_get_property; oc->set_property = stat_set_property; wc->snapshot = stat_snapshot; stat_properties[STAT_PROP_LABEL] = g_param_spec_string ("label", NULL, NULL, NULL, G_PARAM_READWRITE | G_PARAM_EXPLICIT_NOTIFY | G_PARAM_STATIC_STRINGS); stat_properties[STAT_PROP_VALUE] = g_param_spec_double ("value", NULL, NULL, 0.0, G_MAXDOUBLE, 0.0, G_PARAM_READWRITE | G_PARAM_EXPLICIT_NOTIFY | G_PARAM_STATIC_STRINGS); stat_properties[STAT_PROP_MAXIMUM] = g_param_spec_double ("maximum", NULL, NULL, 0.0001, G_MAXDOUBLE, 100.0, G_PARAM_READWRITE | G_PARAM_EXPLICIT_NOTIFY | G_PARAM_STATIC_STRINGS); stat_properties[STAT_PROP_SHOW_VALUE] = g_param_spec_boolean ("show-value", NULL, NULL, TRUE, G_PARAM_READWRITE | G_PARAM_EXPLICIT_NOTIFY | G_PARAM_STATIC_STRINGS); g_object_class_install_properties (oc, STAT_N_PROPS, stat_properties); gtk_widget_class_set_layout_manager_type (wc, GTK_TYPE_BIN_LAYOUT); gtk_widget_class_set_css_name (wc, "awrastatbar"); gtk_widget_class_set_accessible_role (wc, GTK_ACCESSIBLE_ROLE_METER); }
static void awra_stat_bar_init (AwraStatBar *self) { GtkWidget *head = gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 0); self->maximum = 100.0; self->show_value = TRUE; self->root = GTK_BOX (gtk_box_new (GTK_ORIENTATION_VERTICAL, 0)); self->label_widget = GTK_LABEL (gtk_label_new (NULL)); self->value_widget = GTK_LABEL (gtk_label_new ("0")); self->progress = AWRA_PROGRESS_BAR (awra_progress_bar_new ()); awra_box_set_spacing (self->root, AWRA_SPACING_XS); gtk_widget_set_hexpand (GTK_WIDGET (self->label_widget), TRUE); gtk_label_set_xalign (self->label_widget, 0.0f); awra_widget_set_typography (GTK_WIDGET (self->value_widget), AWRA_TYPOGRAPHY_MONOSPACE); gtk_box_append (GTK_BOX (head), GTK_WIDGET (self->label_widget)); gtk_box_append (GTK_BOX (head), GTK_WIDGET (self->value_widget)); gtk_box_append (self->root, head); gtk_box_append (self->root, GTK_WIDGET (self->progress)); gtk_widget_set_parent (GTK_WIDGET (self->root), GTK_WIDGET (self)); }
GtkWidget *awra_stat_bar_new (const char *label) { return g_object_new (AWRA_TYPE_STAT_BAR, "label", label, NULL); }
const char *awra_stat_bar_get_label (AwraStatBar *self) { g_return_val_if_fail (AWRA_IS_STAT_BAR (self), NULL); return self->label; }
void awra_stat_bar_set_label (AwraStatBar *self, const char *label) { g_return_if_fail (AWRA_IS_STAT_BAR (self)); if (g_strcmp0 (self->label, label) == 0) return; g_free (self->label); self->label = g_strdup (label); gtk_label_set_text (self->label_widget, label != NULL ? label : ""); update_stat (self); g_object_notify_by_pspec (G_OBJECT (self), stat_properties[STAT_PROP_LABEL]); }
double awra_stat_bar_get_value (AwraStatBar *self) { g_return_val_if_fail (AWRA_IS_STAT_BAR (self), 0.0); return self->value; }
void awra_stat_bar_set_value (AwraStatBar *self, double value) { g_return_if_fail (AWRA_IS_STAT_BAR (self)); value = MAX (0.0, value); if (self->value == value) return; self->value = value; update_stat (self); g_object_notify_by_pspec (G_OBJECT (self), stat_properties[STAT_PROP_VALUE]); }
double awra_stat_bar_get_maximum (AwraStatBar *self) { g_return_val_if_fail (AWRA_IS_STAT_BAR (self), 0.0); return self->maximum; }
void awra_stat_bar_set_maximum (AwraStatBar *self, double maximum) { g_return_if_fail (AWRA_IS_STAT_BAR (self)); g_return_if_fail (maximum > 0.0); if (self->maximum == maximum) return; self->maximum = maximum; update_stat (self); g_object_notify_by_pspec (G_OBJECT (self), stat_properties[STAT_PROP_MAXIMUM]); }
gboolean awra_stat_bar_get_show_value (AwraStatBar *self) { g_return_val_if_fail (AWRA_IS_STAT_BAR (self), FALSE); return self->show_value; }
void awra_stat_bar_set_show_value (AwraStatBar *self, gboolean show_value) { g_return_if_fail (AWRA_IS_STAT_BAR (self)); show_value = !!show_value; if (self->show_value == show_value) return; self->show_value = show_value; update_stat (self); g_object_notify_by_pspec (G_OBJECT (self), stat_properties[STAT_PROP_SHOW_VALUE]); }

struct _AwraBadgeGroup { GtkWidget parent_instance; GtkFlowBox *box; GPtrArray *badges; };
static GtkBuildableIface *badge_parent_buildable;
static void badge_group_buildable_init (GtkBuildableIface *iface);
G_DEFINE_FINAL_TYPE_WITH_CODE (AwraBadgeGroup, awra_badge_group, GTK_TYPE_WIDGET, G_IMPLEMENT_INTERFACE (GTK_TYPE_BUILDABLE, badge_group_buildable_init))
static void badge_group_dispose (GObject *object) { AwraBadgeGroup *self = AWRA_BADGE_GROUP (object); if (self->box != NULL) { gtk_widget_unparent (GTK_WIDGET (self->box)); self->box = NULL; } g_clear_pointer (&self->badges, g_ptr_array_unref); G_OBJECT_CLASS (awra_badge_group_parent_class)->dispose (object); }
static void badge_group_snapshot (GtkWidget *widget, GtkSnapshot *snapshot) { gtk_widget_snapshot_child (widget, GTK_WIDGET (AWRA_BADGE_GROUP (widget)->box), snapshot); }
static void awra_badge_group_class_init (AwraBadgeGroupClass *klass) { GObjectClass *oc = G_OBJECT_CLASS (klass); GtkWidgetClass *wc = GTK_WIDGET_CLASS (klass); oc->dispose = badge_group_dispose; wc->snapshot = badge_group_snapshot; gtk_widget_class_set_layout_manager_type (wc, GTK_TYPE_BIN_LAYOUT); gtk_widget_class_set_css_name (wc, "awrabadgegroup"); gtk_widget_class_set_accessible_role (wc, GTK_ACCESSIBLE_ROLE_GROUP); }
static void awra_badge_group_init (AwraBadgeGroup *self) { self->badges = g_ptr_array_new (); self->box = GTK_FLOW_BOX (gtk_flow_box_new ()); gtk_flow_box_set_selection_mode (self->box, GTK_SELECTION_NONE); gtk_flow_box_set_row_spacing (self->box, 6); gtk_flow_box_set_column_spacing (self->box, 6); gtk_widget_set_parent (GTK_WIDGET (self->box), GTK_WIDGET (self)); }
static void badge_buildable_add (GtkBuildable *buildable, GtkBuilder *builder, GObject *child, const char *type) { if (g_strcmp0 (type, "badge") == 0 && AWRA_IS_BADGE (child)) awra_badge_group_append (AWRA_BADGE_GROUP (buildable), AWRA_BADGE (child)); else badge_parent_buildable->add_child (buildable, builder, child, type); }
static void badge_group_buildable_init (GtkBuildableIface *iface) { badge_parent_buildable = g_type_interface_peek_parent (iface); iface->add_child = badge_buildable_add; }
GtkWidget *awra_badge_group_new (void) { return g_object_new (AWRA_TYPE_BADGE_GROUP, NULL); }
void awra_badge_group_append (AwraBadgeGroup *self, AwraBadge *badge) { g_return_if_fail (AWRA_IS_BADGE_GROUP (self)); g_return_if_fail (AWRA_IS_BADGE (badge)); g_return_if_fail (gtk_widget_get_parent (GTK_WIDGET (badge)) == NULL); g_ptr_array_add (self->badges, badge); gtk_flow_box_append (self->box, GTK_WIDGET (badge)); }
void awra_badge_group_remove (AwraBadgeGroup *self, AwraBadge *badge) { guint pos; g_return_if_fail (AWRA_IS_BADGE_GROUP (self)); if (!g_ptr_array_find (self->badges, badge, &pos)) return; GtkWidget *child = gtk_widget_get_parent (GTK_WIDGET (badge)); if (GTK_IS_FLOW_BOX_CHILD (child)) gtk_flow_box_remove (self->box, child); g_ptr_array_remove_index (self->badges, pos); }
guint awra_badge_group_get_n_badges (AwraBadgeGroup *self) { g_return_val_if_fail (AWRA_IS_BADGE_GROUP (self), 0); return self->badges->len; }
AwraBadge *awra_badge_group_get_badge (AwraBadgeGroup *self, guint position) { g_return_val_if_fail (AWRA_IS_BADGE_GROUP (self), NULL); return position < self->badges->len ? g_ptr_array_index (self->badges, position) : NULL; }

struct _AwraMetadataGroup { GtkWidget parent_instance; GtkBox *root; GtkLabel *title_widget; GPtrArray *rows; char *title; };
enum { META_PROP_0, META_PROP_TITLE, META_N_PROPS };
static GParamSpec *meta_properties[META_N_PROPS];
static GtkBuildableIface *meta_parent_buildable;
static void metadata_buildable_init (GtkBuildableIface *iface);
G_DEFINE_FINAL_TYPE_WITH_CODE (AwraMetadataGroup, awra_metadata_group, GTK_TYPE_WIDGET, G_IMPLEMENT_INTERFACE (GTK_TYPE_BUILDABLE, metadata_buildable_init))
static void metadata_dispose (GObject *object) { AwraMetadataGroup *self = AWRA_METADATA_GROUP (object); if (self->root != NULL) { gtk_widget_unparent (GTK_WIDGET (self->root)); self->root = NULL; } g_clear_pointer (&self->rows, g_ptr_array_unref); G_OBJECT_CLASS (awra_metadata_group_parent_class)->dispose (object); }
static void metadata_finalize (GObject *object) { g_free (AWRA_METADATA_GROUP (object)->title); G_OBJECT_CLASS (awra_metadata_group_parent_class)->finalize (object); }
static void metadata_snapshot (GtkWidget *widget, GtkSnapshot *snapshot) { gtk_widget_snapshot_child (widget, GTK_WIDGET (AWRA_METADATA_GROUP (widget)->root), snapshot); }
static void metadata_get_property (GObject *object, guint id, GValue *value, GParamSpec *pspec) { if (id == META_PROP_TITLE) g_value_set_string (value, AWRA_METADATA_GROUP (object)->title); else G_OBJECT_WARN_INVALID_PROPERTY_ID (object, id, pspec); }
static void metadata_set_property (GObject *object, guint id, const GValue *value, GParamSpec *pspec) { if (id == META_PROP_TITLE) awra_metadata_group_set_title (AWRA_METADATA_GROUP (object), g_value_get_string (value)); else G_OBJECT_WARN_INVALID_PROPERTY_ID (object, id, pspec); }
static void awra_metadata_group_class_init (AwraMetadataGroupClass *klass) { GObjectClass *oc = G_OBJECT_CLASS (klass); GtkWidgetClass *wc = GTK_WIDGET_CLASS (klass); oc->dispose = metadata_dispose; oc->finalize = metadata_finalize; oc->get_property = metadata_get_property; oc->set_property = metadata_set_property; wc->snapshot = metadata_snapshot; meta_properties[META_PROP_TITLE] = g_param_spec_string ("title", NULL, NULL, NULL, G_PARAM_READWRITE | G_PARAM_EXPLICIT_NOTIFY | G_PARAM_STATIC_STRINGS); g_object_class_install_properties (oc, META_N_PROPS, meta_properties); gtk_widget_class_set_layout_manager_type (wc, GTK_TYPE_BIN_LAYOUT); gtk_widget_class_set_css_name (wc, "awrametadatagroup"); gtk_widget_class_set_accessible_role (wc, GTK_ACCESSIBLE_ROLE_GROUP); }
static void awra_metadata_group_init (AwraMetadataGroup *self) { self->rows = g_ptr_array_new (); self->root = GTK_BOX (gtk_box_new (GTK_ORIENTATION_VERTICAL, 0)); self->title_widget = GTK_LABEL (gtk_label_new (NULL)); awra_widget_set_typography (GTK_WIDGET (self->title_widget), AWRA_TYPOGRAPHY_TITLE_3); gtk_label_set_xalign (self->title_widget, 0.0f); gtk_widget_set_visible (GTK_WIDGET (self->title_widget), FALSE); awra_box_set_spacing (self->root, AWRA_SPACING_SM); gtk_box_append (self->root, GTK_WIDGET (self->title_widget)); gtk_widget_set_parent (GTK_WIDGET (self->root), GTK_WIDGET (self)); }
static void metadata_buildable_add (GtkBuildable *buildable, GtkBuilder *builder, GObject *child, const char *type) { if (g_strcmp0 (type, "row") == 0 && AWRA_IS_METRIC_ROW (child)) awra_metadata_group_append_row (AWRA_METADATA_GROUP (buildable), AWRA_METRIC_ROW (child)); else meta_parent_buildable->add_child (buildable, builder, child, type); }
static void metadata_buildable_init (GtkBuildableIface *iface) { meta_parent_buildable = g_type_interface_peek_parent (iface); iface->add_child = metadata_buildable_add; }
GtkWidget *awra_metadata_group_new (void) { return g_object_new (AWRA_TYPE_METADATA_GROUP, NULL); }
const char *awra_metadata_group_get_title (AwraMetadataGroup *self) { g_return_val_if_fail (AWRA_IS_METADATA_GROUP (self), NULL); return self->title; }
void awra_metadata_group_set_title (AwraMetadataGroup *self, const char *title) { g_return_if_fail (AWRA_IS_METADATA_GROUP (self)); if (g_strcmp0 (self->title, title) == 0) return; g_free (self->title); self->title = g_strdup (title); gtk_label_set_text (self->title_widget, title != NULL ? title : ""); gtk_widget_set_visible (GTK_WIDGET (self->title_widget), title != NULL && *title != '\0'); g_object_notify_by_pspec (G_OBJECT (self), meta_properties[META_PROP_TITLE]); }
AwraMetricRow *awra_metadata_group_append (AwraMetadataGroup *self, const char *label, const char *value) { AwraMetricRow *row; g_return_val_if_fail (AWRA_IS_METADATA_GROUP (self), NULL); row = AWRA_METRIC_ROW (awra_metric_row_new (label, value)); awra_metadata_group_append_row (self, row); return row; }
void awra_metadata_group_append_row (AwraMetadataGroup *self, AwraMetricRow *row) { g_return_if_fail (AWRA_IS_METADATA_GROUP (self)); g_return_if_fail (AWRA_IS_METRIC_ROW (row)); g_return_if_fail (gtk_widget_get_parent (GTK_WIDGET (row)) == NULL); g_ptr_array_add (self->rows, row); gtk_box_append (self->root, GTK_WIDGET (row)); }
void awra_metadata_group_remove_row (AwraMetadataGroup *self, AwraMetricRow *row) { guint pos; g_return_if_fail (AWRA_IS_METADATA_GROUP (self)); if (!g_ptr_array_find (self->rows, row, &pos)) return; gtk_box_remove (self->root, GTK_WIDGET (row)); g_ptr_array_remove_index (self->rows, pos); }
guint awra_metadata_group_get_n_rows (AwraMetadataGroup *self) { g_return_val_if_fail (AWRA_IS_METADATA_GROUP (self), 0); return self->rows->len; }
AwraMetricRow *awra_metadata_group_get_row (AwraMetadataGroup *self, guint position) { g_return_val_if_fail (AWRA_IS_METADATA_GROUP (self), NULL); return position < self->rows->len ? g_ptr_array_index (self->rows, position) : NULL; }
