// This file was generated by gir (https://github.com/gtk-rs/gir)
// from build
// from subprojects/gir-files
// DO NOT EDIT

#![cfg(unix)]

use awra_sys::*;
use std::env;
use std::error::Error;
use std::ffi::OsString;
use std::mem::{align_of, size_of};
use std::path::Path;
use std::process::{Command, Stdio};
use std::str;
use tempfile::Builder;

static PACKAGES: &[&str] = &["awra-1"];

#[derive(Clone, Debug)]
struct Compiler {
    pub args: Vec<String>,
}

impl Compiler {
    pub fn new() -> Result<Self, Box<dyn Error>> {
        let mut args = get_var("CC", "cc")?;
        args.push("-Wno-deprecated-declarations".to_owned());
        // For _Generic
        args.push("-std=c11".to_owned());
        // For %z support in printf when using MinGW.
        args.push("-D__USE_MINGW_ANSI_STDIO".to_owned());
        args.extend(get_var("CFLAGS", "")?);
        args.extend(get_var("CPPFLAGS", "")?);
        args.extend(pkg_config_cflags(PACKAGES)?);
        Ok(Self { args })
    }

    pub fn compile(&self, src: &Path, out: &Path) -> Result<(), Box<dyn Error>> {
        let mut cmd = self.to_command();
        cmd.arg(src);
        cmd.arg("-o");
        cmd.arg(out);
        let status = cmd.spawn()?.wait()?;
        if !status.success() {
            return Err(format!("compilation command {cmd:?} failed, {status}").into());
        }
        Ok(())
    }

    fn to_command(&self) -> Command {
        let mut cmd = Command::new(&self.args[0]);
        cmd.args(&self.args[1..]);
        cmd
    }
}

fn get_var(name: &str, default: &str) -> Result<Vec<String>, Box<dyn Error>> {
    match env::var(name) {
        Ok(value) => Ok(shell_words::split(&value)?),
        Err(env::VarError::NotPresent) => Ok(shell_words::split(default)?),
        Err(err) => Err(format!("{name} {err}").into()),
    }
}

fn pkg_config_cflags(packages: &[&str]) -> Result<Vec<String>, Box<dyn Error>> {
    if packages.is_empty() {
        return Ok(Vec::new());
    }
    let pkg_config = env::var_os("PKG_CONFIG").unwrap_or_else(|| OsString::from("pkg-config"));
    let mut cmd = Command::new(pkg_config);
    cmd.arg("--cflags");
    cmd.args(packages);
    cmd.stderr(Stdio::inherit());
    let out = cmd.output()?;
    if !out.status.success() {
        let (status, stdout) = (out.status, String::from_utf8_lossy(&out.stdout));
        return Err(format!("command {cmd:?} failed, {status:?}\nstdout: {stdout}").into());
    }
    let stdout = str::from_utf8(&out.stdout)?;
    Ok(shell_words::split(stdout.trim())?)
}

#[derive(Copy, Clone, Debug, Eq, PartialEq)]
struct Layout {
    size: usize,
    alignment: usize,
}

#[derive(Copy, Clone, Debug, Default, Eq, PartialEq)]
struct Results {
    /// Number of successfully completed tests.
    passed: usize,
    /// Total number of failed tests (including those that failed to compile).
    failed: usize,
}

impl Results {
    fn record_passed(&mut self) {
        self.passed += 1;
    }
    fn record_failed(&mut self) {
        self.failed += 1;
    }
    fn summary(&self) -> String {
        format!("{} passed; {} failed", self.passed, self.failed)
    }
    fn expect_total_success(&self) {
        if self.failed == 0 {
            println!("OK: {}", self.summary());
        } else {
            panic!("FAILED: {}", self.summary());
        };
    }
}

#[test]
fn cross_validate_constants_with_c() {
    let mut c_constants: Vec<(String, String)> = Vec::new();

    for l in get_c_output("constant").unwrap().lines() {
        let (name, value) = l.split_once(';').expect("Missing ';' separator");
        c_constants.push((name.to_owned(), value.to_owned()));
    }

    let mut results = Results::default();

    for ((rust_name, rust_value), (c_name, c_value)) in
        RUST_CONSTANTS.iter().zip(c_constants.iter())
    {
        if rust_name != c_name {
            results.record_failed();
            eprintln!("Name mismatch:\nRust: {rust_name:?}\nC:    {c_name:?}");
            continue;
        }

        if rust_value != c_value {
            results.record_failed();
            eprintln!(
                "Constant value mismatch for {rust_name}\nRust: {rust_value:?}\nC:    {c_value:?}",
            );
            continue;
        }

        results.record_passed();
    }

    results.expect_total_success();
}

#[test]
fn cross_validate_layout_with_c() {
    let mut c_layouts = Vec::new();

    for l in get_c_output("layout").unwrap().lines() {
        let (name, value) = l.split_once(';').expect("Missing first ';' separator");
        let (size, alignment) = value.split_once(';').expect("Missing second ';' separator");
        let size = size.parse().expect("Failed to parse size");
        let alignment = alignment.parse().expect("Failed to parse alignment");
        c_layouts.push((name.to_owned(), Layout { size, alignment }));
    }

    let mut results = Results::default();

    for ((rust_name, rust_layout), (c_name, c_layout)) in RUST_LAYOUTS.iter().zip(c_layouts.iter())
    {
        if rust_name != c_name {
            results.record_failed();
            eprintln!("Name mismatch:\nRust: {rust_name:?}\nC:    {c_name:?}");
            continue;
        }

        if rust_layout != c_layout {
            results.record_failed();
            eprintln!("Layout mismatch for {rust_name}\nRust: {rust_layout:?}\nC:    {c_layout:?}",);
            continue;
        }

        results.record_passed();
    }

    results.expect_total_success();
}

fn get_c_output(name: &str) -> Result<String, Box<dyn Error>> {
    let tmpdir = Builder::new().prefix("abi").tempdir()?;
    let exe = tmpdir.path().join(name);
    let c_file = Path::new("tests").join(name).with_extension("c");

    let cc = Compiler::new().expect("configured compiler");
    cc.compile(&c_file, &exe)?;

    let mut cmd = Command::new(exe);
    cmd.stderr(Stdio::inherit());
    let out = cmd.output()?;
    if !out.status.success() {
        let (status, stdout) = (out.status, String::from_utf8_lossy(&out.stdout));
        return Err(format!("command {cmd:?} failed, {status:?}\nstdout: {stdout}").into());
    }

    Ok(String::from_utf8(out.stdout)?)
}

const RUST_LAYOUTS: &[(&str, Layout)] = &[
    (
        "AwraAccentSource",
        Layout {
            size: size_of::<AwraAccentSource>(),
            alignment: align_of::<AwraAccentSource>(),
        },
    ),
    (
        "AwraActionRowClass",
        Layout {
            size: size_of::<AwraActionRowClass>(),
            alignment: align_of::<AwraActionRowClass>(),
        },
    ),
    (
        "AwraAppearance",
        Layout {
            size: size_of::<AwraAppearance>(),
            alignment: align_of::<AwraAppearance>(),
        },
    ),
    (
        "AwraBadgeAppearance",
        Layout {
            size: size_of::<AwraBadgeAppearance>(),
            alignment: align_of::<AwraBadgeAppearance>(),
        },
    ),
    (
        "AwraBadgeClass",
        Layout {
            size: size_of::<AwraBadgeClass>(),
            alignment: align_of::<AwraBadgeClass>(),
        },
    ),
    (
        "AwraBadgeGroupClass",
        Layout {
            size: size_of::<AwraBadgeGroupClass>(),
            alignment: align_of::<AwraBadgeGroupClass>(),
        },
    ),
    (
        "AwraBreadcrumbBarClass",
        Layout {
            size: size_of::<AwraBreadcrumbBarClass>(),
            alignment: align_of::<AwraBreadcrumbBarClass>(),
        },
    ),
    (
        "AwraBreadcrumbItemClass",
        Layout {
            size: size_of::<AwraBreadcrumbItemClass>(),
            alignment: align_of::<AwraBreadcrumbItemClass>(),
        },
    ),
    (
        "AwraButtonAppearance",
        Layout {
            size: size_of::<AwraButtonAppearance>(),
            alignment: align_of::<AwraButtonAppearance>(),
        },
    ),
    (
        "AwraButtonClass",
        Layout {
            size: size_of::<AwraButtonClass>(),
            alignment: align_of::<AwraButtonClass>(),
        },
    ),
    (
        "AwraCardAppearance",
        Layout {
            size: size_of::<AwraCardAppearance>(),
            alignment: align_of::<AwraCardAppearance>(),
        },
    ),
    (
        "AwraCardClass",
        Layout {
            size: size_of::<AwraCardClass>(),
            alignment: align_of::<AwraCardClass>(),
        },
    ),
    (
        "AwraCheckButtonClass",
        Layout {
            size: size_of::<AwraCheckButtonClass>(),
            alignment: align_of::<AwraCheckButtonClass>(),
        },
    ),
    (
        "AwraChoiceGroupClass",
        Layout {
            size: size_of::<AwraChoiceGroupClass>(),
            alignment: align_of::<AwraChoiceGroupClass>(),
        },
    ),
    (
        "AwraCommandPaletteClass",
        Layout {
            size: size_of::<AwraCommandPaletteClass>(),
            alignment: align_of::<AwraCommandPaletteClass>(),
        },
    ),
    (
        "AwraContextClass",
        Layout {
            size: size_of::<AwraContextClass>(),
            alignment: align_of::<AwraContextClass>(),
        },
    ),
    (
        "AwraDataColumnClass",
        Layout {
            size: size_of::<AwraDataColumnClass>(),
            alignment: align_of::<AwraDataColumnClass>(),
        },
    ),
    (
        "AwraDataViewClass",
        Layout {
            size: size_of::<AwraDataViewClass>(),
            alignment: align_of::<AwraDataViewClass>(),
        },
    ),
    (
        "AwraDataViewState",
        Layout {
            size: size_of::<AwraDataViewState>(),
            alignment: align_of::<AwraDataViewState>(),
        },
    ),
    (
        "AwraDetailPaneClass",
        Layout {
            size: size_of::<AwraDetailPaneClass>(),
            alignment: align_of::<AwraDetailPaneClass>(),
        },
    ),
    (
        "AwraDiagnosticsClass",
        Layout {
            size: size_of::<AwraDiagnosticsClass>(),
            alignment: align_of::<AwraDiagnosticsClass>(),
        },
    ),
    (
        "AwraDialogClass",
        Layout {
            size: size_of::<AwraDialogClass>(),
            alignment: align_of::<AwraDialogClass>(),
        },
    ),
    (
        "AwraDropdownClass",
        Layout {
            size: size_of::<AwraDropdownClass>(),
            alignment: align_of::<AwraDropdownClass>(),
        },
    ),
    (
        "AwraEdgePanelClass",
        Layout {
            size: size_of::<AwraEdgePanelClass>(),
            alignment: align_of::<AwraEdgePanelClass>(),
        },
    ),
    (
        "AwraEffectCapability",
        Layout {
            size: size_of::<AwraEffectCapability>(),
            alignment: align_of::<AwraEffectCapability>(),
        },
    ),
    (
        "AwraElevation",
        Layout {
            size: size_of::<AwraElevation>(),
            alignment: align_of::<AwraElevation>(),
        },
    ),
    (
        "AwraEmptyStateClass",
        Layout {
            size: size_of::<AwraEmptyStateClass>(),
            alignment: align_of::<AwraEmptyStateClass>(),
        },
    ),
    (
        "AwraEntryClass",
        Layout {
            size: size_of::<AwraEntryClass>(),
            alignment: align_of::<AwraEntryClass>(),
        },
    ),
    (
        "AwraErrorStateClass",
        Layout {
            size: size_of::<AwraErrorStateClass>(),
            alignment: align_of::<AwraErrorStateClass>(),
        },
    ),
    (
        "AwraFilterBarClass",
        Layout {
            size: size_of::<AwraFilterBarClass>(),
            alignment: align_of::<AwraFilterBarClass>(),
        },
    ),
    (
        "AwraFormClass",
        Layout {
            size: size_of::<AwraFormClass>(),
            alignment: align_of::<AwraFormClass>(),
        },
    ),
    (
        "AwraFormRowClass",
        Layout {
            size: size_of::<AwraFormRowClass>(),
            alignment: align_of::<AwraFormRowClass>(),
        },
    ),
    (
        "AwraHeaderClass",
        Layout {
            size: size_of::<AwraHeaderClass>(),
            alignment: align_of::<AwraHeaderClass>(),
        },
    ),
    (
        "AwraInspectorClass",
        Layout {
            size: size_of::<AwraInspectorClass>(),
            alignment: align_of::<AwraInspectorClass>(),
        },
    ),
    (
        "AwraLayoutMode",
        Layout {
            size: size_of::<AwraLayoutMode>(),
            alignment: align_of::<AwraLayoutMode>(),
        },
    ),
    (
        "AwraLayoutPreset",
        Layout {
            size: size_of::<AwraLayoutPreset>(),
            alignment: align_of::<AwraLayoutPreset>(),
        },
    ),
    (
        "AwraListViewClass",
        Layout {
            size: size_of::<AwraListViewClass>(),
            alignment: align_of::<AwraListViewClass>(),
        },
    ),
    (
        "AwraLoadingStateClass",
        Layout {
            size: size_of::<AwraLoadingStateClass>(),
            alignment: align_of::<AwraLoadingStateClass>(),
        },
    ),
    (
        "AwraMasterDetailClass",
        Layout {
            size: size_of::<AwraMasterDetailClass>(),
            alignment: align_of::<AwraMasterDetailClass>(),
        },
    ),
    (
        "AwraMasterDetailPane",
        Layout {
            size: size_of::<AwraMasterDetailPane>(),
            alignment: align_of::<AwraMasterDetailPane>(),
        },
    ),
    (
        "AwraMaterialClass",
        Layout {
            size: size_of::<AwraMaterialClass>(),
            alignment: align_of::<AwraMaterialClass>(),
        },
    ),
    (
        "AwraMaterialKind",
        Layout {
            size: size_of::<AwraMaterialKind>(),
            alignment: align_of::<AwraMaterialKind>(),
        },
    ),
    (
        "AwraMaterialPreset",
        Layout {
            size: size_of::<AwraMaterialPreset>(),
            alignment: align_of::<AwraMaterialPreset>(),
        },
    ),
    (
        "AwraMaterialResolutionClass",
        Layout {
            size: size_of::<AwraMaterialResolutionClass>(),
            alignment: align_of::<AwraMaterialResolutionClass>(),
        },
    ),
    (
        "AwraMenuButtonClass",
        Layout {
            size: size_of::<AwraMenuButtonClass>(),
            alignment: align_of::<AwraMenuButtonClass>(),
        },
    ),
    (
        "AwraMetadataGroupClass",
        Layout {
            size: size_of::<AwraMetadataGroupClass>(),
            alignment: align_of::<AwraMetadataGroupClass>(),
        },
    ),
    (
        "AwraMetricRowClass",
        Layout {
            size: size_of::<AwraMetricRowClass>(),
            alignment: align_of::<AwraMetricRowClass>(),
        },
    ),
    (
        "AwraMotionPreset",
        Layout {
            size: size_of::<AwraMotionPreset>(),
            alignment: align_of::<AwraMotionPreset>(),
        },
    ),
    (
        "AwraNavigationItemClass",
        Layout {
            size: size_of::<AwraNavigationItemClass>(),
            alignment: align_of::<AwraNavigationItemClass>(),
        },
    ),
    (
        "AwraNavigationViewClass",
        Layout {
            size: size_of::<AwraNavigationViewClass>(),
            alignment: align_of::<AwraNavigationViewClass>(),
        },
    ),
    (
        "AwraPageClass",
        Layout {
            size: size_of::<AwraPageClass>(),
            alignment: align_of::<AwraPageClass>(),
        },
    ),
    (
        "AwraPageHeaderClass",
        Layout {
            size: size_of::<AwraPageHeaderClass>(),
            alignment: align_of::<AwraPageHeaderClass>(),
        },
    ),
    (
        "AwraPanelEdge",
        Layout {
            size: size_of::<AwraPanelEdge>(),
            alignment: align_of::<AwraPanelEdge>(),
        },
    ),
    (
        "AwraPasswordEntryClass",
        Layout {
            size: size_of::<AwraPasswordEntryClass>(),
            alignment: align_of::<AwraPasswordEntryClass>(),
        },
    ),
    (
        "AwraPopoverClass",
        Layout {
            size: size_of::<AwraPopoverClass>(),
            alignment: align_of::<AwraPopoverClass>(),
        },
    ),
    (
        "AwraProgressBarClass",
        Layout {
            size: size_of::<AwraProgressBarClass>(),
            alignment: align_of::<AwraProgressBarClass>(),
        },
    ),
    (
        "AwraRadius",
        Layout {
            size: size_of::<AwraRadius>(),
            alignment: align_of::<AwraRadius>(),
        },
    ),
    (
        "AwraResponsiveBinClass",
        Layout {
            size: size_of::<AwraResponsiveBinClass>(),
            alignment: align_of::<AwraResponsiveBinClass>(),
        },
    ),
    (
        "AwraSearchEntryClass",
        Layout {
            size: size_of::<AwraSearchEntryClass>(),
            alignment: align_of::<AwraSearchEntryClass>(),
        },
    ),
    (
        "AwraSectionClass",
        Layout {
            size: size_of::<AwraSectionClass>(),
            alignment: align_of::<AwraSectionClass>(),
        },
    ),
    (
        "AwraSegmentedControlClass",
        Layout {
            size: size_of::<AwraSegmentedControlClass>(),
            alignment: align_of::<AwraSegmentedControlClass>(),
        },
    ),
    (
        "AwraSelectionToolbarClass",
        Layout {
            size: size_of::<AwraSelectionToolbarClass>(),
            alignment: align_of::<AwraSelectionToolbarClass>(),
        },
    ),
    (
        "AwraSidebarClass",
        Layout {
            size: size_of::<AwraSidebarClass>(),
            alignment: align_of::<AwraSidebarClass>(),
        },
    ),
    (
        "AwraSkeletonClass",
        Layout {
            size: size_of::<AwraSkeletonClass>(),
            alignment: align_of::<AwraSkeletonClass>(),
        },
    ),
    (
        "AwraSliderClass",
        Layout {
            size: size_of::<AwraSliderClass>(),
            alignment: align_of::<AwraSliderClass>(),
        },
    ),
    (
        "AwraSpacing",
        Layout {
            size: size_of::<AwraSpacing>(),
            alignment: align_of::<AwraSpacing>(),
        },
    ),
    (
        "AwraSpinButtonClass",
        Layout {
            size: size_of::<AwraSpinButtonClass>(),
            alignment: align_of::<AwraSpinButtonClass>(),
        },
    ),
    (
        "AwraSplitViewClass",
        Layout {
            size: size_of::<AwraSplitViewClass>(),
            alignment: align_of::<AwraSplitViewClass>(),
        },
    ),
    (
        "AwraStatBarClass",
        Layout {
            size: size_of::<AwraStatBarClass>(),
            alignment: align_of::<AwraStatBarClass>(),
        },
    ),
    (
        "AwraStatusAppearance",
        Layout {
            size: size_of::<AwraStatusAppearance>(),
            alignment: align_of::<AwraStatusAppearance>(),
        },
    ),
    (
        "AwraStatusBannerClass",
        Layout {
            size: size_of::<AwraStatusBannerClass>(),
            alignment: align_of::<AwraStatusBannerClass>(),
        },
    ),
    (
        "AwraStyleManagerClass",
        Layout {
            size: size_of::<AwraStyleManagerClass>(),
            alignment: align_of::<AwraStyleManagerClass>(),
        },
    ),
    (
        "AwraSurfaceClass",
        Layout {
            size: size_of::<AwraSurfaceClass>(),
            alignment: align_of::<AwraSurfaceClass>(),
        },
    ),
    (
        "AwraSurfaceCorner",
        Layout {
            size: size_of::<AwraSurfaceCorner>(),
            alignment: align_of::<AwraSurfaceCorner>(),
        },
    ),
    (
        "AwraSurfaceEdge",
        Layout {
            size: size_of::<AwraSurfaceEdge>(),
            alignment: align_of::<AwraSurfaceEdge>(),
        },
    ),
    (
        "AwraSurfaceRole",
        Layout {
            size: size_of::<AwraSurfaceRole>(),
            alignment: align_of::<AwraSurfaceRole>(),
        },
    ),
    (
        "AwraSwitchClass",
        Layout {
            size: size_of::<AwraSwitchClass>(),
            alignment: align_of::<AwraSwitchClass>(),
        },
    ),
    (
        "AwraTabViewClass",
        Layout {
            size: size_of::<AwraTabViewClass>(),
            alignment: align_of::<AwraTabViewClass>(),
        },
    ),
    (
        "AwraTagEntryClass",
        Layout {
            size: size_of::<AwraTagEntryClass>(),
            alignment: align_of::<AwraTagEntryClass>(),
        },
    ),
    (
        "AwraTextAreaClass",
        Layout {
            size: size_of::<AwraTextAreaClass>(),
            alignment: align_of::<AwraTextAreaClass>(),
        },
    ),
    (
        "AwraToastOverlayClass",
        Layout {
            size: size_of::<AwraToastOverlayClass>(),
            alignment: align_of::<AwraToastOverlayClass>(),
        },
    ),
    (
        "AwraToggleButtonClass",
        Layout {
            size: size_of::<AwraToggleButtonClass>(),
            alignment: align_of::<AwraToggleButtonClass>(),
        },
    ),
    (
        "AwraTokenSetClass",
        Layout {
            size: size_of::<AwraTokenSetClass>(),
            alignment: align_of::<AwraTokenSetClass>(),
        },
    ),
    (
        "AwraToolbarClass",
        Layout {
            size: size_of::<AwraToolbarClass>(),
            alignment: align_of::<AwraToolbarClass>(),
        },
    ),
    (
        "AwraTypography",
        Layout {
            size: size_of::<AwraTypography>(),
            alignment: align_of::<AwraTypography>(),
        },
    ),
    (
        "AwraValidationState",
        Layout {
            size: size_of::<AwraValidationState>(),
            alignment: align_of::<AwraValidationState>(),
        },
    ),
    (
        "AwraWindow",
        Layout {
            size: size_of::<AwraWindow>(),
            alignment: align_of::<AwraWindow>(),
        },
    ),
    (
        "AwraWindowClass",
        Layout {
            size: size_of::<AwraWindowClass>(),
            alignment: align_of::<AwraWindowClass>(),
        },
    ),
];

const RUST_CONSTANTS: &[(&str, &str)] = &[
    ("(gint) AWRA_ACCENT_SOURCE_CUSTOM", "2"),
    ("(gint) AWRA_ACCENT_SOURCE_DEFAULT", "1"),
    ("(gint) AWRA_ACCENT_SOURCE_SYSTEM", "0"),
    ("(gint) AWRA_APPEARANCE_DARK", "2"),
    ("(gint) AWRA_APPEARANCE_LIGHT", "1"),
    ("(gint) AWRA_APPEARANCE_SYSTEM", "0"),
    ("(gint) AWRA_BADGE_APPEARANCE_ACCENT", "1"),
    ("(gint) AWRA_BADGE_APPEARANCE_DANGER", "5"),
    ("(gint) AWRA_BADGE_APPEARANCE_INFO", "2"),
    ("(gint) AWRA_BADGE_APPEARANCE_NEUTRAL", "0"),
    ("(gint) AWRA_BADGE_APPEARANCE_SUCCESS", "3"),
    ("(gint) AWRA_BADGE_APPEARANCE_WARNING", "4"),
    ("(gint) AWRA_BUTTON_APPEARANCE_DESTRUCTIVE", "3"),
    ("(gint) AWRA_BUTTON_APPEARANCE_GHOST", "2"),
    ("(gint) AWRA_BUTTON_APPEARANCE_PRIMARY", "0"),
    ("(gint) AWRA_BUTTON_APPEARANCE_SECONDARY", "1"),
    ("(gint) AWRA_BUTTON_APPEARANCE_TOOLBAR", "4"),
    ("(gint) AWRA_CARD_APPEARANCE_PLAIN", "0"),
    ("(gint) AWRA_CARD_APPEARANCE_RAISED", "2"),
    ("(gint) AWRA_CARD_APPEARANCE_TINTED", "1"),
    ("(gint) AWRA_DATA_VIEW_STATE_CONTENT", "0"),
    ("(gint) AWRA_DATA_VIEW_STATE_EMPTY", "1"),
    ("(gint) AWRA_DATA_VIEW_STATE_ERROR", "3"),
    ("(gint) AWRA_DATA_VIEW_STATE_LOADING", "2"),
    ("(guint) AWRA_EFFECT_CAPABILITY_BLUR", "1"),
    ("(guint) AWRA_EFFECT_CAPABILITY_NONE", "0"),
    ("(gint) AWRA_ELEVATION_FLAT", "0"),
    ("(gint) AWRA_ELEVATION_FLOATING", "2"),
    ("(gint) AWRA_ELEVATION_MODAL", "3"),
    ("(gint) AWRA_ELEVATION_RAISED", "1"),
    ("(gint) AWRA_LAYOUT_MODE_COMPACT", "0"),
    ("(gint) AWRA_LAYOUT_MODE_EXPANDED", "2"),
    ("(gint) AWRA_LAYOUT_MODE_MEDIUM", "1"),
    ("(gint) AWRA_LAYOUT_PRESET_COMPACT", "0"),
    ("(gint) AWRA_LAYOUT_PRESET_CONTENT", "3"),
    ("(gint) AWRA_LAYOUT_PRESET_CONTROL_GROUP", "1"),
    ("(gint) AWRA_LAYOUT_PRESET_OVERLAY", "6"),
    ("(gint) AWRA_LAYOUT_PRESET_PAGE", "4"),
    ("(gint) AWRA_LAYOUT_PRESET_SECTION", "2"),
    ("(gint) AWRA_LAYOUT_PRESET_TOOLBAR", "5"),
    ("AWRA_MAJOR_VERSION", "1"),
    ("(gint) AWRA_MASTER_DETAIL_PANE_DETAIL", "1"),
    ("(gint) AWRA_MASTER_DETAIL_PANE_MASTER", "0"),
    ("(gint) AWRA_MATERIAL_KIND_FROSTED", "2"),
    ("(gint) AWRA_MATERIAL_KIND_LIQUID", "3"),
    ("(gint) AWRA_MATERIAL_KIND_SOLID", "0"),
    ("(gint) AWRA_MATERIAL_KIND_TRANSLUCENT", "1"),
    ("(gint) AWRA_MATERIAL_PRESET_CANVAS", "1"),
    ("(gint) AWRA_MATERIAL_PRESET_CHROME", "3"),
    ("(gint) AWRA_MATERIAL_PRESET_CONTENT", "2"),
    ("(gint) AWRA_MATERIAL_PRESET_FLOATING", "5"),
    ("(gint) AWRA_MATERIAL_PRESET_LAYER", "4"),
    ("(gint) AWRA_MATERIAL_PRESET_NONE", "0"),
    ("(gint) AWRA_MATERIAL_PRESET_OPAQUE", "6"),
    ("AWRA_MICRO_VERSION", "0"),
    ("AWRA_MINOR_VERSION", "0"),
    ("(gint) AWRA_MOTION_PRESET_FAST", "1"),
    ("(gint) AWRA_MOTION_PRESET_INSTANT", "0"),
    ("(gint) AWRA_MOTION_PRESET_NORMAL", "2"),
    ("(gint) AWRA_MOTION_PRESET_SLOW", "3"),
    ("(gint) AWRA_PANEL_EDGE_END", "1"),
    ("(gint) AWRA_PANEL_EDGE_START", "0"),
    ("(gint) AWRA_RADIUS_LARGE", "2"),
    ("(gint) AWRA_RADIUS_MEDIUM", "1"),
    ("(gint) AWRA_RADIUS_PILL", "4"),
    ("(gint) AWRA_RADIUS_SMALL", "0"),
    ("(gint) AWRA_RADIUS_WINDOW", "3"),
    ("(gint) AWRA_SPACING_LG", "3"),
    ("(gint) AWRA_SPACING_MD", "2"),
    ("(gint) AWRA_SPACING_NONE", "6"),
    ("(gint) AWRA_SPACING_SM", "1"),
    ("(gint) AWRA_SPACING_XL", "4"),
    ("(gint) AWRA_SPACING_XS", "0"),
    ("(gint) AWRA_SPACING_XXL", "5"),
    ("(gint) AWRA_STATUS_APPEARANCE_ERROR", "3"),
    ("(gint) AWRA_STATUS_APPEARANCE_INFO", "0"),
    ("(gint) AWRA_STATUS_APPEARANCE_SUCCESS", "1"),
    ("(gint) AWRA_STATUS_APPEARANCE_WARNING", "2"),
    ("(guint) AWRA_SURFACE_CORNER_ALL", "15"),
    ("(guint) AWRA_SURFACE_CORNER_BOTTOM_END", "4"),
    ("(guint) AWRA_SURFACE_CORNER_BOTTOM_START", "8"),
    ("(guint) AWRA_SURFACE_CORNER_NONE", "0"),
    ("(guint) AWRA_SURFACE_CORNER_TOP_END", "2"),
    ("(guint) AWRA_SURFACE_CORNER_TOP_START", "1"),
    ("(guint) AWRA_SURFACE_EDGE_ALL", "15"),
    ("(guint) AWRA_SURFACE_EDGE_BOTTOM", "4"),
    ("(guint) AWRA_SURFACE_EDGE_END", "2"),
    ("(guint) AWRA_SURFACE_EDGE_NONE", "0"),
    ("(guint) AWRA_SURFACE_EDGE_START", "8"),
    ("(guint) AWRA_SURFACE_EDGE_TOP", "1"),
    ("(gint) AWRA_SURFACE_ROLE_CARD", "3"),
    ("(gint) AWRA_SURFACE_ROLE_CONTENT", "1"),
    ("(gint) AWRA_SURFACE_ROLE_DIALOG", "8"),
    ("(gint) AWRA_SURFACE_ROLE_FLOATING", "5"),
    ("(gint) AWRA_SURFACE_ROLE_HUD", "10"),
    ("(gint) AWRA_SURFACE_ROLE_MENU", "7"),
    ("(gint) AWRA_SURFACE_ROLE_POPOVER", "6"),
    ("(gint) AWRA_SURFACE_ROLE_SIDEBAR", "2"),
    ("(gint) AWRA_SURFACE_ROLE_TOOLBAR", "4"),
    ("(gint) AWRA_SURFACE_ROLE_TOOLTIP", "9"),
    ("(gint) AWRA_SURFACE_ROLE_WINDOW", "0"),
    ("(gint) AWRA_TYPOGRAPHY_BODY", "0"),
    ("(gint) AWRA_TYPOGRAPHY_DISPLAY", "6"),
    ("(gint) AWRA_TYPOGRAPHY_EYEBROW", "2"),
    ("(gint) AWRA_TYPOGRAPHY_MONOSPACE", "7"),
    ("(gint) AWRA_TYPOGRAPHY_MUTED", "1"),
    ("(gint) AWRA_TYPOGRAPHY_TITLE_1", "5"),
    ("(gint) AWRA_TYPOGRAPHY_TITLE_2", "4"),
    ("(gint) AWRA_TYPOGRAPHY_TITLE_3", "3"),
    ("(gint) AWRA_VALIDATION_STATE_ERROR", "3"),
    ("(gint) AWRA_VALIDATION_STATE_NONE", "0"),
    ("(gint) AWRA_VALIDATION_STATE_SUCCESS", "1"),
    ("(gint) AWRA_VALIDATION_STATE_WARNING", "2"),
    ("AWRA_VERSION_S", "1.0.0"),
];
