// This file was generated by gir (https://github.com/gtk-rs/gir)
// from build
// from subprojects/gir-files
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "AwraAccentSource", sizeof(AwraAccentSource), alignof(AwraAccentSource));
    printf("%s;%zu;%zu\n", "AwraActionRowClass", sizeof(AwraActionRowClass), alignof(AwraActionRowClass));
    printf("%s;%zu;%zu\n", "AwraAppearance", sizeof(AwraAppearance), alignof(AwraAppearance));
    printf("%s;%zu;%zu\n", "AwraBadgeAppearance", sizeof(AwraBadgeAppearance), alignof(AwraBadgeAppearance));
    printf("%s;%zu;%zu\n", "AwraBadgeClass", sizeof(AwraBadgeClass), alignof(AwraBadgeClass));
    printf("%s;%zu;%zu\n", "AwraBadgeGroupClass", sizeof(AwraBadgeGroupClass), alignof(AwraBadgeGroupClass));
    printf("%s;%zu;%zu\n", "AwraBreadcrumbBarClass", sizeof(AwraBreadcrumbBarClass), alignof(AwraBreadcrumbBarClass));
    printf("%s;%zu;%zu\n", "AwraBreadcrumbItemClass", sizeof(AwraBreadcrumbItemClass), alignof(AwraBreadcrumbItemClass));
    printf("%s;%zu;%zu\n", "AwraButtonAppearance", sizeof(AwraButtonAppearance), alignof(AwraButtonAppearance));
    printf("%s;%zu;%zu\n", "AwraButtonClass", sizeof(AwraButtonClass), alignof(AwraButtonClass));
    printf("%s;%zu;%zu\n", "AwraCardAppearance", sizeof(AwraCardAppearance), alignof(AwraCardAppearance));
    printf("%s;%zu;%zu\n", "AwraCardClass", sizeof(AwraCardClass), alignof(AwraCardClass));
    printf("%s;%zu;%zu\n", "AwraCheckButtonClass", sizeof(AwraCheckButtonClass), alignof(AwraCheckButtonClass));
    printf("%s;%zu;%zu\n", "AwraChoiceGroupClass", sizeof(AwraChoiceGroupClass), alignof(AwraChoiceGroupClass));
    printf("%s;%zu;%zu\n", "AwraCommandPaletteClass", sizeof(AwraCommandPaletteClass), alignof(AwraCommandPaletteClass));
    printf("%s;%zu;%zu\n", "AwraContextClass", sizeof(AwraContextClass), alignof(AwraContextClass));
    printf("%s;%zu;%zu\n", "AwraDataColumnClass", sizeof(AwraDataColumnClass), alignof(AwraDataColumnClass));
    printf("%s;%zu;%zu\n", "AwraDataViewClass", sizeof(AwraDataViewClass), alignof(AwraDataViewClass));
    printf("%s;%zu;%zu\n", "AwraDataViewState", sizeof(AwraDataViewState), alignof(AwraDataViewState));
    printf("%s;%zu;%zu\n", "AwraDetailPaneClass", sizeof(AwraDetailPaneClass), alignof(AwraDetailPaneClass));
    printf("%s;%zu;%zu\n", "AwraDiagnosticsClass", sizeof(AwraDiagnosticsClass), alignof(AwraDiagnosticsClass));
    printf("%s;%zu;%zu\n", "AwraDialogClass", sizeof(AwraDialogClass), alignof(AwraDialogClass));
    printf("%s;%zu;%zu\n", "AwraDropdownClass", sizeof(AwraDropdownClass), alignof(AwraDropdownClass));
    printf("%s;%zu;%zu\n", "AwraEdgePanelClass", sizeof(AwraEdgePanelClass), alignof(AwraEdgePanelClass));
    printf("%s;%zu;%zu\n", "AwraEffectCapability", sizeof(AwraEffectCapability), alignof(AwraEffectCapability));
    printf("%s;%zu;%zu\n", "AwraElevation", sizeof(AwraElevation), alignof(AwraElevation));
    printf("%s;%zu;%zu\n", "AwraEmptyStateClass", sizeof(AwraEmptyStateClass), alignof(AwraEmptyStateClass));
    printf("%s;%zu;%zu\n", "AwraEntryClass", sizeof(AwraEntryClass), alignof(AwraEntryClass));
    printf("%s;%zu;%zu\n", "AwraErrorStateClass", sizeof(AwraErrorStateClass), alignof(AwraErrorStateClass));
    printf("%s;%zu;%zu\n", "AwraFilterBarClass", sizeof(AwraFilterBarClass), alignof(AwraFilterBarClass));
    printf("%s;%zu;%zu\n", "AwraFormClass", sizeof(AwraFormClass), alignof(AwraFormClass));
    printf("%s;%zu;%zu\n", "AwraFormRowClass", sizeof(AwraFormRowClass), alignof(AwraFormRowClass));
    printf("%s;%zu;%zu\n", "AwraHeaderClass", sizeof(AwraHeaderClass), alignof(AwraHeaderClass));
    printf("%s;%zu;%zu\n", "AwraInspectorClass", sizeof(AwraInspectorClass), alignof(AwraInspectorClass));
    printf("%s;%zu;%zu\n", "AwraLayoutMode", sizeof(AwraLayoutMode), alignof(AwraLayoutMode));
    printf("%s;%zu;%zu\n", "AwraLayoutPreset", sizeof(AwraLayoutPreset), alignof(AwraLayoutPreset));
    printf("%s;%zu;%zu\n", "AwraListViewClass", sizeof(AwraListViewClass), alignof(AwraListViewClass));
    printf("%s;%zu;%zu\n", "AwraLoadingStateClass", sizeof(AwraLoadingStateClass), alignof(AwraLoadingStateClass));
    printf("%s;%zu;%zu\n", "AwraMasterDetailClass", sizeof(AwraMasterDetailClass), alignof(AwraMasterDetailClass));
    printf("%s;%zu;%zu\n", "AwraMasterDetailPane", sizeof(AwraMasterDetailPane), alignof(AwraMasterDetailPane));
    printf("%s;%zu;%zu\n", "AwraMaterialClass", sizeof(AwraMaterialClass), alignof(AwraMaterialClass));
    printf("%s;%zu;%zu\n", "AwraMaterialKind", sizeof(AwraMaterialKind), alignof(AwraMaterialKind));
    printf("%s;%zu;%zu\n", "AwraMaterialPreset", sizeof(AwraMaterialPreset), alignof(AwraMaterialPreset));
    printf("%s;%zu;%zu\n", "AwraMaterialResolutionClass", sizeof(AwraMaterialResolutionClass), alignof(AwraMaterialResolutionClass));
    printf("%s;%zu;%zu\n", "AwraMenuButtonClass", sizeof(AwraMenuButtonClass), alignof(AwraMenuButtonClass));
    printf("%s;%zu;%zu\n", "AwraMetadataGroupClass", sizeof(AwraMetadataGroupClass), alignof(AwraMetadataGroupClass));
    printf("%s;%zu;%zu\n", "AwraMetricRowClass", sizeof(AwraMetricRowClass), alignof(AwraMetricRowClass));
    printf("%s;%zu;%zu\n", "AwraMotionPreset", sizeof(AwraMotionPreset), alignof(AwraMotionPreset));
    printf("%s;%zu;%zu\n", "AwraNavigationItemClass", sizeof(AwraNavigationItemClass), alignof(AwraNavigationItemClass));
    printf("%s;%zu;%zu\n", "AwraNavigationViewClass", sizeof(AwraNavigationViewClass), alignof(AwraNavigationViewClass));
    printf("%s;%zu;%zu\n", "AwraPageClass", sizeof(AwraPageClass), alignof(AwraPageClass));
    printf("%s;%zu;%zu\n", "AwraPageHeaderClass", sizeof(AwraPageHeaderClass), alignof(AwraPageHeaderClass));
    printf("%s;%zu;%zu\n", "AwraPanelEdge", sizeof(AwraPanelEdge), alignof(AwraPanelEdge));
    printf("%s;%zu;%zu\n", "AwraPasswordEntryClass", sizeof(AwraPasswordEntryClass), alignof(AwraPasswordEntryClass));
    printf("%s;%zu;%zu\n", "AwraPopoverClass", sizeof(AwraPopoverClass), alignof(AwraPopoverClass));
    printf("%s;%zu;%zu\n", "AwraProgressBarClass", sizeof(AwraProgressBarClass), alignof(AwraProgressBarClass));
    printf("%s;%zu;%zu\n", "AwraRadius", sizeof(AwraRadius), alignof(AwraRadius));
    printf("%s;%zu;%zu\n", "AwraResponsiveBinClass", sizeof(AwraResponsiveBinClass), alignof(AwraResponsiveBinClass));
    printf("%s;%zu;%zu\n", "AwraSearchEntryClass", sizeof(AwraSearchEntryClass), alignof(AwraSearchEntryClass));
    printf("%s;%zu;%zu\n", "AwraSectionClass", sizeof(AwraSectionClass), alignof(AwraSectionClass));
    printf("%s;%zu;%zu\n", "AwraSegmentedControlClass", sizeof(AwraSegmentedControlClass), alignof(AwraSegmentedControlClass));
    printf("%s;%zu;%zu\n", "AwraSelectionToolbarClass", sizeof(AwraSelectionToolbarClass), alignof(AwraSelectionToolbarClass));
    printf("%s;%zu;%zu\n", "AwraSidebarClass", sizeof(AwraSidebarClass), alignof(AwraSidebarClass));
    printf("%s;%zu;%zu\n", "AwraSkeletonClass", sizeof(AwraSkeletonClass), alignof(AwraSkeletonClass));
    printf("%s;%zu;%zu\n", "AwraSliderClass", sizeof(AwraSliderClass), alignof(AwraSliderClass));
    printf("%s;%zu;%zu\n", "AwraSpacing", sizeof(AwraSpacing), alignof(AwraSpacing));
    printf("%s;%zu;%zu\n", "AwraSpinButtonClass", sizeof(AwraSpinButtonClass), alignof(AwraSpinButtonClass));
    printf("%s;%zu;%zu\n", "AwraSplitViewClass", sizeof(AwraSplitViewClass), alignof(AwraSplitViewClass));
    printf("%s;%zu;%zu\n", "AwraStatBarClass", sizeof(AwraStatBarClass), alignof(AwraStatBarClass));
    printf("%s;%zu;%zu\n", "AwraStatusAppearance", sizeof(AwraStatusAppearance), alignof(AwraStatusAppearance));
    printf("%s;%zu;%zu\n", "AwraStatusBannerClass", sizeof(AwraStatusBannerClass), alignof(AwraStatusBannerClass));
    printf("%s;%zu;%zu\n", "AwraStyleManagerClass", sizeof(AwraStyleManagerClass), alignof(AwraStyleManagerClass));
    printf("%s;%zu;%zu\n", "AwraSurfaceClass", sizeof(AwraSurfaceClass), alignof(AwraSurfaceClass));
    printf("%s;%zu;%zu\n", "AwraSurfaceCorner", sizeof(AwraSurfaceCorner), alignof(AwraSurfaceCorner));
    printf("%s;%zu;%zu\n", "AwraSurfaceEdge", sizeof(AwraSurfaceEdge), alignof(AwraSurfaceEdge));
    printf("%s;%zu;%zu\n", "AwraSurfaceRole", sizeof(AwraSurfaceRole), alignof(AwraSurfaceRole));
    printf("%s;%zu;%zu\n", "AwraSwitchClass", sizeof(AwraSwitchClass), alignof(AwraSwitchClass));
    printf("%s;%zu;%zu\n", "AwraTabViewClass", sizeof(AwraTabViewClass), alignof(AwraTabViewClass));
    printf("%s;%zu;%zu\n", "AwraTagEntryClass", sizeof(AwraTagEntryClass), alignof(AwraTagEntryClass));
    printf("%s;%zu;%zu\n", "AwraTextAreaClass", sizeof(AwraTextAreaClass), alignof(AwraTextAreaClass));
    printf("%s;%zu;%zu\n", "AwraToastOverlayClass", sizeof(AwraToastOverlayClass), alignof(AwraToastOverlayClass));
    printf("%s;%zu;%zu\n", "AwraToggleButtonClass", sizeof(AwraToggleButtonClass), alignof(AwraToggleButtonClass));
    printf("%s;%zu;%zu\n", "AwraTokenSetClass", sizeof(AwraTokenSetClass), alignof(AwraTokenSetClass));
    printf("%s;%zu;%zu\n", "AwraToolbarClass", sizeof(AwraToolbarClass), alignof(AwraToolbarClass));
    printf("%s;%zu;%zu\n", "AwraTypography", sizeof(AwraTypography), alignof(AwraTypography));
    printf("%s;%zu;%zu\n", "AwraValidationState", sizeof(AwraValidationState), alignof(AwraValidationState));
    printf("%s;%zu;%zu\n", "AwraWindow", sizeof(AwraWindow), alignof(AwraWindow));
    printf("%s;%zu;%zu\n", "AwraWindowClass", sizeof(AwraWindowClass), alignof(AwraWindowClass));
    return 0;
}
